In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("..\datasets\diabetic_data_initial.csv")

In [3]:
def data_overview(x):
 pd.set_option("display.max_columns",50)
 pd.set_option("display.max_rows", None)
 display(x.head(50))
 print(f"Number of rows:{x.shape[0]}\nNumber of columns:{x.shape[1]}")
 print(pd.DataFrame({
     "Data type:": x.dtypes,
     "Missing values:": x.isna().sum(), 
     "Percentage of na:": x.isna().mean()*100
 }))

In [47]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,A1Cresult,metformin,repaglinide,nateglinide,...,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,admission_type,discharge_disposition,admmission_source
0,2278392,8222157,Caucasian,Female,[0-10),NaN,25.0,1.0,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN,Not Mapped,Physician Referral
1,149190,55629189,Caucasian,Female,[10-20),1.0,1.0,7.0,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
2,64410,86047875,AfricanAmerican,Female,[20-30),1.0,1.0,7.0,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
3,500364,82442376,Caucasian,Male,[30-40),1.0,1.0,7.0,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
4,16680,42519267,Caucasian,Male,[40-50),1.0,1.0,7.0,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
5,35754,82637451,Caucasian,Male,[50-60),2.0,1.0,2.0,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
6,55842,84259809,Caucasian,Male,[60-70),3.0,1.0,2.0,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,NaN,Steady,No,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
7,63768,114882984,Caucasian,Male,[70-80),1.0,1.0,7.0,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
8,12522,48330783,Caucasian,Female,[80-90),2.0,1.0,4.0,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
9,15738,63555939,Caucasian,Female,[90-100),3.0,3.0,4.0,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,No,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
10,28236,89869032,AfricanAmerican,Female,[40-50),1.0,1.0,7.0,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
11,36900,77391171,AfricanAmerican,Male,[60-70),2.0,1.0,4.0,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,NaN,No,No,No,...,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Urgent,Discharged to home,Transfer from a hospital
12,40926,85504905,Caucasian,Female,[40-50),1.0,3.0,7.0,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,Steady,Up,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged/transferred to SNF,Emergency Room
13,42570,77586282,Caucasian,Male,[80-90),1.0,6.0,7.0,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
14,62256,49726791,AfricanAmerican,Female,[60-70),3.0,1.0,2.0,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Elective,Discharged to home,Clinic Referral
15,73578,86328819,AfricanAmerican,Male,[60-70),1.0,3.0,7.0,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
16,77076,92519352,AfricanAmerican,Male,[50-60),1.0,1.0,7.0,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged to home,Emergency Room
17,84222,108662661,Caucasian,Female,[50-60),1.0,1.0,7.0,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
18,89682,107389323,AfricanAmerican,Male,[70-80),1.0,1.0,7.0,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
19,148530,69422211,NaN,Male,[70-80),3.0,6.0,2.0,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,NaN,No,No,No,...,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to home with home healt...,Clinic Referral
20,150006,22864131,NaN,Female,[50-60),2.0,1.0,4.0,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
21,150048,21239181,NaN,Male,[60-70),2.0,1.0,4.0,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,NaN,Steady,No,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
22,182796,63000108,AfricanAmerican,Female,[70-80),2.0,1.0,4.0,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Urgent,Discharged to home,Transfer from a hospital
23,183930,107400762,Caucasian,Female,[80-90),2.0,6.0,1.0,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,Urgent,Discharged/transferred to home with home healt...,Physician Referral
24,216156,62718876,AfricanAmerican,Female,[70-80),3.0,1.0,2.0,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
25,221634,21861756,Other,Female,[50-60),1.0,1.0,7.0,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,NaN,Steady,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
26,236316,40523301,Caucasian,Male,[80-90),1.0,3.0,7.0,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,>7,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
27,248916,115196778,Caucasian,Female,[50-60),1.0,1.0,1.0,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Physician Referral
28,250872,41606064,Caucasian,Male,[20-30),2.0,1.0,2.0,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Clinic Referral
29,252822,18196434,Caucasian,Female,[80-90),1.0,2.0,7.0,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
30,253380,56480238,AfricanAmerican,Female,[60-70),1.0,1.0,7.0,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,NaN,No,No,No,...,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
31,253722,96664626,AfricanAmerican,Male,[70-80),1.0,5.0,7.0,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another type of inpa...,Emergency Room
32,260166,80845353,Caucasian,Female,[70-80),1.0,1.0,7.0,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
33,293058,114715242,Caucasian,Male,[60-70),2.0,6.0,2.0,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged/transferred to home with home healt...,Clinic Referral
34,293118,3327282,Caucasian,Female,[70-80),2.0,11.0,2.0,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Expired,Clinic Referral
35,325848,63023292,Caucasian,Female,[60-70),1.0,1.0,7.0,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,No,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
36,325866,98427861,Caucasian,Female,[70-80),3.0,1.0,2.0,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
37,326028,112002975,Caucasian,Female,[60-70),1.0,1.0,7.0,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,NaN,Steady,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
38,358776,101002446,Caucasian,Male,[70-80),1.0,6.0,7.0,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
39,377268,104672268,Caucasian,Male,[50-60),2.0,1.0,2.0,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
40,383430,80588529,Caucasian,Female,[70-80),1.0,2.0,7.0,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,Steady,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
41,419304,99715041,Caucasian,Male,[40-50),2.0,1.0,2.0,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
42,421194,96435585,Caucasian,Female,[70-80),2.0,1.0,1.0,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,NaN,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Physician Referral
43,449142,66274866,Caucasian,Male,[50-60),1.0,1.0,7.0,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,Steady,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
44,450210,80177094,Caucasian,Female,[80-90),1.0,11.0,7.0,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Expired,Emergency Room
45,464994,106936875,Caucasian,Female,[40-50),3.0,1.0,2.0,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
46,486156,86240259,Caucasian,Female,[70-80),3.0,5.0,4.0,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital
47,498030,51838164,Caucasian,Male,[70-80),3.0,3.0,4.0,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,NaN,Up,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
48,537834,90097839,Caucasian,Male,[50-60),3.0,1.0,2.0,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
49,544194,34997814,Caucasian,Male,[60-70),2.0,6.0,4.0,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital

Number of rows:101766
Number of columns:51
                         Data type:  Missing values:  Percentage of na:
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id           float64             5291           5.199182
discharge_disposition_id    float64             3691           3.626948
admission_source_id         float64             7110           6.986616
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000
admission_type               object             5291           5.199182
discharge_disposition        object             3691           3.626948
admmission_source            object             7110           6.986616

U skupu podataka uocava se string "?" koji predstavlja nedostajucu vrednost, ali je python tako ne prepoznaje pa ce "?" biti zamenjen sa NaN

In [5]:
def replacing_with_na(x):
   missing_value = "?"
   for column in x.columns:
        x[column]= x[column].replace(missing_value, np.nan)
   return x

In [6]:
data = replacing_with_na(data)

Kolone "weight" i "max_glu_serum" imaju visok procenat nedostajucih vrednosti(>94%), ali ce pre njihovog izbacivanja biti ispitano da li postoji neka zakonitost u podacima zbog koje je izostavljen veci deo ovih podataka.

In [7]:
data["weight"].describe()

count         3197
unique           9
top       [75-100)
freq          1336
Name: weight, dtype: object

In [8]:
data["max_glu_serum"].describe()

count     5346
unique       3
top       Norm
freq      2597
Name: max_glu_serum, dtype: object

Analizom distribucije dostupnih vrednosti za atribute weight i max_glu_serum nije uoceno da su podaci belezeni iskljucivo za ekstremne slucajeve. Najzastupljenije kategorije medju postojecim vrednostima odgovaraju uobicajenim vrednostima, sto ukazuje da nedostajanje ovih podataka verovatno nije posledica selektivnog belezenja samo kod pacijenata sa ekstremnim vrednostima.

In [9]:
def compare_column_with_all_columns(name_of_column):
 for column in data.columns:
    if column != name_of_column:
      display(pd.crosstab(data[name_of_column].dropna(), data[column].dropna(), normalize="index")*100)

In [10]:
data["has_weight"]= data["weight"].notna()

In [11]:
compare_column_with_all_columns("has_weight")

encounter_id,12522,15738,16680,28236,35754,36900,40926,42570,55842,62256,63768,64410,73578,77076,84222,89682,148530,149190,150006,150048,182796,183930,216156,221634,236316,...,443787128,443787512,443793668,443793992,443797076,443797298,443804570,443811536,443816024,443824292,443835140,443835512,443841992,443842016,443842022,443842070,443842136,443842340,443842778,443847176,443847548,443847782,443854148,443857166,443867222
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,...,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

patient_nbr,135,378,729,774,927,1152,1305,1314,1629,2025,3069,4302,5220,5337,6174,6228,6309,6696,6723,6939,7128,8154,8208,8460,8748,...,188755484,188755646,188846312,188858885,188903993,188928527,188970179,189001796,189052124,189075614,189097331,189129353,189169511,189179321,189195422,189215762,189257846,189298877,189332087,189349430,189351095,189365864,189445127,189481478,189502619
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002029,0.001015,0.001015,0.001015,0.001015,0.005073,0.001015,0.003044,0.000000,0.001015,0.001015,0.001015,0.004058,0.002029,0.001015,0.001015,0.001015,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,...,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

race        AfricanAmerican     Asian  Caucasian  Hispanic     Other
has_weight
False             19.803181  0.655371  75.898542  2.112326  1.530581
True               3.694018  0.294214  95.031056  0.000000  0.980713

gender         Female       Male  Unknown/Invalid
has_weight
False       53.830312  46.166645         0.003044
True        51.548327  48.451673         0.000000

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
has_weight,,,,,,,,,,
False,0.158265,0.682770,1.611054,3.743570,9.591251,16.999259,22.078950,25.494831,16.899837,2.740212
True,0.156397,0.563028,2.158273,2.658743,7.225524,15.639662,22.521114,29.340006,16.859556,2.877698

weight,>200,[0-25),[100-125),[125-150),[150-175),[175-200),[25-50),[50-75),[75-100)
has_weight,,,,,,,,,
True,0.093838,1.501408,19.549578,4.535502,1.094776,0.344073,3.034094,28.057554,41.789177

admission_type_id,1,2,3,4,5,6,7,8
has_weight,,,,,,,,
False,53.238848,18.31306,18.379004,0.008116,4.851424,4.863598,0.021305,0.324646
True,47.325618,13.41883,23.553331,0.062559,0.093838,15.545824,0.000000,0.000000

discharge_disposition_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,27,28
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,
False,59.134211,2.138603,13.672656,0.814658,1.140318,12.511033,0.623928,0.109568,0.021305,0.006087,1.624243,0.003044,0.373343,0.377401,0.063915,0.01116,0.014203,3.712120,0.008116,0.002029,2.021934,0.417981,0.048697,1.003358,0.005073,0.141018
True,60.869565,0.625586,14.920238,0.375352,1.876759,17.829215,0.250235,0.000000,0.000000,0.000000,1.282452,0.000000,0.969659,0.000000,0.000000,0.00000,0.000000,1.000938,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

admission_source_id,1,2,3,4,5,6,7,8,9,10,11,13,14,17,20,22,25
has_weight,,,,,,,,,,,,,,,,,
False,28.953322,1.120028,0.189715,3.092250,0.687843,2.163966,57.007781,0.016232,0.126815,0.008116,0.002029,0.001015,0.002029,6.451318,0.163337,0.012174,0.002029
True,32.092587,0.000000,0.000000,4.347826,5.536440,4.097591,40.725680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.199875,0.000000,0.000000,0.000000

time_in_hospital,1,2,3,4,5,6,7,8,9,10,11,12,13,14
has_weight,,,,,,,,,,,,,,
False,14.121073,16.991143,17.445647,13.657438,9.787053,7.326847,5.724924,4.288367,2.925869,2.294839,1.818016,1.416267,1.179884,1.022634
True,9.039725,14.888958,17.516422,14.451048,9.978104,9.915546,6.756334,5.129809,3.690960,2.502346,1.970597,1.626525,1.470128,1.063497

payer_code,BC,CH,CM,CP,DM,FR,HM,MC,MD,MP,OG,OT,PO,SI,SP,UN,WC
has_weight,,,,,,,,,,,,,,,,,
False,7.618887,0.244953,3.098235,3.974998,0.731481,0.001689,10.389391,52.747698,5.926176,0.133457,1.74508,0.158797,1.000084,0.092913,8.426387,3.495228,0.214545
True,6.263499,0.043197,4.449244,7.775378,5.010799,0.000000,5.356371,52.483801,1.036717,0.000000,0.00000,0.043197,0.000000,0.000000,0.820734,16.371490,0.345572

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,...,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.013952,0.023918,0.03787,9.471607,0.013952,0.011959,0.005980,0.001993,15.078432,0.239182,0.015945,14.518347,1.124155,0.115605,0.163441,0.412589,0.113611,0.073748,28.331108,3.215005,0.404616,0.001993,0.04983,0.03787,1.267665,...,1.654342,0.001993,0.013952,0.201312,1.736063,2.272229,0.105639,0.003986,0.033884,0.001993,0.001993,0.089693,0.195332,1.299556,0.021925,5.383588,0.021925,0.93281,0.015945,0.081721,0.001993,0.217257,1.062367,0.065775,1.365331
True,0.000000,0.000000,0.00000,36.452005,0.000000,0.000000,0.060753,0.000000,0.000000,0.000000,0.000000,9.477521,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.577157,0.000000,0.000000,0.000000,0.00000,0.00000,2.126367,...,1.458080,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.179830,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

num_lab_procedures,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,...,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,111,113,114,118,120,121,126,129,132
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,3.230225,1.103795,0.671611,0.355081,0.283050,0.286094,0.325660,0.368270,0.946545,0.840021,0.688858,0.499143,0.402764,0.320588,0.458562,0.544796,0.741612,0.720308,0.981039,0.760888,0.673640,0.694945,0.841035,0.749729,1.055098,...,0.044639,0.043624,0.027392,0.03145,0.024348,0.009131,0.011160,0.013189,0.007102,0.005073,0.002029,0.005073,0.005073,0.001015,0.004058,0.004058,0.003044,0.003044,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015
True,0.750704,0.406631,0.187676,0.875821,0.218955,0.000000,0.062559,0.093838,0.000000,0.312793,0.312793,0.437911,0.218955,0.625586,0.281514,0.218955,0.375352,0.625586,0.312793,0.406631,0.375352,0.281514,0.218955,0.156397,0.250235,...,0.031279,0.093838,0.031279,0.00000,0.062559,0.000000,0.062559,0.000000,0.031279,0.031279,0.031279,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

num_procedures,0,1,2,3,4,5,6
has_weight,,,,,,,
False,45.985046,20.321805,12.524222,9.241242,4.091550,2.996885,4.839250
True,41.445105,22.239600,11.635909,10.447294,4.598061,3.878636,5.755396

num_medications,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,...,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,72,74,75,79,81
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.259717,0.470736,0.889732,1.400034,2.006716,2.663109,3.435157,4.296483,4.868671,5.253173,5.716808,5.894348,5.962321,5.594051,5.656951,5.304913,4.799683,4.416196,4.002273,3.612698,3.170368,2.815287,2.380059,2.071645,1.855553,...,0.041595,0.050726,0.040581,0.033479,0.031450,0.037537,0.025363,0.023334,0.02029,0.022319,0.014203,0.015218,0.014203,0.008116,0.011160,0.005073,0.007102,0.007102,0.005073,0.002029,0.003044,0.001015,0.002029,0.001015,0.001015
True,0.187676,0.187676,0.719424,1.157335,1.219894,2.314670,3.065374,3.690960,3.565843,5.254926,5.004692,6.068189,6.537379,6.036910,6.756334,6.287144,5.880513,5.317485,4.160150,4.066312,3.284329,2.908977,2.502346,2.095715,1.845480,...,0.062559,0.125117,0.000000,0.000000,0.031279,0.000000,0.031279,0.062559,0.00000,0.031279,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_outpatient,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,34,35,36,37,38,39,40,42
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,84.387586,8.152665,3.308342,1.860626,0.980024,0.471751,0.276963,0.137974,0.088263,0.072031,0.047682,0.037537,0.029421,0.028406,0.026377,0.018261,0.014203,0.008116,0.005073,0.003044,0.007102,0.006087,0.005073,0.002029,0.003044,0.002029,0.002029,0.003044,0.001015,0.002029,0.002029,0.001015,0.002029,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015
True,57.772912,15.983735,10.416015,6.506099,4.160150,2.126994,0.938380,0.594307,0.344073,0.375352,0.312793,0.156397,0.031279,0.093838,0.062559,0.062559,0.031279,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_emergency,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,24,25,28,29,37,42,46,54,63,64,76
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,88.923495,7.463807,1.987440,0.704075,0.363197,0.189715,0.090292,0.073045,0.050726,0.032465,0.033479,0.022319,0.010145,0.011160,0.003044,0.003044,0.005073,0.005073,0.004058,0.004058,0.002029,0.006087,0.001015,0.002029,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015,0.001015
True,85.455114,10.009384,2.596184,0.969659,0.500469,0.156397,0.156397,0.031279,0.000000,0.031279,0.031279,0.031279,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_inpatient,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21
has_weight,,,,,,,,,,,,,,,,,,,,,
False,66.441782,19.138877,7.433372,3.372257,1.612069,0.802484,0.477838,0.269862,0.151163,0.109568,0.060871,0.049711,0.033479,0.02029,0.009131,0.009131,0.006087,0.001015,0.000000,0.001015,0.000000
True,66.906475,20.519237,7.475759,2.721301,1.032218,0.656866,0.281514,0.062559,0.062559,0.093838,0.031279,0.000000,0.031279,0.00000,0.031279,0.000000,0.000000,0.000000,0.031279,0.031279,0.031279

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,...,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001015,0.010147,0.002029,0.074076,0.001015,0.002029,0.009133,0.002029,0.001015,0.027398,0.005074,0.006088,0.004059,0.001015,0.001015,0.004059,0.002029,0.001015,0.002029,0.026383,0.060884,0.015221,0.304420,0.090311,0.053781,...,0.001015,0.078135,1.918862,0.410967,0.762065,0.029427,0.001015,0.001015,0.001015,0.002029,0.001015,0.004059,0.001015,0.039575,0.044648,0.067987,0.016236,1.126355,0.211065,0.001015,0.008118,0.002029,0.001015,0.001015,0.008118
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.062559,0.000000,0.344073,0.156397,0.031279,...,0.000000,0.031279,2.377229,0.594307,1.032218,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.156397,0.031279,0.125117,0.000000,3.034094,0.625586,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279

diag_2,11,110,111,112,114,115,117,123,130,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,...,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.003054,0.007127,0.001018,0.195474,0.001018,0.001018,0.008145,0.001018,0.001018,0.003054,0.113008,0.005090,0.001018,0.022398,0.001018,0.002036,0.001018,0.035633,0.022398,0.013235,0.101809,0.042760,0.033597,0.013235,0.086538,...,0.000000,0.260631,0.126243,0.011199,0.409273,0.011199,0.037669,0.001018,0.002036,0.073303,0.002036,0.008145,0.148641,0.001018,0.002036,0.064140,0.030543,0.026470,0.023416,0.00509,0.001018,0.007127,0.013235,0.169003,0.002036
True,0.000000,0.031397,0.000000,0.282575,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.125589,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.219780,0.094192,0.000000,0.094192,0.000000,...,0.031397,0.251177,0.188383,0.000000,0.188383,0.000000,0.062794,0.000000,0.000000,0.188383,0.000000,0.031397,0.345369,0.000000,0.000000,0.094192,0.000000,0.031397,0.000000,0.00000,0.000000,0.000000,0.000000,0.094192,0.000000

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,...,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002058,0.020582,0.001029,0.207883,0.001029,0.007204,0.001029,0.001029,0.006175,0.003087,0.062777,0.002058,0.018524,0.002058,0.001029,0.004116,0.001029,0.001029,0.013379,0.009262,0.002058,0.054544,0.013379,0.012349,0.004116,...,0.004116,0.002058,0.036019,0.245961,0.198621,0.027786,1.420191,0.061747,0.053514,0.007204,0.050427,0.008233,0.007204,0.502213,0.004116,0.005146,0.027786,0.013379,0.045281,0.024699,0.018524,0.002058,0.008233,0.097767,0.003087
True,0.000000,0.000000,0.000000,0.126064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.094548,0.000000,0.094548,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.031516,0.063032,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.063032,0.126064,0.567286,0.000000,0.283643,0.000000,0.063032,0.000000,0.283643,0.000000,0.000000,0.409707,0.000000,0.000000,0.063032,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000

number_diagnoses,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
has_weight,,,,,,,,,,,,,,,,
False,0.212034,1.023648,2.842679,5.539267,11.431586,10.118800,9.922998,10.538810,48.253508,0.017247,0.01116,0.009131,0.016232,0.007102,0.010145,0.045653
True,0.312793,0.437911,1.032218,2.408508,3.909916,5.849234,19.142947,7.131686,59.774789,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000

max_glu_serum       >200       >300       Norm
has_weight
False          27.777778  23.643846  48.578376

A1Cresult          >7         >8       Norm
has_weight
False       22.336852  48.218570  29.444578
True        25.433526  51.156069  23.410405

metformin       Down         No     Steady        Up
has_weight
False       0.561028  80.427924  17.980298  1.030750
True        0.688145  78.229590  19.487019  1.595246

repaglinide      Down         No    Steady        Up
has_weight
False        0.045653  98.478223  1.368584  0.107539
True         0.000000  98.780106  1.094776  0.125117

nateglinide     Down         No    Steady        Up
has_weight
False        0.01116  99.322302  0.645233  0.021305
True         0.00000  98.905224  1.000938  0.093838

chlorpropamide      Down         No    Steady        Up
has_weight
False           0.001015  99.914781  0.078118  0.006087
True            0.000000  99.937441  0.062559  0.000000

glimepiride      Down         No    Steady        Up
has_weight
False        0.189715  94.926397  4.569388  0.314501
True         0.218955  94.056928  5.192368  0.531749

acetohexamide          No    Steady
has_weight
False           99.998985  0.001015
True           100.000000  0.000000

glipizide       Down         No     Steady        Up
has_weight
False       0.542767  87.634043  11.094766  0.728424
True        0.781983  84.454176  13.137316  1.626525

glyburide       Down         No     Steady        Up
has_weight
False       0.547840  89.597135   9.068774  0.786251
True        0.750704  87.613388  10.478574  1.157335

tolbutamide         No    Steady
has_weight
False        99.977681  0.022319
True         99.968721  0.031279

pioglitazone      Down         No    Steady        Up
has_weight
False         0.114641  92.885187  6.775964  0.224208
True          0.156397  90.147013  9.289959  0.406631

rosiglitazone      Down         No    Steady        Up
has_weight
False          0.085219  93.753614  5.988698  0.172468
True           0.093838  93.493901  6.162027  0.250235

acarbose        Down         No    Steady        Up
has_weight
False       0.003044  99.704775  0.283050  0.009131
True        0.000000  99.468251  0.500469  0.031279

miglitol        Down          No   Steady        Up
has_weight
False       0.005073   99.961448  0.03145  0.002029
True        0.000000  100.000000  0.00000  0.000000

troglitazone          No    Steady
has_weight
False          99.996956  0.003044
True          100.000000  0.000000

tolazamide         No    Steady        Up
has_weight
False       99.961448  0.037537  0.001015
True        99.968721  0.031279  0.000000

examide        No
has_weight
False       100.0
True        100.0

citoglipton     No
has_weight
False        100.0
True         100.0

insulin          Down         No     Steady         Up
has_weight
False       12.300013  45.749678  30.584667  11.365642
True         2.940256  71.567094  21.958086   3.534564

glyburide-metformin      Down         No    Steady        Up
has_weight
False                0.006087   99.28375  0.702046  0.008116
True                 0.000000  100.00000  0.000000  0.000000

glipizide-metformin          No    Steady
has_weight
False                 99.986811  0.013189
True                 100.000000  0.000000

glimepiride-pioglitazone          No    Steady
has_weight
False                      99.998985  0.001015
True                      100.000000  0.000000

metformin-rosiglitazone          No    Steady
has_weight
False                     99.997971  0.002029
True                     100.000000  0.000000

metformin-pioglitazone          No    Steady
has_weight
False                    99.998985  0.001015
True                    100.000000  0.000000

change             Ch         No
has_weight
False       46.612018  53.387982
True        33.343760  66.656240

diabetesMed         No        Yes
has_weight
False        22.732299  77.267701
True         31.154207  68.845793

readmitted        <30        >30         NO
has_weight
False       11.159695  34.529112  54.311193
True        11.166719  47.231780  41.601501

Iako je analizirano da li nedostajanje atributa weight pokazuje povezanost sa drugim karakteristikama pacijenata, nije uocen dovoljno izrazen obrazac koji bi ukazivao na to da se merenje tezine vrsilo iskljucivo kod odredjene populacije pacijenata. Uocene su odredjene razlike izmedju pacijenata sa dostupnom i nedostupnom vrednoscu atributa, ali one nisu bile dovoljno izrazene da bi opravdale zadrzavanje promenljive sa veoma visokim procentom nedostajucih vrednosti (preko 94%). Zbog toga je atribut weight uklonjen iz dalje analize.

In [12]:
data = data.drop(["weight","has_weight"], axis= 1)

In [13]:
data["has_max_glu_serum"]= data["max_glu_serum"].notna()

In [14]:
compare_column_with_all_columns("has_max_glu_serum")

encounter_id,12522,15738,16680,28236,35754,36900,40926,42570,55842,62256,63768,64410,73578,77076,84222,89682,148530,149190,150006,150048,182796,183930,216156,221634,236316,...,443787128,443787512,443793668,443793992,443797076,443797298,443804570,443811536,443816024,443824292,443835140,443835512,443841992,443842016,443842022,443842070,443842136,443842340,443842778,443847176,443847548,443847782,443854148,443857166,443867222
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,...,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

patient_nbr,135,378,729,774,927,1152,1305,1314,1629,2025,3069,4302,5220,5337,6174,6228,6309,6696,6723,6939,7128,8154,8208,8460,8748,...,188755484,188755646,188846312,188858885,188903993,188928527,188970179,189001796,189052124,189075614,189097331,189129353,189169511,189179321,189195422,189215762,189257846,189298877,189332087,189349430,189351095,189365864,189445127,189481478,189502619
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002074,0.001037,0.001037,0.001037,0.001037,0.005186,0.001037,0.003111,0.001037,0.001037,0.001037,0.001037,0.004149,0.002074,0.001037,0.001037,0.001037,0.002074,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,...,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.002074,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.002074,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

race               AfricanAmerican     Asian  Caucasian  Hispanic     Other
has_max_glu_serum
False                    19.905948  0.652845  75.951934  1.964906  1.524368
True                      8.657845  0.491493  86.011342  3.516068  1.323251

gender                Female       Male  Unknown/Invalid
has_max_glu_serum
False              53.732628  46.264261         0.003111
True               54.227460  45.772540         0.000000

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
has_max_glu_serum,,,,,,,,,,
False,0.166978,0.701099,1.647998,3.733665,9.530180,17.151006,22.324207,25.420037,16.643850,2.680979
True,0.000000,0.280584,1.271979,3.273475,9.277965,13.449308,17.919940,29.143285,21.492705,3.890759

admission_type_id,1,2,3,4,5,6,7,8
has_max_glu_serum,,,,,,,,
False,55.108899,18.943165,19.545737,0.010371,2.097075,3.941091,0.02178,0.331881
True,15.974560,4.021698,0.430228,0.000000,51.683502,27.890011,0.00000,0.000000

discharge_disposition_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,27,28
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,
False,60.235428,1.992325,13.091682,0.834889,1.130471,12.460071,0.603609,0.104750,0.02178,0.001037,1.577474,0.003111,0.403443,0.321510,0.065339,0.002074,0.001037,3.828044,0.008297,0.001037,2.033810,0.424186,0.049782,0.657540,0.005186,0.142087
True,40.310513,3.872054,24.897119,0.187056,1.758324,16.610550,0.766929,0.130939,0.00000,0.093528,2.263374,0.000000,0.187056,1.159746,0.000000,0.168350,0.243172,0.000000,0.000000,0.018706,0.598578,0.056117,0.000000,6.640479,0.000000,0.037411

admission_source_id,1,2,3,4,5,6,7,8,9,10,11,13,14,17,20,22,25
has_max_glu_serum,,,,,,,,,,,,,,,,,
False,30.434557,1.123211,0.193943,3.304294,0.886745,2.348061,58.366521,0.016594,0.129641,0.008297,0.002074,0.001037,0.002074,3.001452,0.166978,0.012446,0.002074
True,4.115226,0.392817,0.000000,0.018706,0.000000,0.000000,22.764684,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,72.708567,0.000000,0.000000,0.000000

time_in_hospital,1,2,3,4,5,6,7,8,9,10,11,12,13,14
has_max_glu_serum,,,,,,,,,,,,,,
False,13.988799,17.060776,17.463182,13.639286,9.766646,7.356358,5.758141,4.271935,2.943373,2.300353,1.816013,1.393902,1.195810,1.045426
True,13.468013,14.478114,17.171717,14.459409,10.269360,8.342686,5.742611,5.087916,3.067714,2.319491,1.945380,1.945380,1.066218,0.635990

payer_code,BC,CH,CM,CP,DM,FR,HM,MC,MD,MP,OG,OT,PO,SI,SP,UN,WC
has_max_glu_serum,,,,,,,,,,,,,,,,,
False,7.673334,0.238271,3.233438,4.166387,0.899389,0.001678,9.923485,52.302168,5.815827,0.132559,1.733338,0.159407,0.993355,0.067119,8.368011,4.069065,0.223169
True,4.284222,0.208986,0.522466,2.612330,0.679206,0.000000,18.808777,66.300940,3.448276,0.000000,0.000000,0.000000,0.000000,0.783699,1.044932,1.201672,0.104493

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,...,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.014317,0.024543,0.03886,10.486164,0.014317,0.012272,0.006136,0.002045,15.468472,0.245434,0.016362,13.200254,1.086045,0.118626,0.167713,0.177940,0.116581,0.071585,28.314892,3.072014,0.413147,0.002045,0.051132,0.03886,1.347841,...,1.552369,0.002045,0.014317,0.206574,1.775305,2.327532,0.1084,0.004091,0.03477,0.002045,0.002045,0.092038,0.200438,1.333524,0.022498,5.669523,0.018408,0.957192,0.016362,0.081811,0.002045,0.222936,1.090136,0.067494,1.329434
True,0.000000,0.000000,0.00000,7.694938,0.000000,0.000000,0.034200,0.000000,0.068399,0.000000,0.000000,33.720930,1.128591,0.000000,0.000000,4.103967,0.000000,0.068399,27.051984,3.796170,0.034200,0.000000,0.000000,0.00000,0.410397,...,3.248974,0.000000,0.000000,0.000000,0.102599,0.068399,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.183311,0.068399,0.000000,0.000000,0.034200,0.000000,0.000000,0.000000,0.000000,1.196990

num_lab_procedures,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,...,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,111,113,114,118,120,121,126,129,132
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,3.325036,1.141879,0.690728,0.392035,0.296619,0.29247,0.333956,0.372329,0.790292,0.762290,0.594275,0.428334,0.380626,0.332918,0.256171,0.302842,0.284173,0.360921,0.661688,0.669985,0.622278,0.511305,0.491599,0.477079,0.718731,...,0.042522,0.042522,0.024891,0.031114,0.022817,0.009334,0.013483,0.012446,0.007260,0.005186,0.003111,0.005186,0.004149,0.001037,0.004149,0.004149,0.003111,0.003111,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037
True,0.037411,0.000000,0.037411,0.000000,0.000000,0.00000,0.018706,0.130939,3.198653,1.926674,2.169847,1.739618,0.692106,0.280584,4.002993,4.713805,8.772914,7.145529,6.341190,2.188552,1.421624,3.759820,6.771418,5.312383,6.640479,...,0.074822,0.093528,0.074822,0.018706,0.074822,0.000000,0.000000,0.018706,0.018706,0.018706,0.000000,0.018706,0.018706,0.000000,0.000000,0.000000,0.000000,0.000000,0.018706,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

num_procedures,0,1,2,3,4,5,6
has_max_glu_serum,,,,,,,
False,45.208463,20.269654,12.573118,9.442024,4.257415,3.149761,5.099564
True,57.276468,22.409278,11.111111,6.341190,1.402918,0.766929,0.692106

num_medications,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,...,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,72,74,75,79,81
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.262394,0.470857,0.880523,1.408421,1.984028,2.664385,3.438083,4.248081,4.800871,5.247874,5.648206,5.914748,5.966604,5.618129,5.662726,5.296619,4.847542,4.444099,3.999170,3.605061,3.150799,2.816843,2.372952,2.077370,1.855424,...,0.044597,0.056005,0.041485,0.034225,0.033188,0.038374,0.026965,0.025928,0.020743,0.023854,0.01452,0.015557,0.01452,0.008297,0.012446,0.005186,0.00726,0.00726,0.005186,0.002074,0.003111,0.001037,0.002074,0.001037,0.001037
True,0.168350,0.299289,0.953984,1.103629,1.945380,2.431725,3.161242,4.807333,5.312383,5.349794,6.528245,5.630378,6.228956,5.424617,6.210251,6.041900,4.582866,4.451927,4.152637,4.021698,3.591470,2.843247,2.581369,1.982791,1.851852,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_outpatient,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,34,35,36,37,38,39,40,42
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,84.306161,8.120722,3.327111,1.864758,0.999793,0.479154,0.283136,0.149347,0.099564,0.081933,0.057042,0.043559,0.030077,0.029040,0.02904,0.020743,0.015557,0.008297,0.005186,0.003111,0.00726,0.00726,0.005186,0.002074,0.003111,0.002074,0.002074,0.003111,0.001037,0.002074,0.002074,0.001037,0.001037,0.002074,0.001037,0.001037,0.001037,0.001037,0.001037
True,69.940142,13.411897,7.220352,4.564160,2.525253,1.328096,0.561167,0.205761,0.037411,0.074822,0.037411,0.000000,0.018706,0.056117,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018706,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_emergency,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,24,25,28,29,37,42,46,54,63,64,76
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,89.256378,7.277536,1.882390,0.681394,0.352624,0.182535,0.088156,0.071562,0.048745,0.033188,0.035262,0.023854,0.010371,0.012446,0.003111,0.003111,0.005186,0.005186,0.004149,0.004149,0.002074,0.005186,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037,0.001037
True,80.845492,12.345679,4.246165,1.271979,0.635990,0.299289,0.168350,0.074822,0.056117,0.018706,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018706,0.000000,0.018706,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

number_inpatient,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,
False,66.671852,19.133997,7.366729,3.315702,1.566065,0.784070,0.464634,0.252022,0.150384,0.108899,0.060153,0.049782,0.034225,0.019705,0.008297,0.007260,0.002074,0.001037,0.001037,0.001037,0.001037
True,62.570146,20.052376,8.660681,4.002993,2.095024,1.047512,0.598578,0.467639,0.112233,0.112233,0.056117,0.018706,0.018706,0.018706,0.037411,0.037411,0.074822,0.000000,0.000000,0.018706,0.000000

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,...,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001037,0.010373,0.002075,0.070539,0.001037,0.002075,0.009336,0.002075,0.001037,0.025934,0.004149,0.005187,0.004149,0.001037,0.001037,0.004149,0.002075,0.001037,0.002075,0.026971,0.060166,0.01556,0.304979,0.091286,0.053942,...,0.001037,0.078838,1.973029,0.411826,0.787344,0.025934,0.001037,0.001037,0.001037,0.002075,0.001037,0.005187,0.001037,0.045643,0.045643,0.068465,0.016598,1.181535,0.226141,0.001037,0.008299,0.001037,0.001037,0.001037,0.007261
True,0.000000,0.000000,0.000000,0.093545,0.000000,0.000000,0.000000,0.000000,0.000000,0.037418,0.018709,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.074836,0.00000,0.318054,0.112254,0.037418,...,0.000000,0.037418,1.216090,0.505145,0.467727,0.074836,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.093545,0.000000,1.272217,0.187091,0.000000,0.000000,0.018709,0.000000,0.000000,0.037418

diag_2,11,110,111,112,114,115,117,123,130,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,...,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.003123,0.007287,0.001041,0.196742,0.001041,0.001041,0.01041,0.001041,0.001041,0.003123,0.117629,0.005205,0.001041,0.020819,0.001041,0.002082,0.000000,0.034352,0.021860,0.011451,0.103055,0.046843,0.032270,0.016655,0.075990,...,0.001041,0.264404,0.135325,0.010410,0.415344,0.010410,0.040598,0.001041,0.002082,0.080154,0.002082,0.009369,0.157185,0.001041,0.002082,0.068703,0.031229,0.026024,0.023942,0.005205,0.001041,0.007287,0.012492,0.175923,0.002082
True,0.000000,0.018716,0.000000,0.224593,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.037432,0.018716,0.000000,0.037432,0.000000,0.000000,0.018716,0.037432,0.056148,0.037432,0.149729,0.000000,0.037432,0.000000,0.224593,...,0.000000,0.187161,0.000000,0.018716,0.168445,0.018716,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.112296,0.000000,0.000000,0.000000,0.000000,0.037432,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,...,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002104,0.016828,0.001052,0.207196,0.001052,0.006311,0.001052,0.001052,0.006311,0.003155,0.067312,0.002104,0.022087,0.002104,0.001052,0.004207,0.001052,0.001052,0.012621,0.009466,0.003155,0.055743,0.012621,0.012621,0.004207,...,0.004207,0.002104,0.038915,0.247163,0.221921,0.025242,1.406199,0.063105,0.056795,0.006311,0.057847,0.007362,0.007362,0.516413,0.004207,0.005259,0.030501,0.013673,0.044174,0.025242,0.018932,0.002104,0.008414,0.098865,0.003155
True,0.000000,0.075988,0.000000,0.170973,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.000000,0.037994,0.018997,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.151976,0.000000,0.056991,0.987842,0.000000,0.000000,0.018997,0.056991,0.018997,0.000000,0.189970,0.000000,0.000000,0.000000,0.000000,0.056991,0.000000,0.000000,0.000000,0.000000,0.037994,0.000000

number_diagnoses,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
has_max_glu_serum,,,,,,,,,,,,,,,,
False,0.224020,0.980087,2.720390,5.482265,11.166770,9.424393,10.300767,10.000000,49.582037,0.017631,0.011408,0.009334,0.016594,0.00726,0.010371,0.046671
True,0.056117,1.459035,3.965582,4.695099,11.709689,20.089787,8.623270,18.219229,31.182192,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000

max_glu_serum           >200       >300       Norm
has_max_glu_serum
True               27.777778  23.643846  48.578376

A1Cresult                 >7         >8       Norm
has_max_glu_serum
False              22.422249  48.080144  29.497608
True               21.140940  59.395973  19.463087

metformin              Down         No     Steady        Up
has_max_glu_serum
False              0.576644  80.080896  18.282514  1.059946
True               0.355406  85.372241  13.430602  0.841751

repaglinide            Down         No    Steady        Up
has_max_glu_serum
False              0.046671  98.434972  1.405310  0.113047
True               0.000000  99.438833  0.542462  0.018706

nateglinide            Down         No    Steady        Up
has_max_glu_serum
False              0.011408  99.272972  0.690728  0.024891
True               0.000000  99.962589  0.037411  0.000000

chlorpropamide         Down         No    Steady        Up
has_max_glu_serum
False              0.001037  99.918067  0.074673  0.006223
True               0.000000  99.869061  0.130939  0.000000

glimepiride            Down         No    Steady        Up
has_max_glu_serum
False              0.197055  94.723086  4.747978  0.331881
True               0.074822  98.073326  1.720913  0.130939

acetohexamide              No    Steady
has_max_glu_serum
False               99.998963  0.001037
True               100.000000  0.000000

glipizide              Down         No     Steady        Up
has_max_glu_serum
False              0.549678  87.570006  11.133582  0.746733
True               0.561167  86.887392  11.616162  0.935279

glyburide              Down         No    Steady        Up
has_max_glu_serum
False              0.546567  89.545737  9.111180  0.796515
True               0.692106  89.337823  9.147026  0.823045

tolbutamide               No    Steady
has_max_glu_serum
False              99.981332  0.018668
True               99.906472  0.093528

pioglitazone           Down         No    Steady        Up
has_max_glu_serum
False              0.114084  92.689276  6.965360  0.231280
True               0.149645  94.781145  4.863449  0.205761

rosiglitazone          Down         No    Steady        Up
has_max_glu_serum
False              0.086082  93.719145  6.019498  0.175275
True               0.074822  94.219978  5.536850  0.168350

acarbose               Down         No    Steady        Up
has_max_glu_serum
False              0.003111  99.699233  0.288322  0.009334
True               0.000000  99.663300  0.317995  0.018706

miglitol               Down          No    Steady        Up
has_max_glu_serum
False              0.005186   99.960589  0.032151  0.002074
True               0.000000  100.000000  0.000000  0.000000

troglitazone               No    Steady
has_max_glu_serum
False               99.996889  0.003111
True               100.000000  0.000000

tolazamide                No    Steady        Up
has_max_glu_serum
False              99.961626  0.037337  0.001037
True               99.962589  0.037411  0.000000

examide               No
has_max_glu_serum
False              100.0
True               100.0

citoglipton           No
has_max_glu_serum
False              100.0
True               100.0

insulin                 Down         No     Steady         Up
has_max_glu_serum
False              11.781788  46.494503  30.562124  11.161585
True               16.049383  47.755331  25.832398  10.362888

glyburide-metformin      Down         No    Steady        Up
has_max_glu_serum
False                0.006223  99.269861  0.715619  0.008297
True                 0.000000  99.962589  0.037411  0.000000

glipizide-metformin          No    Steady
has_max_glu_serum
False                 99.986517  0.013483
True                 100.000000  0.000000

glimepiride-pioglitazone          No    Steady
has_max_glu_serum
False                      99.998963  0.001037
True                      100.000000  0.000000

metformin-rosiglitazone          No    Steady
has_max_glu_serum
False                     99.997926  0.002074
True                     100.000000  0.000000

metformin-pioglitazone          No    Steady
has_max_glu_serum
False                    99.998963  0.001037
True                    100.000000  0.000000

change                    Ch         No
has_max_glu_serum
False              46.311968  53.688032
True               44.089039  55.910961

diabetesMed               No        Yes
has_max_glu_serum
False              22.806472  77.193528
True               26.430976  73.569024

readmitted               <30        >30         NO
has_max_glu_serum
False              11.093134  34.856876  54.049990
True               12.364385  36.213992  51.421624

Atribut max_glu_serum predstavlja znacajan medicinski pokazatelj, ali zbog veoma visokog procenta nedostajucih vrednosti (94.75%) i nepostojanja jasnog obrasca u nedostajanju, uklonjen je iz dalje analize.

In [15]:
data = data.drop(["max_glu_serum","has_max_glu_serum"], axis= 1)

In [16]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),1,1,7,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),2,1,4,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,NaN,No,No,No,No,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),1,3,7,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,Steady,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),1,6,7,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),3,1,2,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),1,3,7,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),1,1,7,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),1,1,7,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),1,1,7,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,NaN,Male,[70-80),3,6,2,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,NaN,No,No,No,No,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,NaN,Female,[50-60),2,1,4,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,NaN,Male,[60-70),2,1,4,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),2,1,4,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),2,6,1,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),3,1,2,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),1,1,7,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),1,3,7,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,>7,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),1,1,1,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),2,1,2,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),1,2,7,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),1,1,7,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,NaN,No,No,No,No,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),1,5,7,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),1,1,7,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),2,6,2,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
34,293118,3327282,Caucasian,Female,[70-80),2,11,2,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
35,325848,63023292,Caucasian,Female,[60-70),1,1,7,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),3,1,2,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),1,1,7,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),1,6,7,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),2,1,2,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),1,2,7,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),2,1,2,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),2,1,1,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),1,1,7,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
44,450210,80177094,Caucasian,Female,[80-90),1,11,7,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
45,464994,106936875,Caucasian,Female,[40-50),3,1,2,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),3,5,4,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),3,3,4,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,NaN,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),3,1,2,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),2,6,4,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

Number of rows:101766
Number of columns:48
                         Data type:  Missing values:  Percentage of na:
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id             int64                0           0.000000
discharge_disposition_id      int64                0           0.000000
admission_source_id           int64                0           0.000000
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000

In [17]:
data_id_mapping = pd.read_csv("../datasets/id_mapping.csv")

In [18]:
data_overview(data_id_mapping)

,ID mappings for the diabetes dataset,? - always means a missing value
0,admission_type_id,description
1,1,Emergency
2,2,Urgent
3,3,Elective
4,4,Newborn
5,5,Not Available
6,6,NaN
7,7,Trauma Center
8,8,Not Mapped
9,NaN,NaN
10,discharge_disposition_id,description
11,1,Discharged to home
12,2,Discharged/transferred to another short term h...
13,3,Discharged/transferred to SNF
14,4,Discharged/transferred to ICF
15,5,Discharged/transferred to another type of inpa...
16,6,Discharged/transferred to home with home healt...
17,7,Left AMA
18,8,Discharged/transferred to home under care of H...
19,9,Admitted as an inpatient to this hospital
20,10,Neonate discharged to another hospital for neo...
21,11,Expired
22,12,Still patient or expected to return for outpat...
23,13,Hospice / home
24,14,Hospice / medical facility
25,15,Discharged/transferred within this institution...
26,16,Discharged/transferred/referred another instit...
27,17,Discharged/transferred/referred to this instit...
28,18,NaN
29,19,"Expired at home. Medicaid only, hospice."
30,20,"Expired in a medical facility. Medicaid only, ..."
31,21,"Expired, place unknown. Medicaid only, hospice."
32,22,Discharged/transferred to another rehab fac in...
33,23,Discharged/transferred to a long term care hos...
34,24,Discharged/transferred to a nursing facility c...
35,25,Not Mapped
36,26,Unknown/Invalid
37,30,Discharged/transferred to another Type of Heal...
38,27,Discharged/transferred to a federal health car...
39,28,Discharged/transferred/referred to a psychiatr...
40,29,Discharged/transferred to a Critical Access Ho...
41,NaN,NaN
42,admission_source_id,description
43,1,Physician Referral
44,2,Clinic Referral
45,3,HMO Referral
46,4,Transfer from a hospital
47,5,Transfer from a Skilled Nursing Facility (SNF)
48,6,Transfer from another health care facility
49,7,Emergency Room

Number of rows:68
Number of columns:2
                                     Data type:  Missing values:  \
ID mappings for the diabetes dataset     object                2
 ? - always means a missing value        object                5

                                      Percentage of na:
ID mappings for the diabetes dataset           2.941176
 ? - always means a missing value              7.352941

Pored standardnih nedostajucih vrednosti potrebno je analizirati i tabelu id_mapping.csv i proveriti da li postoje sifre koje se takodje mogu tretirati kao NaN.

In [19]:
data_id_mapping.columns

Index(['ID mappings for the diabetes dataset', ' ? - always means a missing value'], dtype='object')

In [20]:
admission_mapping = data_id_mapping[0:9]

In [21]:
admission_mapping.head(12)

  ID mappings for the diabetes dataset  ? - always means a missing value
0                    admission_type_id                       description
1                                    1                         Emergency
2                                    2                            Urgent
3                                    3                          Elective
4                                    4                           Newborn
5                                    5                     Not Available
6                                    6                               NaN
7                                    7                     Trauma Center
8                                    8                        Not Mapped

In [22]:
admission_mapping.columns= admission_mapping.iloc[0]

In [23]:
admission_mapping= admission_mapping[1:].reset_index(drop=True)

In [24]:
discharge_disposition_mapping = data_id_mapping[10:41]

In [25]:
discharge_disposition_mapping.head(40)

,ID mappings for the diabetes dataset,? - always means a missing value
10,discharge_disposition_id,description
11,1,Discharged to home
12,2,Discharged/transferred to another short term h...
13,3,Discharged/transferred to SNF
14,4,Discharged/transferred to ICF
15,5,Discharged/transferred to another type of inpa...
16,6,Discharged/transferred to home with home healt...
17,7,Left AMA
18,8,Discharged/transferred to home under care of H...
19,9,Admitted as an inpatient to this hospital
20,10,Neonate discharged to another hospital for neo...
21,11,Expired
22,12,Still patient or expected to return for outpat...
23,13,Hospice / home
24,14,Hospice / medical facility
25,15,Discharged/transferred within this institution...
26,16,Discharged/transferred/referred another instit...
27,17,Discharged/transferred/referred to this instit...
28,18,NaN
29,19,"Expired at home. Medicaid only, hospice."
30,20,"Expired in a medical facility. Medicaid only, ..."
31,21,"Expired, place unknown. Medicaid only, hospice."
32,22,Discharged/transferred to another rehab fac in...
33,23,Discharged/transferred to a long term care hos...
34,24,Discharged/transferred to a nursing facility c...
35,25,Not Mapped
36,26,Unknown/Invalid
37,30,Discharged/transferred to another Type of Heal...
38,27,Discharged/transferred to a federal health car...
39,28,Discharged/transferred/referred to a psychiatr...
40,29,Discharged/transferred to a Critical Access Ho...

In [26]:
discharge_disposition_mapping.columns = discharge_disposition_mapping.iloc[0]

In [27]:
discharge_disposition_mapping = discharge_disposition_mapping[1:].reset_index(drop = True)

In [28]:
discharge_disposition_mapping.columns

Index(['discharge_disposition_id', 'description'], dtype='object', name=10)

In [29]:
discharge_disposition_mapping.columns.name = None

In [30]:
admission_source_mapping = data_id_mapping[42:50]

In [31]:
admission_source_mapping.head(20)

,ID mappings for the diabetes dataset,? - always means a missing value
42,admission_source_id,description
43,1,Physician Referral
44,2,Clinic Referral
45,3,HMO Referral
46,4,Transfer from a hospital
47,5,Transfer from a Skilled Nursing Facility (SNF)
48,6,Transfer from another health care facility
49,7,Emergency Room

In [32]:
admission_source_mapping.columns = admission_source_mapping.iloc[0]

In [33]:
admission_source_mapping = admission_source_mapping[1:].reset_index(drop=True)

In [34]:
admission_source_mapping.columns.name = None

In [35]:
def data_frame_to_dict(x):
 dictionary = dict(
 zip(
    x[x.columns[0]].astype(int),
    x[x.columns[1]]
 )  
 )
 return dictionary

In [36]:
admission_dict = data_frame_to_dict(admission_mapping)

In [37]:
discharge_dict  =data_frame_to_dict(discharge_disposition_mapping)

In [38]:
admission_source_dict = data_frame_to_dict(admission_source_mapping)

In [39]:
data_raw = data.copy()

In [40]:
data["admission_type"]= data["admission_type_id"].map(admission_dict)
data["discharge_disposition"] = data["discharge_disposition_id"].map(discharge_dict)
data["admmission_source"]= data["admission_source_id"].map(admission_source_dict)

In [46]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,A1Cresult,metformin,repaglinide,nateglinide,...,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,admission_type,discharge_disposition,admmission_source
0,2278392,8222157,Caucasian,Female,[0-10),NaN,25.0,1.0,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN,Not Mapped,Physician Referral
1,149190,55629189,Caucasian,Female,[10-20),1.0,1.0,7.0,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
2,64410,86047875,AfricanAmerican,Female,[20-30),1.0,1.0,7.0,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
3,500364,82442376,Caucasian,Male,[30-40),1.0,1.0,7.0,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
4,16680,42519267,Caucasian,Male,[40-50),1.0,1.0,7.0,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
5,35754,82637451,Caucasian,Male,[50-60),2.0,1.0,2.0,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
6,55842,84259809,Caucasian,Male,[60-70),3.0,1.0,2.0,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,NaN,Steady,No,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
7,63768,114882984,Caucasian,Male,[70-80),1.0,1.0,7.0,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
8,12522,48330783,Caucasian,Female,[80-90),2.0,1.0,4.0,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
9,15738,63555939,Caucasian,Female,[90-100),3.0,3.0,4.0,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,No,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
10,28236,89869032,AfricanAmerican,Female,[40-50),1.0,1.0,7.0,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
11,36900,77391171,AfricanAmerican,Male,[60-70),2.0,1.0,4.0,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,NaN,No,No,No,...,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Urgent,Discharged to home,Transfer from a hospital
12,40926,85504905,Caucasian,Female,[40-50),1.0,3.0,7.0,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,Steady,Up,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged/transferred to SNF,Emergency Room
13,42570,77586282,Caucasian,Male,[80-90),1.0,6.0,7.0,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
14,62256,49726791,AfricanAmerican,Female,[60-70),3.0,1.0,2.0,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Elective,Discharged to home,Clinic Referral
15,73578,86328819,AfricanAmerican,Male,[60-70),1.0,3.0,7.0,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
16,77076,92519352,AfricanAmerican,Male,[50-60),1.0,1.0,7.0,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged to home,Emergency Room
17,84222,108662661,Caucasian,Female,[50-60),1.0,1.0,7.0,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
18,89682,107389323,AfricanAmerican,Male,[70-80),1.0,1.0,7.0,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
19,148530,69422211,NaN,Male,[70-80),3.0,6.0,2.0,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,NaN,No,No,No,...,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to home with home healt...,Clinic Referral
20,150006,22864131,NaN,Female,[50-60),2.0,1.0,4.0,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
21,150048,21239181,NaN,Male,[60-70),2.0,1.0,4.0,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,NaN,Steady,No,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
22,182796,63000108,AfricanAmerican,Female,[70-80),2.0,1.0,4.0,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Urgent,Discharged to home,Transfer from a hospital
23,183930,107400762,Caucasian,Female,[80-90),2.0,6.0,1.0,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,Urgent,Discharged/transferred to home with home healt...,Physician Referral
24,216156,62718876,AfricanAmerican,Female,[70-80),3.0,1.0,2.0,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
25,221634,21861756,Other,Female,[50-60),1.0,1.0,7.0,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,NaN,Steady,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
26,236316,40523301,Caucasian,Male,[80-90),1.0,3.0,7.0,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,>7,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
27,248916,115196778,Caucasian,Female,[50-60),1.0,1.0,1.0,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Physician Referral
28,250872,41606064,Caucasian,Male,[20-30),2.0,1.0,2.0,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Clinic Referral
29,252822,18196434,Caucasian,Female,[80-90),1.0,2.0,7.0,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
30,253380,56480238,AfricanAmerican,Female,[60-70),1.0,1.0,7.0,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,NaN,No,No,No,...,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
31,253722,96664626,AfricanAmerican,Male,[70-80),1.0,5.0,7.0,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another type of inpa...,Emergency Room
32,260166,80845353,Caucasian,Female,[70-80),1.0,1.0,7.0,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
33,293058,114715242,Caucasian,Male,[60-70),2.0,6.0,2.0,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged/transferred to home with home healt...,Clinic Referral
34,293118,3327282,Caucasian,Female,[70-80),2.0,11.0,2.0,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Expired,Clinic Referral
35,325848,63023292,Caucasian,Female,[60-70),1.0,1.0,7.0,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,No,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
36,325866,98427861,Caucasian,Female,[70-80),3.0,1.0,2.0,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
37,326028,112002975,Caucasian,Female,[60-70),1.0,1.0,7.0,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,NaN,Steady,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
38,358776,101002446,Caucasian,Male,[70-80),1.0,6.0,7.0,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
39,377268,104672268,Caucasian,Male,[50-60),2.0,1.0,2.0,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
40,383430,80588529,Caucasian,Female,[70-80),1.0,2.0,7.0,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,Steady,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
41,419304,99715041,Caucasian,Male,[40-50),2.0,1.0,2.0,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
42,421194,96435585,Caucasian,Female,[70-80),2.0,1.0,1.0,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,NaN,Steady,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Physician Referral
43,449142,66274866,Caucasian,Male,[50-60),1.0,1.0,7.0,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,Steady,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
44,450210,80177094,Caucasian,Female,[80-90),1.0,11.0,7.0,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Expired,Emergency Room
45,464994,106936875,Caucasian,Female,[40-50),3.0,1.0,2.0,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
46,486156,86240259,Caucasian,Female,[70-80),3.0,5.0,4.0,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,No,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital
47,498030,51838164,Caucasian,Male,[70-80),3.0,3.0,4.0,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,NaN,Up,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
48,537834,90097839,Caucasian,Male,[50-60),3.0,1.0,2.0,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,NaN,No,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
49,544194,34997814,Caucasian,Male,[60-70),2.0,6.0,4.0,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,NaN,No,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital

Number of rows:101766
Number of columns:51
                         Data type:  Missing values:  Percentage of na:
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id           float64             5291           5.199182
discharge_disposition_id    float64             3691           3.626948
admission_source_id         float64             7110           6.986616
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000
admission_type               object             5291           5.199182
discharge_disposition        object             3691           3.626948
admmission_source            object             7110           6.986616

In [44]:
def id_to_na(col1,col2):
    for index,row in data.iterrows():
        if pd.isna(row[col2]):
            data.loc[index, col1] = np.nan

In [45]:
id_to_na("admission_type_id","admission_type")
id_to_na("discharge_disposition_id","discharge_disposition")
id_to_na("admission_source_id","admmission_source")

Svaki ID koji je u mapping tabeli bio označen kao NULL, zamenjen je vrednošću NaN u kolonama admission_type_id, discharge_disposition_id i admission_source_id.