In [93]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
from scipy.stats import kruskal

In [2]:
data = pd.read_csv("..\datasets\diabetic_data_initial.csv")

In [3]:
def data_overview(x):
 pd.set_option("display.max_columns",50)
 pd.set_option("display.max_rows", None)
 display(x.head(50))
 print(f"Number of rows:{x.shape[0]}\nNumber of columns:{x.shape[1]}")
 print(pd.DataFrame({
     "Data type:": x.dtypes,
     "Missing values:": x.isna().sum(), 
     "Percentage of na:": x.isna().mean()*100,
     "Value count:":  x.nunique()
 }))

In [4]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,?,?,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),?,3,1,2,4,?,?,70,1,21,0,0,0,414,411,V45,7,NaN,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),?,1,1,7,5,?,?,73,0,12,0,0,0,428,492,250,8,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),?,2,1,4,13,?,?,68,2,28,0,0,0,398,427,38,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),?,3,3,4,12,?,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),?,1,1,7,9,?,?,47,2,17,0,0,0,250.7,403,996,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),?,2,1,4,7,?,?,62,0,11,0,0,0,157,288,197,7,NaN,NaN,No,No,No,No,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),?,1,3,7,7,?,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,NaN,Steady,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),?,1,6,7,10,?,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),?,3,1,2,1,?,?,49,5,2,0,0,0,518,998,627,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),?,1,3,7,12,?,?,75,5,13,0,0,0,999,507,996,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),?,1,1,7,4,?,?,45,4,17,0,0,0,410,411,414,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),?,1,1,7,3,?,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),?,1,1,7,5,?,?,35,5,23,0,0,0,402,425,416,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,?,Male,[70-80),?,3,6,2,6,?,?,42,2,23,0,0,0,737,427,714,8,NaN,NaN,No,No,No,No,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,?,Female,[50-60),?,2,1,4,2,?,?,66,1,19,0,0,0,410,427,428,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,?,Male,[60-70),?,2,1,4,2,?,?,36,2,11,0,0,0,572,456,427,6,NaN,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),?,2,1,4,2,?,?,47,0,12,0,0,0,410,401,582,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),?,2,6,1,11,?,?,42,2,19,0,0,0,V57,715,V43,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),?,3,1,2,3,?,?,19,4,18,0,0,0,189,496,427,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),?,1,1,7,1,?,?,33,0,7,0,0,0,786,401,250,3,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),?,1,3,7,6,?,Cardiology,64,3,18,0,0,0,427,428,414,7,NaN,>7,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),?,1,1,1,2,?,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),?,2,1,2,10,?,?,53,0,20,0,0,0,277,250.02,263,6,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),?,1,2,7,5,?,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),?,1,1,7,6,?,?,87,0,18,0,0,0,584,496,250.42,9,NaN,NaN,No,No,No,No,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),?,1,5,7,1,?,?,53,0,10,0,0,0,462,250.01,276,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),?,1,1,7,6,?,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),?,2,6,2,5,?,?,37,0,18,0,0,0,473,996,482,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
34,293118,3327282,Caucasian,Female,[70-80),?,2,11,2,5,?,?,46,2,20,0,0,0,428,585,414,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
35,325848,63023292,Caucasian,Female,[60-70),?,1,1,7,2,?,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),?,3,1,2,3,?,?,33,1,8,0,0,0,174,135,250,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),?,1,1,7,4,?,?,33,0,12,0,0,0,486,244,250,3,NaN,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),?,1,6,7,7,?,?,47,2,22,0,0,0,998,41,414,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),?,2,1,2,1,?,?,44,1,15,0,0,0,996,403,250.41,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),?,1,2,7,1,?,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),?,2,1,2,7,?,?,36,2,9,0,0,0,511,571,585,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),?,2,1,1,13,?,?,48,2,18,0,0,1,V57,276,781,8,NaN,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),?,1,1,7,3,?,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
44,450210,80177094,Caucasian,Female,[80-90),?,1,11,7,7,?,?,72,1,27,0,0,0,432,997,427,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
45,464994,106936875,Caucasian,Female,[40-50),?,3,1,2,2,?,?,10,3,8,0,0,0,626,250.01,998,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),?,3,5,4,9,?,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),?,3,3,4,9,?,?,2,0,12,0,0,1,295,599,250,3,NaN,NaN,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),?,3,1,2,6,?,?,65,5,19,0,0,0,414,424,428,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),?,2,6,4,11,?,?,67,2,25,0,0,0,428,491,427,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

Number of rows:101766
Number of columns:50
                         Data type:  Missing values:  Percentage of na:  \
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object                0           0.000000
gender                       object                0           0.000000
age                          object                0           0.000000
weight                       object                0           0.000000
admission_type_id             int64                0           0.000000
discharge_disposition_id      int64                0           0.000000
admission_source_id           int64                0           0.000000
time_in_hospital              int64                0           0.000000
payer_code                   object                0           0.000000
medical_specialty            object                0           0.000000
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object                0           0.000000
diag_2                       object                0           0.000000
diag_3                       object                0           0.000000
number_diagnoses              int64                0           0.000000
max_glu_serum                object            96420          94.746772
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000

                          Value count:
encounter_id                    101766
patient_nbr                      71518
race                                 6
gender                               3
age                                 10
weight                              10
admission_type_id                    8
discharge_disposition_id            26
admission_source_id                 17
time_in_hospital                    14
payer_code                          18
medical_specialty                   73
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             717
diag_2                             749
diag_3                             790
number_diagnoses                    16
max_glu_serum                        3
A1Cresult                            3
metformin                            4
repaglinide                          4
nateglinide                          4
chlorpropamide                       4
glimepiride                          4
acetohexamide                        2
glipizide                            4
glyburide                            4
tolbutamide                          2
pioglitazone                         4
rosiglitazone                        4
acarbose                             4
miglitol                             4
troglitazone                         2
tolazamide                           3
examide                              1
citoglipton                          1
insulin                              4
glyburide-metformin                  4
glipizide-metformin                  2
glimepiride-pioglitazone             2
metformin-rosiglitazone              2
metformin-pioglitazone               2
change                               2
diabetesMed                          2
readmitted                           3

U skupu podataka uocava se string "?" koji predstavlja nedostajucu vrednost, ali je python tako ne prepoznaje pa ce "?" biti zamenjen sa NaN

In [5]:
def replacing_with_na(x):
   missing_value = "?"
   for column in x.columns:
        x[column]= x[column].replace(missing_value, np.nan)
   return x

In [6]:
data = replacing_with_na(data)

Kolone "weight" i "max_glu_serum" imaju visok procenat nedostajucih vrednosti(>94%), ali ce pre njihovog izbacivanja biti ispitano da li postoji neka zakonitost u podacima zbog koje je izostavljen veci deo ovih podataka.

In [7]:
data["weight"].describe()

count         3197
unique           9
top       [75-100)
freq          1336
Name: weight, dtype: object

In [8]:
data["max_glu_serum"].describe()

count     5346
unique       3
top       Norm
freq      2597
Name: max_glu_serum, dtype: object

Analizom distribucije dostupnih vrednosti za atribute weight i max_glu_serum nije uoceno da su podaci belezeni iskljucivo za ekstremne slucajeve. Najzastupljenije kategorije medju postojecim vrednostima odgovaraju uobicajenim vrednostima, sto ukazuje da nedostajanje ovih podataka verovatno nije posledica selektivnog belezenja samo kod pacijenata sa ekstremnim vrednostima.

In [9]:
def compare_column_with_all_columns(name_of_column):
 pd.set_option("display.max_columns", None)
 for column in data.columns:
    if column != name_of_column:
        if data[column].dtype == "object" and data[name_of_column].dtype=="object":
          display(pd.crosstab(data[name_of_column], data[column], normalize="index") *100)
        else:
            print(f"\n--- {column} ---")
            display(data.groupby(name_of_column)[column].describe())

In [10]:
data["has_weight"]= data["weight"].notna()
data["has_weight"].dtype
data["has_weight"]= data["has_weight"].astype("object")

In [11]:
compare_column_with_all_columns("has_weight")
data["has_weight"].value_counts()

--- encounter_id ---

,count,mean,std,min,25%,50%,75%,max
has_weight,,,,,,,,
False,98569.0,1.655019e+08,1.026795e+08,12522.0,85035102.0,152907534.0,230816256.0,443867222.0
True,3197.0,1.559442e+08,1.010020e+08,8042082.0,83230266.0,127781592.0,212779206.0,443695760.0

--- patient_nbr ---

,count,mean,std,min,25%,50%,75%,max
has_weight,,,,,,,,
False,98569.0,5.378262e+07,3.879460e+07,135.0,23368149.0,44297208.0,87170085.0,189502619.0
True,3197.0,7.121929e+07,3.112114e+07,1629.0,54222390.0,76705218.0,95722092.0,186768005.0

race        AfricanAmerican     Asian  Caucasian  Hispanic     Other
has_weight
False             19.803181  0.655371  75.898542  2.112326  1.530581
True               3.694018  0.294214  95.031056  0.000000  0.980713

gender         Female       Male  Unknown/Invalid
has_weight
False       53.830312  46.166645         0.003044
True        51.548327  48.451673         0.000000

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
has_weight,,,,,,,,,,
False,0.158265,0.682770,1.611054,3.743570,9.591251,16.999259,22.078950,25.494831,16.899837,2.740212
True,0.156397,0.563028,2.158273,2.658743,7.225524,15.639662,22.521114,29.340006,16.859556,2.877698

weight,>200,[0-25),[100-125),[125-150),[150-175),[175-200),[25-50),[50-75),[75-100)
has_weight,,,,,,,,,
True,0.093838,1.501408,19.549578,4.535502,1.094776,0.344073,3.034094,28.057554,41.789177

--- admission_type_id ---

              count      mean       std  min  25%  50%  75%  max
has_weight
False       98569.0  2.012195  1.432961  1.0  1.0  1.0  3.0  8.0
True         3197.0  2.388176  1.748526  1.0  1.0  2.0  3.0  6.0

--- discharge_disposition_id ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  3.748187  5.337341  1.0  1.0  1.0  4.0  28.0
True         3197.0  2.712230  2.850754  1.0  1.0  1.0  3.0  18.0

--- admission_source_id ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  5.742830  4.031089  1.0  1.0  7.0  7.0  25.0
True         3197.0  6.112293  4.962522  1.0  1.0  7.0  7.0  17.0

--- time_in_hospital ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  4.382778  2.983971  1.0  2.0  4.0  6.0  14.0
True         3197.0  4.803253  2.991919  1.0  3.0  4.0  6.0  14.0

payer_code,BC,CH,CM,CP,DM,FR,HM,MC,MD,MP,OG,OT,PO,SI,SP,UN,WC
has_weight,,,,,,,,,,,,,,,,,
False,7.618887,0.244953,3.098235,3.974998,0.731481,0.001689,10.389391,52.747698,5.926176,0.133457,1.74508,0.158797,1.000084,0.092913,8.426387,3.495228,0.214545
True,6.263499,0.043197,4.449244,7.775378,5.010799,0.000000,5.356371,52.483801,1.036717,0.000000,0.00000,0.043197,0.000000,0.000000,0.820734,16.371490,0.345572

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,Oncology,Ophthalmology,Orthopedics,Orthopedics-Reconstructive,Osteopath,Otolaryngology,OutreachServices,Pathology,Pediatrics,Pediatrics-AllergyandImmunology,Pediatrics-CriticalCare,Pediatrics-EmergencyMedicine,Pediatrics-Endocrinology,Pediatrics-Hematology-Oncology,Pediatrics-InfectiousDiseases,Pediatrics-Neurology,Pediatrics-Pulmonology,Perinatology,PhysicalMedicineandRehabilitation,PhysicianNotFound,Podiatry,Proctology,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.013952,0.023918,0.03787,9.471607,0.013952,0.011959,0.005980,0.001993,15.078432,0.239182,0.015945,14.518347,1.124155,0.115605,0.163441,0.412589,0.113611,0.073748,28.331108,3.215005,0.404616,0.001993,0.04983,0.03787,1.267665,0.693628,0.075741,2.790457,2.457595,0.077734,0.249148,0.023918,0.033884,0.484344,0.00598,0.173407,0.00598,0.316916,0.007973,0.001993,0.019932,0.04983,0.001993,0.779335,0.021925,0.199318,0.001993,1.654342,0.001993,0.013952,0.201312,1.736063,2.272229,0.105639,0.003986,0.033884,0.001993,0.001993,0.089693,0.195332,1.299556,0.021925,5.383588,0.021925,0.93281,0.015945,0.081721,0.001993,0.217257,1.062367,0.065775,1.365331
True,0.000000,0.000000,0.00000,36.452005,0.000000,0.000000,0.060753,0.000000,0.000000,0.000000,0.000000,9.477521,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.577157,0.000000,0.000000,0.000000,0.00000,0.00000,2.126367,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.668287,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.458080,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.179830,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

--- num_lab_procedures ---

              count       mean        std  min   25%   50%   75%    max
has_weight
False       98569.0  42.769786  19.610886  1.0  31.0  44.0  56.0  132.0
True         3197.0  53.142321  18.970172  1.0  41.0  55.0  68.0  105.0

--- num_procedures ---

              count      mean       std  min  25%  50%  75%  max
has_weight
False       98569.0  1.334801  1.703007  0.0  0.0  1.0  2.0  6.0
True         3197.0  1.491711  1.783584  0.0  0.0  1.0  2.0  6.0

--- num_medications ---

              count      mean       std  min   25%   50%   75%   max
has_weight
False       98569.0  16.01115  8.135118  1.0  10.0  15.0  20.0  81.0
True         3197.0  16.35158  7.885302  1.0  11.0  15.0  20.0  65.0

--- number_outpatient ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  0.346001  1.235617  0.0  0.0  0.0  0.0  42.0
True         3197.0  1.089459  1.874539  0.0  0.0  0.0  2.0  21.0

--- number_emergency ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  0.196664  0.935510  0.0  0.0  0.0  0.0  76.0
True         3197.0  0.233969  0.758141  0.0  0.0  0.0  0.0  13.0

--- number_inpatient ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  0.637543  1.264208  0.0  0.0  0.0  1.0  19.0
True         3197.0  0.574601  1.219299  0.0  0.0  0.0  1.0  21.0

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,170,171,172,173,174,175,179,180,182,183,184,185,187,188,189,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,207,208,210,211,212,214,215,216,217,218,219,220,223,225,226,227,228,229,23,230,233,235,236,237,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,261,262,263,266,27,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,31,310,311,312,314,318,320,322,323,324,325,327,331,332,333,334,335,336,337,338,34,340,341,342,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,36,360,361,362,363,365,366,368,369,370,372,373,374,375,376,377,378,379,38,380,381,382,383,384,385,386,388,389,39,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,461,462,463,464,465,466,47,470,471,473,474,475,477,478,48,480,481,482,483,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,518,519,52,521,522,523,524,526,527,528,529,53,530,531,532,533,534,535,536,537,54,540,541,542,543,550,551,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,58,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,61,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,632,633,634,637,640,641,642,643,644,645,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,671,674,680,681,682,683,684,685,686,690,691,692,693,694,695,696,698,7,70,700,703,704,705,706,707,708,709,710,711,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,745,746,747,75,751,753,756,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,803,804,805,806,807,808,810,812,813,814,815,816,817,82,820,821,822,823,824,825,826,827,831,832,833,834,835,836,837,838,839,84,840,842,843,844,845,846,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,873,875,878,879,88,880,881,882,883,885,886,890,891,892,893,895,897,9,903,904,906,911,913,914,915,916,917,919,920,921,922,923,924,928,933,934,935,936,939,94,941,942,944,945,952,955,957,958,959,962,963,964,965,966,967,968,969,97,970,971,972,973,974,975,976,977,98,980,982,983,986,987,988,989,990,991,992,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001015,0.010147,0.002029,0.074076,0.001015,0.002029,0.009133,0.002029,0.001015,0.027398,0.005074,0.006088,0.004059,0.001015,0.001015,0.004059,0.002029,0.001015,0.002029,0.026383,0.060884,0.015221,0.304420,0.090311,0.053781,0.018265,0.112635,0.012177,0.001015,0.012177,0.424159,0.009133,0.003044,0.002029,0.011162,0.004059,0.003044,0.145107,0.005074,0.004059,0.006088,0.100459,0.031457,0.008118,0.166416,0.002029,0.104518,0.121768,0.044648,0.004059,0.027398,0.002029,0.009133,0.024354,0.312538,0.236433,0.014206,0.016236,0.009133,0.101473,0.035516,0.019280,0.026383,0.001015,0.004059,0.007103,0.101473,0.008118,0.006088,0.004059,0.001015,0.001015,0.120753,0.001015,0.043634,0.006088,0.041604,0.01928,0.044648,0.005074,0.002029,0.002029,0.008118,0.025368,0.027398,0.002029,0.007103,0.061899,0.029427,0.003044,0.055810,0.022324,0.011162,0.004059,0.001015,0.230345,0.054796,0.677842,0.203962,0.311523,0.600722,0.421115,0.840200,0.109591,0.012177,0.156269,0.029427,0.018265,0.015221,0.01725,0.01928,0.262816,0.090311,0.091326,0.025368,0.008118,0.001015,0.004059,0.004059,1.171003,0.870642,1.651987,0.184682,0.409953,0.093356,0.007103,0.004059,0.050737,0.01725,0.015221,0.022324,0.050737,0.024354,0.003044,0.003044,0.012177,0.003044,0.002029,0.003044,0.006088,0.006088,0.096400,0.053781,1.883346,0.034501,0.384584,0.002029,0.317612,0.020295,0.069002,0.025368,0.058855,0.367334,0.045663,0.086252,0.092341,0.01928,0.085238,0.092341,0.100459,0.055810,0.114665,0.437350,0.858465,0.013192,0.062914,0.001015,0.013192,0.091326,0.004059,0.069002,0.028413,0.025368,0.010147,0.024354,0.003044,0.035516,0.003044,0.010147,0.053781,0.017250,0.001015,0.001015,0.007103,0.002029,0.010147,0.005074,0.001015,0.024354,0.186711,0.053781,0.035516,0.002029,0.009133,0.003044,0.010147,0.020295,0.006088,0.042619,0.005074,0.008118,0.006088,0.114665,0.075090,0.001015,0.152210,0.034501,0.008118,0.010147,0.029427,0.002029,0.005074,0.009133,0.01725,0.005074,0.020295,0.013192,0.008118,0.002029,0.002029,0.005074,0.008118,0.001015,0.001015,0.001015,0.012177,0.002029,0.003044,0.001015,0.001015,0.003044,0.001015,0.011162,0.003044,0.013192,0.005074,1.687503,0.020295,0.001015,0.004059,0.009133,0.002029,0.002029,0.134960,0.005074,0.001015,0.002029,0.001015,0.010147,0.005074,0.026383,0.005074,0.128871,0.345010,0.418070,0.510411,0.254698,0.002029,0.008118,3.536348,0.250639,0.001015,0.116694,6.446605,0.444453,0.064943,0.002029,0.045663,0.063928,0.041604,0.002029,0.071031,0.175549,0.080164,0.277022,2.659618,6.810894,0.036530,0.030442,0.167431,0.088282,0.770183,2.012217,1.003572,0.175549,0.088282,0.082193,0.798596,0.126842,0.032471,0.109591,0.156269,0.007103,0.022324,0.061899,0.002029,0.039575,0.005074,0.541868,0.009133,0.092341,0.022324,0.012177,0.412997,0.094370,0.020295,0.011162,0.005074,0.010147,0.046678,0.233389,0.026383,0.004059,0.001015,0.022324,0.004059,0.014206,0.001015,0.031457,0.002029,0.018265,0.069002,0.336892,0.005074,0.041604,3.488655,0.101473,0.005074,0.086252,2.244591,0.031457,1.046191,0.023339,0.005074,0.080164,0.008118,0.002029,0.003044,0.003044,0.608840,0.005074,0.032471,0.266875,0.044648,0.015221,0.043634,0.121768,0.034501,1.112148,0.046678,0.002029,0.011162,0.025368,0.001015,0.004059,0.007103,0.026383,0.020295,0.004059,0.053781,0.521573,0.264846,0.213094,0.022324,0.022324,0.453586,0.150181,0.106547,0.012177,0.200917,0.009133,0.002029,0.001015,0.051751,0.007103,0.229330,0.134960,0.051751,0.045663,0.192799,0.335877,0.875715,0.977189,0.146122,0.012177,0.084223,0.056825,0.032471,0.281081,0.001015,0.006088,0.278037,0.237448,0.040589,0.947761,0.215124,0.097414,1.053294,0.653489,0.006088,0.002029,0.002029,0.018265,0.002029,0.005074,1.499777,0.076105,0.021309,0.009133,0.332833,0.016236,0.341965,0.098429,0.014206,0.095385,0.048707,0.005074,1.567764,0.204976,0.016236,0.003044,0.003044,0.035516,0.001015,0.021309,0.066972,0.001015,0.002029,0.034501,0.021309,0.002029,0.023339,0.018265,0.153225,0.005074,0.047692,0.020295,0.005074,0.004059,0.064943,0.079149,0.018265,0.003044,0.004059,0.002029,0.001015,0.001015,0.008118,0.061899,0.004059,0.025368,0.002029,0.010147,0.005074,0.285140,0.001015,0.012177,0.002029,0.091326,0.004059,0.021309,0.002029,0.023339,0.029427,0.006088,0.012177,0.024354,0.007103,0.018265,0.003044,0.003044,0.001015,0.004059,0.014206,0.112635,2.028453,0.002029,0.001015,0.006088,0.008118,0.001015,0.001015,0.005074,0.023339,0.006088,0.012177,0.006088,0.001015,0.002029,0.046678,0.001015,0.002029,0.001015,0.010147,0.003044,0.255713,0.008118,0.008118,0.024354,0.063928,0.038560,2.005114,0.054796,0.006088,0.016236,0.054796,0.004059,0.170475,0.749888,0.077120,0.414011,0.011162,0.085238,0.045663,0.125827,0.101473,0.224256,0.004059,0.002029,0.360231,0.004059,0.002029,0.013192,0.008118,0.054796,0.006088,0.007103,0.007103,0.002029,0.005074,0.005074,0.012177,0.005074,0.009133,1.982790,0.107562,0.083208,0.029427,0.150181,0.098429,3.967610,0.265860,0.036530,0.547956,0.083208,0.140033,0.001015,0.005074,0.004059,0.025368,0.003044,0.006088,0.003044,0.064943,0.510411,0.006088,0.032471,0.029427,0.003044,0.001015,0.185696,0.006088,0.083208,0.133945,0.010147,0.230345,0.082193,0.004059,0.007103,0.008118,0.001015,0.007103,1.068515,0.141048,0.048707,0.127856,0.306450,0.021309,0.003044,0.001015,0.008118,0.001015,0.001015,0.001015,0.005074,0.006088,0.001015,0.001015,0.001015,0.001015,0.013192,0.001015,0.012177,0.028413,0.010147,0.004059,0.012177,0.002029,0.052766,0.032471,0.107562,0.017250,0.005074,0.035516,0.013192,0.003044,0.004059,0.007103,0.007103,0.007103,0.014206,0.003044,0.001015,0.002029,0.016236,0.002029,0.002029,0.003044,0.009133,0.002029,0.003044,0.010147,0.006088,0.001015,0.004059,0.006088,0.009133,0.010147,0.005074,0.001015,0.002029,0.046678,0.001015,0.002029,0.001015,0.001015,0.002029,0.002029,0.001015,0.004059,0.003044,0.001015,0.022324,0.003044,0.040589,0.004059,0.052766,0.003044,0.014206,0.006088,0.013192,0.003044,0.001015,0.006088,0.002029,0.005074,0.002029,0.012177,0.008118,0.001015,0.001015,0.020295,0.044648,0.056825,0.003044,0.008118,0.053781,0.012177,0.01725,0.007103,0.056825,0.001015,0.008118,0.003044,0.01725,0.002029,0.001015,0.002029,0.001015,0.013192,0.001015,0.002029,0.001015,0.005074,0.003044,0.003044,0.001015,0.011162,0.001015,0.007103,0.008118,0.001015,0.078135,1.918862,0.410967,0.762065,0.029427,0.001015,0.001015,0.001015,0.002029,0.001015,0.004059,0.001015,0.039575,0.044648,0.067987,0.016236,1.126355,0.211065,0.001015,0.008118,0.002029,0.001015,0.001015,0.008118
True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.062559,0.000000,0.344073,0.156397,0.031279,0.000000,0.093838,0.000000,0.000000,0.000000,0.218955,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.125117,0.000000,0.000000,0.000000,0.281514,0.000000,0.062559,0.281514,0.000000,0.281514,0.187676,0.031279,0.000000,0.031279,0.000000,0.000000,0.031279,0.375352,0.281514,0.000000,0.000000,0.031279,0.125117,0.000000,0.125117,0.031279,0.000000,0.031279,0.000000,0.093838,0.000000,0.000000,0.031279,0.000000,0.000000,0.250235,0.000000,0.093838,0.031279,0.156397,0.00000,0.062559,0.000000,0.000000,0.000000,0.031279,0.125117,0.000000,0.031279,0.000000,0.031279,0.125117,0.000000,0.093838,0.000000,0.000000,0.000000,0.031279,0.250235,0.218955,0.218955,0.000000,0.187676,1.032218,0.062559,0.719424,0.187676,0.000000,0.062559,0.000000,0.062559,0.000000,0.00000,0.00000,0.250235,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.907100,0.406631,1.626525,0.125117,0.250235,0.093838,0.000000,0.000000,0.062559,0.00000,0.000000,0.031279,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,1.032218,0.000000,0.000000,0.000000,0.187676,0.000000,0.000000,0.093838,0.093838,0.093838,0.000000,0.031279,0.031279,0.00000,0.062559,0.000000,0.250235,0.031279,0.093838,0.500469,1.563966,0.031279,0.062559,0.000000,0.000000,0.000000,0.000000,0.031279,0.125117,0.000000,0.000000,0.031279,0.000000,0.062559,0.000000,0.062559,0.125117,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.250235,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.093838,0.062559,0.000000,0.000000,0.000000,0.250235,0.000000,0.062559,0.031279,0.062559,0.031279,0.031279,0.000000,0.031279,0.000000,0.00000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.031279,0.000000,0.781983,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.375352,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.125117,0.000000,0.031279,0.187676,1.157335,0.312793,0.344073,0.031279,0.000000,4.035033,0.218955,0.000000,0.062559,7.131686,0.344073,0.125117,0.000000,0.000000,0.031279,0.000000,0.000000,0.062559,0.312793,0.218955,0.469190,4.535502,4.691899,0.031279,0.062559,0.218955,0.156397,0.938380,1.407570,0.844542,0.062559,0.093838,0.125117,1.657804,0.125117,0.062559,0.062559,0.062559,0.000000,0.031279,0.062559,0.000000,0.031279,0.000000,0.375352,0.000000,0.093838,0.062559,0.000000,0.594307,0.125117,0.000000,0.000000,0.000000,0.000000,0.062559,0.187676,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.062559,0.218955,0.000000,0.031279,2.189553,0.062559,0.000000,0.156397,1.970597,0.031279,0.781983,0.031279,0.000000,0.031279,0.031279,0.000000,0.000000,0.000000,0.312793,0.000000,0.031279,0.218955,0.062559,0.031279,0.000000,0.187676,0.000000,0.594307,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062559,0.531749,0.469190,0.281514,0.000000,0.062559,0.093838,0.062559,0.187676,0.000000,0.000000,0.000000,0.000000,0.000000,0.062559,0.031279,0.250235,0.250235,0.031279,0.031279,0.187676,0.125117,0.406631,0.813262,0.093838,0.000000,0.062559,0.031279,0.000000,0.281514,0.000000,0.000000,0.093838,0.156397,0.031279,0.969659,0.093838,0.031279,0.594307,0.594307,0.031279,0.000000,0.000000,0.031279,0.000000,0.000000,1.313732,0.000000,0.000000,0.000000,0.218955,0.093838,0.406631,0.125117,0.000000,0.031279,0.000000,0.000000,1.563966,0.156397,0.000000,0.000000,0.000000,0.062559,0.000000,0.000000,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.031279,0.312793,0.000000,0.000000,0.062559,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.093838,0.031279,0.062559,0.000000,0.000000,0.000000,0.125117,0.000000,0.031279,0.000000,0.062559,0.031279,0.000000,0.000000,0.093838,0.093838,0.000000,0.000000,0.031279,0.000000,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,1.345011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156397,0.000000,0.000000,0.031279,0.093838,0.062559,5.473882,0.031279,0.031279,0.031279,0.031279,0.000000,0.312793,1.000938,0.031279,1.000938,0.031279,0.218955,0.093838,0.093838,0.187676,0.281514,0.000000,0.000000,0.375352,0.000000,0.000000,0.031279,0.000000,0.062559,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.093838,0.000000,0.000000,2.033156,0.093838,0.062559,0.000000,0.093838,0.125117,3.315608,0.156397,0.093838,0.656866,0.125117,0.187676,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.125117,0.375352,0.000000,0.031279,0.031279,0.000000,0.000000,0.156397,0.000000,0.031279,0.125117,0.000000,0.250235,0.062559,0.031279,0.000000,0.031279,0.000000,0.000000,0.907100,0.187676,0.062559,0.031279,0.437911,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.125117,0.093838,0.125117,0.031279,0.000000,0.062559,0.000000,0.000000,0.000000,0.031279,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.062559,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.031279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.093838,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.000000,0.031279,0.000000,0.00000,0.031279,0.062559,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.031279,0.000000,0.031279,2.377229,0.594307,1.032218,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279,0.000000,0.156397,0.031279,0.125117,0.000000,3.034094,0.625586,0.000000,0.000000,0.000000,0.000000,0.000000,0.031279

diag_2,11,110,111,112,114,115,117,123,130,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,162,163,164,171,172,173,174,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,212,214,215,217,218,220,223,225,226,227,228,232,233,235,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,266,268,269,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,31,310,311,312,314,316,317,318,319,320,322,323,324,325,327,331,332,333,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,360,362,364,365,366,368,369,372,373,374,376,377,378,379,38,380,381,382,383,386,388,389,394,395,396,397,398,40,401,402,403,404,405,41,410,411,412,413,414,415,416,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,446,447,448,451,452,453,454,455,456,457,458,459,46,460,461,462,463,464,465,466,470,472,473,474,475,477,478,480,481,482,483,484,485,486,487,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,517,518,519,52,520,521,522,523,524,527,528,529,53,530,531,532,533,534,535,536,537,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,634,641,642,644,645,646,647,648,649,652,654,656,658,659,66,661,663,664,665,670,674,680,681,682,683,684,685,686,691,692,693,694,695,696,698,7,70,701,702,703,704,705,706,707,709,710,711,712,713,714,715,716,717,718,719,721,722,723,724,725,726,727,728,729,730,731,733,734,736,737,738,741,742,745,746,747,748,75,750,751,752,753,754,755,756,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,806,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,832,833,836,837,840,842,843,844,845,846,847,850,851,852,853,860,861,862,863,864,865,866,867,868,869,870,871,872,873,879,88,880,881,882,883,884,891,892,893,894,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,927,933,934,94,942,944,945,947,948,952,953,955,958,959,96,962,963,965,967,968,969,972,974,975,977,980,987,989,99,990,991,992,994,995,996,997,998,999,E812,E813,E814,E816,E817,E818,E819,E821,E826,E829,E849,E850,E853,E854,E858,E868,E870,E878,E879,E880,E881,E882,E883,E884,E885,E887,E888,E890,E900,E905,E906,E915,E916,E917,E918,E919,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E944,E945,E947,E950,E965,E968,E980,V02,V03,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V23,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.003054,0.007127,0.001018,0.195474,0.001018,0.001018,0.008145,0.001018,0.001018,0.003054,0.113008,0.005090,0.001018,0.022398,0.001018,0.002036,0.001018,0.035633,0.022398,0.013235,0.101809,0.042760,0.033597,0.013235,0.086538,0.397056,0.001018,0.001018,0.002036,0.007127,0.001018,0.027488,0.002036,0.001018,0.001018,0.014253,0.027488,0.001018,0.009163,0.048868,0.014253,0.001018,0.003054,0.001018,0.206673,0.407237,0.310518,0.012217,0.018326,0.019344,0.178166,0.089592,0.11199,0.057013,0.008145,0.052941,0.001018,0.007127,0.002036,0.003054,0.041742,0.008145,0.001018,0.00509,0.002036,0.006109,0.002036,0.001018,0.010181,0.001018,0.017308,0.003054,0.002036,0.011199,0.093664,0.149659,0.004072,0.004072,6.016921,1.526119,2.098287,0.237215,0.017308,0.079411,0.097737,0.104863,0.010181,0.004072,0.038687,0.003054,0.001018,0.001018,0.004072,0.00509,0.166967,0.227034,0.104863,0.036651,0.065158,0.065158,0.057013,0.025452,0.897957,0.131334,0.206673,0.091628,0.180202,0.038687,0.007127,0.008145,0.198528,0.022398,0.010181,0.020362,0.04276,0.066176,0.001018,0.004072,0.003054,0.010181,0.015271,0.013235,0.174094,0.007127,0.001018,0.002036,0.003054,0.001018,0.001018,0.404182,0.008145,0.02647,0.033597,6.748928,0.061085,0.270812,0.011199,0.590493,0.017308,0.050905,0.020362,0.161877,1.487432,0.118099,0.302373,0.074321,0.039706,0.048868,0.074321,0.091628,0.075339,0.154750,0.408255,0.158822,0.006109,0.020362,0.008145,0.144569,0.055995,0.001018,0.284048,0.170021,0.697393,0.004072,0.012217,0.003054,0.049886,0.004072,0.004072,0.081447,0.024434,0.012217,0.001018,0.010181,0.002036,0.018326,0.004072,0.007127,0.00509,0.008145,0.001018,0.034615,0.107918,0.042760,0.016289,0.010181,0.006109,0.049886,0.015271,0.010181,0.119117,0.002036,0.220926,0.005090,0.068212,0.041742,0.020362,0.001018,0.140497,0.035633,0.001018,0.001018,0.003054,0.002036,0.001018,0.010181,0.004072,0.012217,0.072284,0.028507,0.014253,0.003054,0.030543,0.001018,0.008145,0.002036,0.022398,0.007127,0.004072,0.003054,0.001018,0.003054,0.003054,0.012217,0.003054,0.476467,0.008145,0.002036,0.013235,0.003054,0.022398,0.001018,0.006109,0.020362,0.003054,0.121153,0.054977,0.039706,0.012217,3.633569,0.312554,2.814005,0.197510,0.002036,0.327825,0.543661,2.556428,0.100791,1.035399,2.600206,0.105882,0.095701,0.086538,0.025452,0.02138,0.004072,0.016289,0.953952,1.418201,0.301355,4.935708,6.585016,0.030543,0.006109,0.015271,0.022398,0.151696,0.186311,0.092646,0.025452,0.069230,0.253505,0.404182,0.039706,0.013235,0.077375,0.107918,0.032579,0.025452,0.002036,0.031561,0.007127,0.342079,0.006109,0.031561,0.075339,0.007127,0.144569,0.050905,0.001018,0.001018,0.010181,0.014253,0.003054,0.001018,0.054977,0.104863,0.003054,0.002036,0.038687,0.002036,0.000000,0.003054,0.029525,0.00509,0.039706,0.105882,0.002036,0.004072,0.010181,1.375442,0.018326,0.052941,1.549535,0.224998,0.873522,0.012217,0.00509,3.288435,0.001018,0.00509,0.004072,0.001018,0.193437,0.006109,0.011199,0.514136,0.042760,0.00509,0.012217,0.160858,0.028507,0.011199,1.351007,0.030543,0.001018,0.001018,0.00509,0.004072,0.001018,0.008145,0.004072,0.005090,0.001018,0.032579,0.285066,0.045814,0.025452,0.009163,0.002036,0.187329,0.198528,0.030543,0.010181,0.012217,0.003054,0.001018,0.014253,0.047850,0.077375,0.021380,0.017308,0.035633,0.109954,0.392983,0.142533,0.081447,0.009163,0.020362,0.091628,0.064140,0.169003,0.014253,0.412327,0.083484,0.044796,0.342079,0.064140,0.084502,0.400110,0.342079,0.009163,0.001018,0.079411,0.020362,1.611639,1.868198,0.010181,0.004072,0.134388,0.229071,0.073303,0.123189,0.006109,0.067194,0.057013,0.004072,3.281309,0.037669,0.021380,0.002036,0.003054,0.006109,0.001018,0.014253,0.010181,0.002036,0.023416,0.019344,0.001018,0.022398,0.018326,0.034615,0.007127,0.027488,0.008145,0.001018,0.004072,0.046832,0.026470,0.012217,0.002036,0.002036,0.027488,0.004072,0.003054,0.007127,0.00509,0.330880,0.002036,0.003054,0.002036,0.003054,0.001018,0.003054,0.001018,0.002036,0.002036,0.004072,0.001018,0.001018,0.001018,0.023416,0.034615,1.427364,0.001018,0.006109,0.006109,0.006109,0.003054,0.00509,0.011199,0.006109,0.002036,0.014253,0.00509,0.001018,0.272849,0.007127,0.001018,0.001018,0.001018,0.008145,0.009163,1.980188,0.009163,0.159840,0.041742,0.006109,0.004072,0.039706,0.123189,0.02138,0.011199,0.011199,0.050905,0.062104,0.137442,0.058031,0.142533,0.004072,0.026470,0.022398,0.126243,0.084502,0.239251,0.073303,0.179184,0.001018,0.017308,0.011199,0.024434,0.009163,0.002036,0.013235,0.008145,0.00509,0.001018,0.002036,0.008145,0.003054,0.001018,0.016289,0.001018,0.002036,0.011199,0.007127,0.006109,0.002036,1.486414,0.119117,0.073303,0.024434,0.18122,0.518209,0.646488,0.202600,0.381784,0.339024,0.028507,0.221944,0.006109,0.012217,0.00509,0.061085,0.002036,0.008145,0.002036,0.312554,0.196492,0.001018,0.004072,0.025452,0.079411,0.004072,0.041742,0.043778,0.004072,0.001018,0.037669,0.023416,0.002036,0.002036,0.011199,0.055995,0.018326,0.004072,0.014253,0.018326,0.008145,0.003054,0.004072,0.001018,0.000000,0.008145,0.003054,0.015271,0.003054,0.001018,0.00509,0.008145,0.001018,0.004072,0.029525,0.00509,0.015271,0.002036,0.020362,0.009163,0.003054,0.001018,0.005090,0.00509,0.002036,0.010181,0.00509,0.002036,0.003054,0.001018,0.001018,0.039706,0.001018,0.001018,0.001018,0.009163,0.007127,0.007127,0.001018,0.006109,0.007127,0.001018,0.001018,0.006109,0.012217,0.002036,0.00509,0.001018,0.00509,0.006109,0.002036,0.001018,0.003054,0.001018,0.002036,0.001018,0.002036,0.002036,0.021380,0.004072,0.008145,0.009163,0.023416,0.001018,0.003054,0.006109,0.02647,0.001018,0.001018,0.002036,0.001018,0.001018,0.002036,0.001018,0.001018,0.015271,0.012217,0.001018,0.001018,0.000000,0.003054,0.002036,0.001018,0.006109,0.003054,0.001018,0.001018,0.001018,0.002036,0.001018,0.004072,0.001018,0.001018,0.003054,0.002036,0.001018,0.110972,0.439816,0.371603,0.559950,0.033597,0.006109,0.000000,0.002036,0.002036,0.001018,0.001018,0.002036,0.001018,0.001018,0.001018,0.044796,0.001018,0.002036,0.001018,0.004072,0.001018,0.001018,0.079411,0.013235,0.017308,0.002036,0.001018,0.001018,0.012217,0.096719,0.003054,0.093664,0.001018,0.000000,0.003054,0.003054,0.001018,0.002036,0.005090,0.001018,0.001018,0.003054,0.005090,0.014253,0.000000,0.008145,0.003054,0.034615,0.004072,0.006109,0.013235,0.004072,0.00509,0.001018,0.013235,0.001018,0.025452,0.005090,0.001018,0.016289,0.009163,0.001018,0.001018,0.001018,0.004072,0.001018,0.007127,0.010181,0.100791,0.002036,0.068212,0.001018,0.003054,0.128280,0.002036,0.009163,0.008145,0.003054,0.000000,0.260631,0.126243,0.011199,0.409273,0.011199,0.037669,0.001018,0.002036,0.073303,0.002036,0.008145,0.148641,0.001018,0.002036,0.064140,0.030543,0.026470,0.023416,0.00509,0.001018,0.007127,0.013235,0.169003,0.002036
True,0.000000,0.031397,0.000000,0.282575,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.125589,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.219780,0.094192,0.000000,0.094192,0.000000,0.345369,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.031397,0.000000,0.313972,0.313972,0.470958,0.031397,0.031397,0.031397,0.219780,0.062794,0.21978,0.062794,0.000000,0.062794,0.000000,0.031397,0.000000,0.000000,0.094192,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,0.125589,0.031397,0.000000,5.054945,0.753532,0.408163,0.000000,0.000000,0.031397,0.000000,0.031397,0.062794,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.00000,0.188383,0.156986,0.000000,0.031397,0.031397,0.062794,0.000000,0.000000,0.408163,0.031397,0.062794,0.125589,0.000000,0.031397,0.000000,0.000000,0.188383,0.000000,0.000000,0.031397,0.00000,0.125589,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.722135,0.000000,0.00000,0.062794,3.861852,0.031397,0.125589,0.000000,0.816327,0.031397,0.000000,0.000000,0.282575,1.852433,0.031397,0.439560,0.062794,0.062794,0.031397,0.031397,0.219780,0.062794,0.156986,0.219780,0.282575,0.000000,0.000000,0.000000,0.156986,0.282575,0.000000,0.251177,0.125589,0.533752,0.000000,0.031397,0.000000,0.062794,0.000000,0.031397,0.062794,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.031397,0.000000,0.062794,0.062794,0.031397,0.000000,0.031397,0.000000,0.094192,0.000000,0.000000,0.062794,0.000000,0.188383,0.031397,0.000000,0.062794,0.062794,0.000000,0.062794,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.219780,0.031397,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.219780,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,1.883830,0.439560,0.000000,0.000000,5.243328,0.879121,1.852433,0.282575,0.031397,1.789639,0.470958,1.726845,0.094192,0.784929,3.014129,0.094192,0.062794,0.000000,0.000000,0.00000,0.000000,0.000000,4.207221,1.287284,0.156986,5.902669,6.091052,0.062794,0.000000,0.031397,0.000000,0.031397,0.125589,0.062794,0.000000,0.031397,0.439560,0.282575,0.062794,0.094192,0.000000,0.000000,0.000000,0.031397,0.031397,0.031397,0.000000,0.313972,0.000000,0.031397,0.062794,0.000000,0.094192,0.094192,0.000000,0.000000,0.000000,0.062794,0.000000,0.031397,0.031397,0.125589,0.000000,0.000000,0.031397,0.000000,0.031397,0.000000,0.031397,0.00000,0.000000,0.062794,0.000000,0.000000,0.000000,0.879121,0.000000,0.031397,0.722135,0.031397,0.722135,0.000000,0.00000,2.354788,0.000000,0.00000,0.000000,0.000000,0.156986,0.000000,0.000000,0.439560,0.125589,0.00000,0.000000,0.125589,0.031397,0.000000,0.879121,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.000000,0.313972,0.031397,0.031397,0.000000,0.000000,0.282575,0.094192,0.000000,0.000000,0.000000,0.000000,0.031397,0.031397,0.062794,0.031397,0.031397,0.031397,0.094192,0.000000,0.251177,0.062794,0.000000,0.000000,0.031397,0.062794,0.188383,0.282575,0.000000,0.282575,0.031397,0.062794,0.313972,0.031397,0.031397,0.251177,0.439560,0.000000,0.000000,0.062794,0.031397,2.072214,1.130298,0.000000,0.031397,0.062794,0.251177,0.156986,0.031397,0.031397,0.031397,0.125589,0.031397,2.040816,0.031397,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.031397,0.062794,0.031397,0.000000,0.062794,0.000000,0.031397,0.031397,0.031397,0.031397,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.00000,0.408163,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156986,0.973312,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.156986,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,1.695447,0.000000,0.251177,0.062794,0.000000,0.062794,0.000000,0.031397,0.00000,0.000000,0.031397,1.255887,0.031397,0.125589,0.031397,0.125589,0.000000,0.031397,0.125589,0.188383,0.282575,0.345369,0.251177,0.313972,0.000000,0.031397,0.000000,0.031397,0.000000,0.031397,0.062794,0.251177,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.973312,0.188383,0.062794,0.000000,0.21978,0.219780,0.282575,0.282575,0.439560,0.313972,0.031397,0.219780,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.251177,0.188383,0.000000,0.000000,0.000000,0.031397,0.000000,0.156986,0.094192,0.000000,0.000000,0.062794,0.000000,0.000000,0.031397,0.031397,0.000000,0.062794,0.000000,0.000000,0.031397,0.031397,0.031397,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.062794,0.031397,0.00000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.031397,0.062794,0.000000,0.000000,0.000000,0.062794,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.094192,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156986,0.690738,0.502355,0.659341,0.031397,0.062794,0.031397,0.000000,0.031397,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.313972,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,1.098901,0.219780,0.062794,0.062794,0.000000,0.000000,0.282575,0.533752,0.000000,0.533752,0.000000,0.031397,0.000000,0.000000,0.000000,0.000000,0.031397,0.000000,0.000000,0.000000,0.031397,0.031397,0.031397,0.000000,0.000000,0.125589,0.031397,0.125589,0.345369,0.094192,0.00000,0.000000,0.000000,0.031397,0.282575,0.188383,0.000000,0.156986,0.031397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.000000,0.062794,0.000000,0.000000,0.000000,0.000000,0.031397,0.251177,0.188383,0.000000,0.188383,0.000000,0.062794,0.000000,0.000000,0.188383,0.000000,0.031397,0.345369,0.000000,0.000000,0.094192,0.000000,0.031397,0.000000,0.00000,0.000000,0.000000,0.000000,0.094192,0.000000

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,157,158,161,162,163,164,17,170,171,172,173,174,175,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,214,215,216,217,218,220,223,225,226,227,228,230,233,235,236,238,239,240,241,242,243,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,265,266,268,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,310,311,312,313,314,315,317,318,319,323,327,331,332,333,334,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,353,354,355,356,357,358,359,360,361,362,365,365.44,366,368,369,370,372,373,374,376,377,378,379,38,380,381,382,383,384,385,386,387,388,389,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,47,470,472,473,475,477,478,480,481,482,483,484,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,514,515,516,517,518,519,521,522,523,524,525,527,528,529,53,530,531,532,533,534,535,536,537,538,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,607,608,610,611,614,616,617,618,619,620,621,622,623,624,625,626,627,641,642,643,644,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,670,671,674,680,681,682,684,685,686,690,692,693,694,695,696,697,698,7,70,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,741,742,744,745,746,747,75,750,751,752,753,754,755,756,757,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,834,836,837,838,840,841,842,844,845,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,872,873,875,876,877,879,88,880,881,882,883,884,890,891,892,893,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,928,930,933,934,935,94,942,943,944,945,948,951,952,953,955,956,958,959,962,965,966,967,969,970,971,972,980,987,989,991,992,995,996,997,998,999,E812,E813,E815,E816,E817,E818,E819,E822,E825,E826,E828,E849,E850,E852,E853,E854,E855,E858,E861,E864,E865,E870,E876,E878,E879,E880,E881,E882,E883,E884,E885,E886,E887,E888,E892,E894,E900,E901,E904,E905,E906,E912,E915,E916,E917,E919,E920,E922,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E943,E944,E945,E946,E947,E949,E950,E955,E956,E965,E966,E980,E987,V01,V02,V03,V06,V07,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V22,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
has_weight,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002058,0.020582,0.001029,0.207883,0.001029,0.007204,0.001029,0.001029,0.006175,0.003087,0.062777,0.002058,0.018524,0.002058,0.001029,0.004116,0.001029,0.001029,0.013379,0.009262,0.002058,0.054544,0.013379,0.012349,0.004116,0.039107,0.000000,0.003087,0.180097,0.005146,0.001029,0.001029,0.004116,0.004116,0.005146,0.001029,0.044252,0.001029,0.007204,0.003087,0.005146,0.014408,0.051456,0.001029,0.015437,0.026757,0.004116,0.002058,0.001029,0.001029,0.103942,0.379747,0.232582,0.045281,0.009262,0.011320,0.118349,0.067922,0.064835,0.019553,0.010291,0.098796,0.003087,0.001029,0.002058,0.001029,0.050427,0.005146,0.002058,0.006175,0.001029,0.006175,0.007204,0.001029,0.005146,0.004116,0.000000,0.034990,0.006175,0.005146,0.009262,0.078213,0.001029,0.538232,0.003087,0.006175,11.588968,0.923124,1.402696,0.137903,0.020582,0.016466,0.039107,0.010291,0.008233,0.004116,0.015437,0.002058,0.002058,0.001029,0.430174,0.201708,0.132757,0.059689,0.112175,0.128641,0.075126,0.033961,1.081610,0.144077,0.320058,0.051456,0.116291,0.020582,0.009262,0.006175,0.151281,0.014408,0.007204,0.023670,0.048369,0.067922,0.003087,0.003087,0.004116,0.009262,0.015437,0.008233,0.258310,0.001029,0.016466,0.003087,0.001029,0.007204,0.002058,1.941957,0.012349,0.066893,0.086446,5.227951,0.039107,0.690542,0.010291,0.397242,0.037048,0.042194,0.012349,0.138932,1.173202,0.125553,0.385922,0.114233,0.039107,0.082330,0.044252,0.064835,0.079243,0.317999,0.307708,0.210970,0.005146,0.037048,0.004116,0.002058,0.238757,0.084388,0.210970,0.160543,0.914891,0.003087,0.016466,0.001029,0.041165,0.011320,0.217145,0.013379,0.003087,0.003087,0.001029,0.010291,0.009262,0.027786,0.004116,0.078213,0.185242,0.090563,0.028815,0.005146,0.004116,0.005146,0.097767,0.030874,0.005146,0.060718,0.002058,0.167747,0.019553,0.059689,0.039107,0.033961,0.004116,0.086446,0.016466,0.003087,0.002058,0.01132,0.003087,0.009262,0.016466,0.026757,0.390038,0.016466,0.006175,0.002058,0.001029,0.065864,0.019553,0.001029,0.005146,0.032932,0.025728,0.001029,0.008233,0.003087,0.002058,0.002058,0.001029,0.011320,0.006175,0.164660,0.010291,0.001029,0.014408,0.007204,0.002058,0.000000,0.019553,0.001029,0.005146,0.013379,0.001029,0.014408,0.001029,0.155398,0.125553,0.028815,8.256664,0.351960,2.363898,0.124524,0.009262,0.694659,0.205825,0.402388,0.350931,0.330349,3.677061,0.032932,0.165689,0.002058,0.02367,0.010291,0.006175,0.025728,0.943707,1.141299,0.269631,3.894206,4.579603,0.060718,0.002058,0.007204,0.010291,0.145107,0.057631,0.059689,0.008233,0.087476,0.309766,0.221262,0.053514,0.024699,0.201708,0.044252,0.003087,0.027786,0.039107,0.001029,0.009262,0.004116,0.207883,0.013379,0.079243,0.037048,0.021612,0.290213,0.100854,0.002058,0.021612,0.017495,0.001029,0.005146,0.072039,0.130699,0.001029,0.003087,0.005146,0.056602,0.001029,0.016466,0.028815,0.002058,0.005146,0.055573,0.002058,0.001029,0.001029,0.570135,0.017495,0.000000,0.055573,0.575280,0.171864,0.691571,0.013379,0.004116,2.612946,0.003087,0.004116,0.013379,0.005146,0.084388,0.005146,0.005146,0.374601,0.038078,0.013379,0.154369,0.013379,0.041165,0.851086,0.032932,0.012349,0.010291,0.004116,0.001029,0.003087,0.006175,0.003087,0.003087,0.023670,0.618504,0.049398,0.028815,0.022641,0.003087,0.289184,0.271689,0.028815,0.001029,0.014408,0.000000,0.001029,0.004116,0.004116,0.015437,0.138932,0.028815,0.015437,0.012349,0.110116,0.306679,0.192446,0.127611,0.003087,0.005146,0.02367,0.059689,0.109087,0.001029,0.013379,0.315941,0.050427,0.050427,0.136874,0.044252,0.046311,0.15334,0.253165,0.009262,0.009262,0.099825,0.012349,0.091592,0.934445,2.009880,0.015437,0.022641,0.045281,0.139961,0.066893,0.337553,0.009262,0.050427,0.087476,0.002058,0.013379,1.941957,0.079243,0.020582,0.001029,0.001029,0.004116,0.006175,0.010291,0.013379,0.008233,0.016466,0.031903,0.027786,0.023670,0.030874,0.005146,0.025728,0.013379,0.001029,0.005146,0.002058,0.050427,0.030874,0.017495,0.002058,0.032932,0.002058,0.006175,0.018524,0.012349,0.103942,0.008233,0.007204,0.004116,0.013379,0.003087,0.010291,0.001029,0.007204,0.027786,0.001029,0.006175,0.004116,0.014408,0.014408,0.005146,0.001029,0.002058,0.001029,0.000000,0.012349,0.075126,0.882989,0.001029,0.003087,0.01132,0.002058,0.014408,0.015437,0.01132,0.008233,0.021612,0.001029,0.010291,0.002058,0.283009,0.006175,0.002058,0.003087,0.007204,0.008233,0.002058,1.370793,0.007204,0.016466,0.108058,0.024699,0.007204,0.014408,0.084388,0.218174,0.075126,0.007204,0.009262,0.091592,0.003087,0.051456,0.122466,0.030874,0.148194,0.013379,0.032932,0.030874,0.106000,0.148194,0.180097,0.121437,0.001029,0.197592,0.002058,0.002058,0.021612,0.020582,0.021612,0.009262,0.005146,0.001029,0.015437,0.008233,0.009262,0.001029,0.001029,0.005146,0.005146,0.015437,0.001029,0.001029,0.006175,0.001029,0.006175,0.003087,0.003087,1.341978,0.132757,0.121437,0.05866,0.234640,0.387980,0.597921,0.357106,0.345786,0.295359,0.04734,0.190388,0.013379,0.014408,0.008233,0.112175,0.002058,0.013379,0.002058,0.313883,0.185242,0.002058,0.004116,0.020582,0.026757,0.036019,0.019553,0.006175,0.001029,0.032932,0.019553,0.002058,0.005146,0.003087,0.018524,0.006175,0.002058,0.010291,0.019553,0.007204,0.004116,0.004116,0.001029,0.009262,0.001029,0.001029,0.013379,0.001029,0.001029,0.003087,0.009262,0.005146,0.002058,0.003087,0.003087,0.003087,0.001029,0.002058,0.006175,0.008233,0.003087,0.001029,0.002058,0.004116,0.003087,0.009262,0.002058,0.002058,0.001029,0.001029,0.037048,0.001029,0.001029,0.001029,0.001029,0.002058,0.001029,0.006175,0.006175,0.010291,0.001029,0.001029,0.005146,0.009262,0.001029,0.005146,0.014408,0.004116,0.009262,0.004116,0.006175,0.004116,0.002058,0.003087,0.005146,0.004116,0.01132,0.006175,0.002058,0.002058,0.024699,0.004116,0.016466,0.017495,0.040136,0.002058,0.001029,0.003087,0.006175,0.001029,0.021612,0.001029,0.002058,0.001029,0.008233,0.002058,0.001029,0.001029,0.002058,0.001029,0.002058,0.009262,0.022641,0.008233,0.007204,0.003087,0.002058,0.009262,0.001029,0.001029,0.001029,0.001029,0.001029,0.002058,0.007204,0.001029,0.305650,0.276834,0.298446,0.314912,0.026757,0.017495,0.002058,0.001029,0.009262,0.002058,0.004116,0.008233,0.001029,0.001029,0.001029,0.001029,0.196563,0.005146,0.002058,0.001029,0.001029,0.002058,0.004116,0.001029,0.001029,0.000000,0.002058,0.001029,0.113204,0.048369,0.024699,0.008233,0.001029,0.001029,0.024699,0.108058,0.001029,0.006175,0.125553,0.001029,0.001029,0.001029,0.002058,0.001029,0.003087,0.005146,0.001029,0.001029,0.003087,0.003087,0.001029,0.003087,0.001029,0.001029,0.006175,0.009262,0.007204,0.014408,0.011320,0.072039,0.015437,0.019553,0.026757,0.006175,0.006175,0.005146,0.017495,0.004116,0.049398,0.003087,0.018524,0.001029,0.002058,0.037048,0.001029,0.017495,0.001029,0.003087,0.001029,0.001029,0.003087,0.001029,0.001029,0.004116,0.005146,0.002058,0.001029,0.019553,0.080272,0.239786,0.002058,0.208912,0.005146,0.012349,0.342698,0.007204,0.022641,0.015437,0.001029,0.004116,0.002058,0.036019,0.245961,0.198621,0.027786,1.420191,0.061747,0.053514,0.007204,0.050427,0.008233,0.007204,0.502213,0.004116,0.005146,0.027786,0.013379,0.045281,0.024699,0.018524,0.002058,0.008233,0.097767,0.003087
True,0.000000,0.000000,0.000000,0.126064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.094548,0.000000,0.094548,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.031516,0.063032,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.189095,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.031516,0.000000,0.000000,0.031516,0.031516,0.000000,0.000000,0.000000,0.126064,0.504255,0.378191,0.031516,0.000000,0.031516,0.220611,0.031516,0.094548,0.000000,0.000000,0.126064,0.000000,0.000000,0.000000,0.000000,0.126064,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.063032,0.000000,0.000000,0.031516,0.031516,0.000000,0.535771,0.000000,0.000000,9.265679,0.567286,0.189095,0.000000,0.000000,0.063032,0.031516,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.346675,0.094548,0.031516,0.031516,0.063032,0.094548,0.031516,0.063032,0.913962,0.031516,0.157580,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.031516,0.000000,0.094548,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,2.584305,0.000000,0.094548,0.000000,2.994012,0.000000,0.283643,0.000000,0.378191,0.000000,0.000000,0.000000,0.094548,1.890955,0.094548,0.409707,0.063032,0.031516,0.031516,0.000000,0.031516,0.126064,0.189095,0.189095,0.283643,0.031516,0.063032,0.000000,0.000000,0.283643,0.220611,0.063032,0.094548,1.103057,0.063032,0.000000,0.000000,0.157580,0.031516,0.189095,0.031516,0.031516,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.126064,0.157580,0.000000,0.094548,0.000000,0.000000,0.000000,0.063032,0.094548,0.031516,0.031516,0.000000,0.031516,0.000000,0.031516,0.031516,0.031516,0.000000,0.094548,0.000000,0.031516,0.000000,0.00000,0.000000,0.000000,0.063032,0.000000,0.472739,0.031516,0.031516,0.000000,0.000000,0.063032,0.000000,0.000000,0.031516,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.031516,0.000000,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.031516,0.000000,0.000000,0.000000,0.000000,0.094548,0.000000,2.458241,0.882446,0.000000,8.383234,1.040025,1.890955,0.094548,0.000000,1.638828,0.283643,0.252127,0.157580,0.252127,2.867948,0.031516,0.283643,0.031516,0.00000,0.000000,0.000000,0.000000,4.601324,0.850930,0.315159,5.389222,4.002521,0.220611,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.063032,0.535771,0.189095,0.063032,0.000000,0.283643,0.031516,0.000000,0.031516,0.031516,0.000000,0.000000,0.000000,0.283643,0.000000,0.126064,0.063032,0.031516,0.094548,0.189095,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.157580,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.126064,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.441223,0.000000,0.031516,0.063032,0.472739,0.063032,0.693350,0.031516,0.000000,2.080050,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.504255,0.000000,0.000000,0.157580,0.000000,0.063032,0.850930,0.031516,0.031516,0.063032,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.063032,0.756382,0.063032,0.000000,0.031516,0.000000,0.126064,0.094548,0.094548,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.189095,0.031516,0.031516,0.031516,0.031516,0.252127,0.063032,0.094548,0.031516,0.000000,0.00000,0.126064,0.031516,0.000000,0.000000,0.094548,0.063032,0.094548,0.094548,0.000000,0.000000,0.00000,0.126064,0.000000,0.000000,0.000000,0.000000,0.094548,1.733375,1.229121,0.000000,0.126064,0.094548,0.126064,0.000000,0.346675,0.000000,0.063032,0.094548,0.000000,0.031516,1.701859,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.031516,0.063032,0.000000,0.031516,0.126064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.189095,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.063032,0.913962,0.000000,0.000000,0.00000,0.000000,0.031516,0.031516,0.00000,0.031516,0.063032,0.000000,0.000000,0.000000,0.189095,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.882446,0.000000,0.000000,0.126064,0.031516,0.000000,0.000000,0.031516,0.063032,0.126064,0.000000,0.000000,0.220611,0.000000,0.094548,0.063032,0.031516,0.126064,0.094548,0.063032,0.031516,0.126064,0.094548,0.346675,0.252127,0.000000,0.283643,0.000000,0.000000,0.031516,0.000000,0.063032,0.000000,0.000000,0.000000,0.126064,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.945477,0.126064,0.031516,0.00000,0.252127,0.346675,0.094548,0.346675,0.535771,0.094548,0.00000,0.283643,0.031516,0.063032,0.000000,0.031516,0.000000,0.000000,0.000000,0.220611,0.315159,0.000000,0.000000,0.000000,0.031516,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.378191,0.252127,0.315159,0.000000,0.126064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.882446,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.157580,0.000000,1.701859,0.378191,0.063032,0.031516,0.000000,0.000000,0.000000,0.378191,0.000000,0.000000,0.283643,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031516,0.031516,0.000000,0.000000,0.031516,0.031516,0.031516,0.000000,0.031516,0.031516,0.031516,0.031516,0.094548,0.126064,0.031516,0.000000,0.031516,0.094548,0.031516,0.126064,0.000000,0.063032,0.000000,0.000000,0.063032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.252127,0.189095,0.000000,0.031516,0.000000,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063032,0.126064,0.567286,0.000000,0.283643,0.000000,0.063032,0.000000,0.283643,0.000000,0.000000,0.409707,0.000000,0.000000,0.063032,0.000000,0.031516,0.000000,0.000000,0.000000,0.000000,0.031516,0.000000

--- number_diagnoses ---

              count      mean       std  min  25%  50%  75%   max
has_weight
False       98569.0  7.404661  1.942753  1.0  6.0  8.0  9.0  16.0
True         3197.0  7.975915  1.526276  1.0  7.0  9.0  9.0   9.0

max_glu_serum       >200       >300       Norm
has_weight
False          27.777778  23.643846  48.578376

A1Cresult          >7         >8       Norm
has_weight
False       22.336852  48.218570  29.444578
True        25.433526  51.156069  23.410405

metformin       Down         No     Steady        Up
has_weight
False       0.561028  80.427924  17.980298  1.030750
True        0.688145  78.229590  19.487019  1.595246

repaglinide      Down         No    Steady        Up
has_weight
False        0.045653  98.478223  1.368584  0.107539
True         0.000000  98.780106  1.094776  0.125117

nateglinide     Down         No    Steady        Up
has_weight
False        0.01116  99.322302  0.645233  0.021305
True         0.00000  98.905224  1.000938  0.093838

chlorpropamide      Down         No    Steady        Up
has_weight
False           0.001015  99.914781  0.078118  0.006087
True            0.000000  99.937441  0.062559  0.000000

glimepiride      Down         No    Steady        Up
has_weight
False        0.189715  94.926397  4.569388  0.314501
True         0.218955  94.056928  5.192368  0.531749

acetohexamide          No    Steady
has_weight
False           99.998985  0.001015
True           100.000000  0.000000

glipizide       Down         No     Steady        Up
has_weight
False       0.542767  87.634043  11.094766  0.728424
True        0.781983  84.454176  13.137316  1.626525

glyburide       Down         No     Steady        Up
has_weight
False       0.547840  89.597135   9.068774  0.786251
True        0.750704  87.613388  10.478574  1.157335

tolbutamide         No    Steady
has_weight
False        99.977681  0.022319
True         99.968721  0.031279

pioglitazone      Down         No    Steady        Up
has_weight
False         0.114641  92.885187  6.775964  0.224208
True          0.156397  90.147013  9.289959  0.406631

rosiglitazone      Down         No    Steady        Up
has_weight
False          0.085219  93.753614  5.988698  0.172468
True           0.093838  93.493901  6.162027  0.250235

acarbose        Down         No    Steady        Up
has_weight
False       0.003044  99.704775  0.283050  0.009131
True        0.000000  99.468251  0.500469  0.031279

miglitol        Down          No   Steady        Up
has_weight
False       0.005073   99.961448  0.03145  0.002029
True        0.000000  100.000000  0.00000  0.000000

troglitazone          No    Steady
has_weight
False          99.996956  0.003044
True          100.000000  0.000000

tolazamide         No    Steady        Up
has_weight
False       99.961448  0.037537  0.001015
True        99.968721  0.031279  0.000000

examide        No
has_weight
False       100.0
True        100.0

citoglipton     No
has_weight
False        100.0
True         100.0

insulin          Down         No     Steady         Up
has_weight
False       12.300013  45.749678  30.584667  11.365642
True         2.940256  71.567094  21.958086   3.534564

glyburide-metformin      Down         No    Steady        Up
has_weight
False                0.006087   99.28375  0.702046  0.008116
True                 0.000000  100.00000  0.000000  0.000000

glipizide-metformin          No    Steady
has_weight
False                 99.986811  0.013189
True                 100.000000  0.000000

glimepiride-pioglitazone          No    Steady
has_weight
False                      99.998985  0.001015
True                      100.000000  0.000000

metformin-rosiglitazone          No    Steady
has_weight
False                     99.997971  0.002029
True                     100.000000  0.000000

metformin-pioglitazone          No    Steady
has_weight
False                    99.998985  0.001015
True                    100.000000  0.000000

change             Ch         No
has_weight
False       46.612018  53.387982
True        33.343760  66.656240

diabetesMed         No        Yes
has_weight
False        22.732299  77.267701
True         31.154207  68.845793

readmitted        <30        >30         NO
has_weight
False       11.159695  34.529112  54.311193
True        11.166719  47.231780  41.601501

has_weight
False    98569
True      3197
Name: count, dtype: int64

Analizom atributa „weight“ uoceno je da nedostajanje vrednosti varira u odnosu na pojedine kategorije drugih atributa, pri cemu je izrazenije kod pacijenata rase African American, bez insulinske terapije, bez promene terapije, kao i kod pacijenata koji nisu ponovo hospitalizovani. Medjutim, uoceni obrasci nisu dovoljno konzistentni za donosenje pouzdanih zakljucaka o povezanosti nedostajanja sa ovim karakteristikama. Posebno je uocena veca ucestalost nedostajanja kod pacijenata koji nisu ponovo hospitalizovani, sto nije intuitivan obrazac ukoliko se ocekuje veca dostupnost podataka kod pacijenata sa ponovnim kontaktom sa zdravstvenim sistemom. Zbog toga se visok procenat nedostajucih vrednosti pre pripisuje nacinu prikupljanja podataka u periodu 1999–2008. godine, kada zdravstvene ustanove nisu bile obavezne da telesnu tezinu evidentiraju u strukturisanom elektronskom obliku. Na osnovu navedenog, atribut „weight“ je uklonjen iz dalje analize.

In [12]:
data = data.drop(["weight","has_weight"], axis= 1)

In [13]:
data["has_max_glu_serum"]= data["max_glu_serum"].notna()
data["has_max_glu_serum"]= data["has_max_glu_serum"].astype("object")

In [14]:
compare_column_with_all_columns("has_max_glu_serum")

--- encounter_id ---

,count,mean,std,min,25%,50%,75%,max
has_max_glu_serum,,,,,,,,
False,96420.0,1.690902e+08,1.028127e+08,12522.0,89035549.5,155899620.0,234767727.0,443867222.0
True,5346.0,9.506861e+07,6.859692e+07,2265486.0,55859011.5,82505202.0,104741811.0,439020524.0

--- patient_nbr ---

,count,mean,std,min,25%,50%,75%,max
has_max_glu_serum,,,,,,,,
False,96420.0,5.522301e+07,3.905976e+07,135.0,23273201.25,49196052.0,88476435.0,189502619.0
True,5346.0,3.823136e+07,2.672763e+07,209394.0,23637393.00,24455736.0,29903877.0,174774587.0

race               AfricanAmerican     Asian  Caucasian  Hispanic     Other
has_max_glu_serum
False                    19.905948  0.652845  75.951934  1.964906  1.524368
True                      8.657845  0.491493  86.011342  3.516068  1.323251

gender                Female       Male  Unknown/Invalid
has_max_glu_serum
False              53.732628  46.264261         0.003111
True               54.227460  45.772540         0.000000

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
has_max_glu_serum,,,,,,,,,,
False,0.166978,0.701099,1.647998,3.733665,9.530180,17.151006,22.324207,25.420037,16.643850,2.680979
True,0.000000,0.280584,1.271979,3.273475,9.277965,13.449308,17.919940,29.143285,21.492705,3.890759

--- admission_type_id ---

                     count      mean       std  min  25%  50%  75%  max
has_max_glu_serum
False              96420.0  1.886134  1.295472  1.0  1.0  1.0  3.0  8.0
True                5346.0  4.510662  1.724847  1.0  5.0  5.0  6.0  6.0

--- discharge_disposition_id ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  3.660185  5.215376  1.0  1.0  1.0  3.0  28.0
True                5346.0  4.715862  6.252669  1.0  1.0  3.0  6.0  28.0

--- admission_source_id ---

                     count       mean       std  min  25%   50%   75%   max
has_max_glu_serum
False              96420.0   5.297055  3.471441  1.0  1.0   7.0   7.0  25.0
True                5346.0  14.003741  5.024168  1.0  7.0  17.0  17.0  17.0

--- time_in_hospital ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  4.388892  2.986389  1.0  2.0  4.0  6.0  14.0
True                5346.0  4.523943  2.959263  1.0  2.0  4.0  6.0  14.0

payer_code,BC,CH,CM,CP,DM,FR,HM,MC,MD,MP,OG,OT,PO,SI,SP,UN,WC
has_max_glu_serum,,,,,,,,,,,,,,,,,
False,7.673334,0.238271,3.233438,4.166387,0.899389,0.001678,9.923485,52.302168,5.815827,0.132559,1.733338,0.159407,0.993355,0.067119,8.368011,4.069065,0.223169
True,4.284222,0.208986,0.522466,2.612330,0.679206,0.000000,18.808777,66.300940,3.448276,0.000000,0.000000,0.000000,0.000000,0.783699,1.044932,1.201672,0.104493

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,Oncology,Ophthalmology,Orthopedics,Orthopedics-Reconstructive,Osteopath,Otolaryngology,OutreachServices,Pathology,Pediatrics,Pediatrics-AllergyandImmunology,Pediatrics-CriticalCare,Pediatrics-EmergencyMedicine,Pediatrics-Endocrinology,Pediatrics-Hematology-Oncology,Pediatrics-InfectiousDiseases,Pediatrics-Neurology,Pediatrics-Pulmonology,Perinatology,PhysicalMedicineandRehabilitation,PhysicianNotFound,Podiatry,Proctology,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.014317,0.024543,0.03886,10.486164,0.014317,0.012272,0.006136,0.002045,15.468472,0.245434,0.016362,13.200254,1.086045,0.118626,0.167713,0.177940,0.116581,0.071585,28.314892,3.072014,0.413147,0.002045,0.051132,0.03886,1.347841,0.711758,0.073630,2.853169,2.186407,0.079766,0.247479,0.024543,0.03477,0.519502,0.006136,0.17794,0.006136,0.3252,0.008181,0.002045,0.020453,0.051132,0.002045,0.799705,0.022498,0.204528,0.002045,1.552369,0.002045,0.014317,0.206574,1.775305,2.327532,0.1084,0.004091,0.03477,0.002045,0.002045,0.092038,0.200438,1.333524,0.022498,5.669523,0.018408,0.957192,0.016362,0.081811,0.002045,0.222936,1.090136,0.067494,1.329434
True,0.000000,0.000000,0.00000,7.694938,0.000000,0.000000,0.034200,0.000000,0.068399,0.000000,0.000000,33.720930,1.128591,0.000000,0.000000,4.103967,0.000000,0.068399,27.051984,3.796170,0.034200,0.000000,0.000000,0.00000,0.410397,0.000000,0.068399,0.170999,5.608755,0.000000,0.136799,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.248974,0.000000,0.000000,0.000000,0.102599,0.068399,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.183311,0.068399,0.000000,0.000000,0.034200,0.000000,0.000000,0.000000,0.000000,1.196990

--- num_lab_procedures ---

                     count       mean        std  min   25%   50%   75%    max
has_max_glu_serum
False              96420.0  43.857125  19.428744  1.0  33.0  45.0  57.0  132.0
True                5346.0  29.361579  19.007586  1.0  17.0  23.0  37.0  114.0

--- num_procedures ---

                     count      mean       std  min  25%  50%  75%  max
has_max_glu_serum
False              96420.0  1.371178  1.726202  0.0  0.0  1.0  2.0  6.0
True                5346.0  0.772540  1.143690  0.0  0.0  0.0  1.0  6.0

--- num_medications ---

                     count       mean       std  min   25%   50%   75%   max
has_max_glu_serum
False              96420.0  16.057374  8.192361  1.0  10.0  15.0  20.0  81.0
True                5346.0  15.381033  6.823539  1.0  10.0  15.0  20.0  45.0

--- number_outpatient ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  0.353215  1.258644  0.0  0.0  0.0  0.0  42.0
True                5346.0  0.660494  1.381882  0.0  0.0  0.0  1.0  35.0

--- number_emergency ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  0.191216  0.930807  0.0  0.0  0.0  0.0  76.0
True                5346.0  0.317247  0.916326  0.0  0.0  0.0  0.0  25.0

--- number_inpatient ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  0.628863  1.251531  0.0  0.0  0.0  1.0  21.0
True                5346.0  0.756453  1.446967  0.0  0.0  0.0  1.0  19.0

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,170,171,172,173,174,175,179,180,182,183,184,185,187,188,189,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,207,208,210,211,212,214,215,216,217,218,219,220,223,225,226,227,228,229,23,230,233,235,236,237,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,261,262,263,266,27,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,31,310,311,312,314,318,320,322,323,324,325,327,331,332,333,334,335,336,337,338,34,340,341,342,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,36,360,361,362,363,365,366,368,369,370,372,373,374,375,376,377,378,379,38,380,381,382,383,384,385,386,388,389,39,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,461,462,463,464,465,466,47,470,471,473,474,475,477,478,48,480,481,482,483,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,518,519,52,521,522,523,524,526,527,528,529,53,530,531,532,533,534,535,536,537,54,540,541,542,543,550,551,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,58,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,61,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,632,633,634,637,640,641,642,643,644,645,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,671,674,680,681,682,683,684,685,686,690,691,692,693,694,695,696,698,7,70,700,703,704,705,706,707,708,709,710,711,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,745,746,747,75,751,753,756,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,803,804,805,806,807,808,810,812,813,814,815,816,817,82,820,821,822,823,824,825,826,827,831,832,833,834,835,836,837,838,839,84,840,842,843,844,845,846,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,873,875,878,879,88,880,881,882,883,885,886,890,891,892,893,895,897,9,903,904,906,911,913,914,915,916,917,919,920,921,922,923,924,928,933,934,935,936,939,94,941,942,944,945,952,955,957,958,959,962,963,964,965,966,967,968,969,97,970,971,972,973,974,975,976,977,98,980,982,983,986,987,988,989,990,991,992,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.001037,0.010373,0.002075,0.070539,0.001037,0.002075,0.009336,0.002075,0.001037,0.025934,0.004149,0.005187,0.004149,0.001037,0.001037,0.004149,0.002075,0.001037,0.002075,0.026971,0.060166,0.01556,0.304979,0.091286,0.053942,0.016598,0.108921,0.012448,0.001037,0.011411,0.425311,0.009336,0.003112,0.002075,0.011411,0.003112,0.003112,0.147303,0.005187,0.003112,0.006224,0.107884,0.030083,0.010373,0.175311,0.002075,0.109959,0.123444,0.04668,0.003112,0.029046,0.002075,0.008299,0.024896,0.317427,0.237552,0.014523,0.015560,0.010373,0.100622,0.034232,0.022822,0.025934,0.001037,0.005187,0.006224,0.099585,0.008299,0.006224,0.004149,0.001037,0.001037,0.129668,0.001037,0.045643,0.007261,0.047718,0.018672,0.045643,0.005187,0.002075,0.002075,0.009336,0.030083,0.026971,0.003112,0.007261,0.060166,0.034232,0.003112,0.058091,0.022822,0.011411,0.004149,0.002075,0.231328,0.062241,0.670124,0.202282,0.293568,0.603734,0.413900,0.847510,0.100622,0.009336,0.147303,0.028008,0.019710,0.014523,0.017635,0.01971,0.269710,0.091286,0.091286,0.024896,0.008299,0.001037,0.004149,0.003112,1.170124,0.874481,1.615145,0.165975,0.410788,0.082988,0.007261,0.004149,0.052905,0.017635,0.012448,0.023859,0.049793,0.024896,0.004149,0.003112,0.012448,0.002075,0.002075,0.003112,0.006224,0.006224,0.096473,0.051867,1.819502,0.03527,0.352697,0.002075,0.320539,0.017635,0.069502,0.025934,0.062241,0.364108,0.038382,0.085062,0.090249,0.017635,0.087137,0.087137,0.100622,0.052905,0.114108,0.425311,0.879668,0.010373,0.062241,0.001037,0.013485,0.087137,0.004149,0.067427,0.033195,0.024896,0.010373,0.024896,0.003112,0.034232,0.003112,0.011411,0.057054,0.018672,0.001037,0.000000,0.007261,0.002075,0.010373,0.006224,0.001037,0.022822,0.191909,0.052905,0.031120,0.002075,0.007261,0.003112,0.010373,0.020747,0.007261,0.043568,0.007261,0.008299,0.006224,0.113071,0.082988,0.001037,0.150415,0.036307,0.010373,0.011411,0.030083,0.002075,0.006224,0.009336,0.017635,0.004149,0.020747,0.014523,0.008299,0.002075,0.002075,0.005187,0.008299,0.001037,0.001037,0.001037,0.012448,0.002075,0.003112,0.001037,0.001037,0.003112,0.001037,0.010373,0.003112,0.013485,0.005187,1.621369,0.020747,0.001037,0.004149,0.009336,0.002075,0.002075,0.142116,0.005187,0.001037,0.002075,0.001037,0.011411,0.005187,0.03112,0.005187,0.131743,0.344398,0.455394,0.521784,0.264523,0.003112,0.007261,3.582988,0.238589,0.001037,0.107884,6.654564,0.432573,0.070539,0.002075,0.045643,0.062241,0.041494,0.002075,0.071577,0.185685,0.089212,0.271784,2.731328,6.724066,0.034232,0.032158,0.173237,0.094398,0.791494,1.994813,0.997925,0.159751,0.090249,0.086100,0.849585,0.131743,0.034232,0.104772,0.149378,0.005187,0.020747,0.061203,0.002075,0.035270,0.005187,0.542531,0.006224,0.093361,0.022822,0.012448,0.420124,0.098548,0.020747,0.011411,0.005187,0.008299,0.048755,0.237552,0.025934,0.004149,0.001037,0.022822,0.003112,0.014523,0.001037,0.032158,0.002075,0.017635,0.062241,0.339212,0.005187,0.041494,3.334025,0.098548,0.005187,0.089212,2.157676,0.033195,1.040456,0.022822,0.005187,0.082988,0.009336,0.002075,0.003112,0.003112,0.518672,0.003112,0.034232,0.264523,0.038382,0.016598,0.044606,0.122407,0.030083,1.062241,0.045643,0.002075,0.010373,0.025934,0.001037,0.003112,0.007261,0.025934,0.019710,0.004149,0.051867,0.511411,0.267635,0.205394,0.022822,0.024896,0.439834,0.143154,0.110996,0.010373,0.189834,0.009336,0.001037,0.001037,0.051867,0.007261,0.223029,0.136929,0.050830,0.044606,0.187759,0.328838,0.841286,0.955394,0.146266,0.011411,0.081950,0.051867,0.031120,0.275934,0.001037,0.006224,0.272822,0.225104,0.039419,0.936722,0.211618,0.092324,1.016598,0.648340,0.007261,0.002075,0.002075,0.018672,0.002075,0.005187,1.490664,0.077801,0.019710,0.009336,0.335062,0.01971,0.341286,0.100622,0.014523,0.096473,0.047718,0.005187,1.577801,0.206432,0.015560,0.003112,0.003112,0.037344,0.001037,0.021784,0.068465,0.001037,0.002075,0.03527,0.020747,0.002075,0.024896,0.01971,0.165975,0.005187,0.048755,0.021784,0.005187,0.004149,0.06639,0.080913,0.017635,0.003112,0.004149,0.002075,0.001037,0.001037,0.009336,0.06639,0.005187,0.028008,0.002075,0.009336,0.005187,0.295643,0.001037,0.013485,0.002075,0.095436,0.005187,0.020747,0.002075,0.026971,0.033195,0.006224,0.012448,0.025934,0.007261,0.020747,0.003112,0.003112,0.001037,0.004149,0.013485,0.114108,1.960581,0.002075,0.001037,0.006224,0.008299,0.001037,0.001037,0.005187,0.021784,0.006224,0.012448,0.005187,0.001037,0.002075,0.044606,0.001037,0.002075,0.001037,0.009336,0.003112,0.254149,0.008299,0.008299,0.024896,0.065353,0.039419,2.153527,0.056017,0.007261,0.017635,0.053942,0.004149,0.184647,0.776971,0.077801,0.434647,0.012448,0.090249,0.048755,0.124481,0.109959,0.236515,0.004149,0.002075,0.355809,0.004149,0.002075,0.014523,0.008299,0.052905,0.007261,0.007261,0.007261,0.002075,0.004149,0.005187,0.01556,0.005187,0.009336,1.976141,0.108921,0.082988,0.029046,0.151452,0.098548,3.954357,0.267635,0.037344,0.566390,0.088174,0.142116,0.001037,0.005187,0.004149,0.025934,0.003112,0.005187,0.003112,0.070539,0.514523,0.006224,0.033195,0.029046,0.003112,0.001037,0.190871,0.006224,0.081950,0.136929,0.010373,0.238589,0.084025,0.005187,0.007261,0.008299,0.001037,0.007261,1.041494,0.146266,0.047718,0.125519,0.308091,0.023859,0.003112,0.000000,0.007261,0.001037,0.001037,0.001037,0.005187,0.006224,0.001037,0.001037,0.001037,0.001037,0.013485,0.001037,0.012448,0.029046,0.010373,0.004149,0.012448,0.002075,0.057054,0.035270,0.113071,0.018672,0.005187,0.038382,0.013485,0.003112,0.004149,0.008299,0.008299,0.006224,0.013485,0.003112,0.001037,0.002075,0.017635,0.002075,0.002075,0.003112,0.005187,0.002075,0.005187,0.010373,0.006224,0.001037,0.004149,0.006224,0.010373,0.011411,0.004149,0.001037,0.002075,0.045643,0.001037,0.002075,0.001037,0.001037,0.002075,0.002075,0.001037,0.003112,0.003112,0.001037,0.022822,0.003112,0.041494,0.004149,0.056017,0.003112,0.013485,0.006224,0.012448,0.003112,0.001037,0.007261,0.002075,0.005187,0.002075,0.011411,0.009336,0.001037,0.001037,0.020747,0.045643,0.056017,0.003112,0.008299,0.051867,0.010373,0.016598,0.008299,0.056017,0.001037,0.008299,0.003112,0.016598,0.002075,0.001037,0.002075,0.001037,0.012448,0.001037,0.002075,0.001037,0.004149,0.003112,0.003112,0.001037,0.010373,0.002075,0.007261,0.008299,0.001037,0.078838,1.973029,0.411826,0.787344,0.025934,0.001037,0.001037,0.001037,0.002075,0.001037,0.005187,0.001037,0.045643,0.045643,0.068465,0.016598,1.181535,0.226141,0.001037,0.008299,0.001037,0.001037,0.001037,0.007261
True,0.000000,0.000000,0.000000,0.093545,0.000000,0.000000,0.000000,0.000000,0.000000,0.037418,0.018709,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.074836,0.00000,0.318054,0.112254,0.037418,0.037418,0.168382,0.000000,0.000000,0.018709,0.280636,0.000000,0.000000,0.000000,0.018709,0.018709,0.000000,0.093545,0.000000,0.018709,0.000000,0.074836,0.037418,0.000000,0.074836,0.000000,0.112254,0.130964,0.00000,0.018709,0.000000,0.000000,0.018709,0.018709,0.261927,0.243218,0.000000,0.018709,0.000000,0.130964,0.037418,0.018709,0.037418,0.000000,0.000000,0.018709,0.130964,0.000000,0.000000,0.018709,0.000000,0.000000,0.037418,0.000000,0.037418,0.000000,0.000000,0.018709,0.037418,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.074836,0.000000,0.000000,0.037418,0.000000,0.000000,0.000000,0.000000,0.224509,0.018709,0.542563,0.112254,0.561272,0.804490,0.336763,0.636109,0.318054,0.056127,0.261927,0.037418,0.018709,0.018709,0.000000,0.00000,0.130964,0.056127,0.037418,0.018709,0.000000,0.000000,0.000000,0.018709,1.028999,0.523854,2.301216,0.486436,0.299345,0.280636,0.000000,0.000000,0.018709,0.000000,0.056127,0.000000,0.037418,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.056127,0.056127,2.525725,0.00000,0.729654,0.000000,0.187091,0.056127,0.018709,0.056127,0.018709,0.261927,0.149673,0.074836,0.093545,0.037418,0.037418,0.130964,0.187091,0.093545,0.112254,0.692236,0.898036,0.074836,0.074836,0.000000,0.000000,0.112254,0.000000,0.074836,0.000000,0.018709,0.000000,0.018709,0.000000,0.074836,0.000000,0.018709,0.037418,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.037418,0.130964,0.074836,0.093545,0.000000,0.037418,0.000000,0.000000,0.000000,0.000000,0.056127,0.000000,0.000000,0.000000,0.074836,0.037418,0.000000,0.130964,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037418,0.000000,0.018709,0.000000,2.338634,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.149673,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.018709,0.261927,0.187091,0.187091,0.130964,0.000000,0.018709,2.993452,0.449018,0.000000,0.243218,3.105706,0.598690,0.000000,0.000000,0.018709,0.074836,0.018709,0.000000,0.056127,0.074836,0.000000,0.486436,2.488307,7.109448,0.074836,0.018709,0.093545,0.018709,0.486436,1.964453,1.010290,0.392891,0.056127,0.037418,0.392891,0.037418,0.018709,0.168382,0.224509,0.037418,0.056127,0.074836,0.000000,0.112254,0.000000,0.430309,0.056127,0.074836,0.037418,0.000000,0.392891,0.037418,0.000000,0.000000,0.000000,0.037418,0.018709,0.130964,0.018709,0.000000,0.000000,0.018709,0.018709,0.000000,0.000000,0.018709,0.000000,0.018709,0.187091,0.224509,0.000000,0.037418,5.500468,0.130964,0.000000,0.074836,3.648269,0.000000,0.991581,0.037418,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.057998,0.037418,0.000000,0.280636,0.168382,0.000000,0.000000,0.149673,0.093545,1.702526,0.037418,0.000000,0.018709,0.018709,0.000000,0.018709,0.000000,0.018709,0.018709,0.000000,0.093545,0.710945,0.336763,0.392891,0.000000,0.000000,0.486436,0.224509,0.074836,0.037418,0.280636,0.000000,0.018709,0.000000,0.056127,0.018709,0.355472,0.168382,0.056127,0.056127,0.280636,0.336763,1.216090,1.272217,0.112254,0.018709,0.112254,0.130964,0.037418,0.374181,0.000000,0.000000,0.261927,0.411600,0.056127,1.159963,0.205800,0.149673,1.440599,0.710945,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,1.552853,0.000000,0.037418,0.000000,0.224509,0.00000,0.392891,0.074836,0.000000,0.037418,0.037418,0.000000,1.384471,0.149673,0.018709,0.000000,0.000000,0.018709,0.000000,0.000000,0.037418,0.000000,0.000000,0.00000,0.018709,0.000000,0.000000,0.00000,0.018709,0.000000,0.000000,0.018709,0.000000,0.000000,0.00000,0.018709,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.037418,2.843779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037418,0.000000,0.000000,0.018709,0.000000,0.000000,0.056127,0.000000,0.000000,0.000000,0.018709,0.000000,0.224509,0.000000,0.000000,0.018709,0.056127,0.037418,1.403181,0.018709,0.000000,0.000000,0.056127,0.000000,0.000000,0.411600,0.037418,0.392891,0.000000,0.074836,0.018709,0.130964,0.000000,0.037418,0.000000,0.000000,0.449018,0.000000,0.000000,0.000000,0.000000,0.093545,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.00000,0.000000,0.000000,2.132834,0.074836,0.074836,0.018709,0.093545,0.112254,3.816651,0.168382,0.056127,0.280636,0.018709,0.130964,0.000000,0.000000,0.000000,0.018709,0.000000,0.018709,0.000000,0.000000,0.355472,0.000000,0.018709,0.037418,0.000000,0.000000,0.074836,0.000000,0.074836,0.074836,0.000000,0.093545,0.037418,0.000000,0.000000,0.018709,0.000000,0.000000,1.459308,0.074836,0.074836,0.112254,0.355472,0.000000,0.000000,0.018709,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.018709,0.018709,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.018709,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.074836,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.037418,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.018709,0.000000,0.018709,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.000000,0.056127,0.000000,0.000000,0.074836,0.037418,0.018709,0.000000,0.074836,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.000000,0.018709,0.000000,0.000000,0.018709,0.000000,0.037418,1.216090,0.505145,0.467727,0.074836,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018709,0.093545,0.000000,1.272217,0.187091,0.000000,0.000000,0.018709,0.000000,0.000000,0.037418

diag_2,11,110,111,112,114,115,117,123,130,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,162,163,164,171,172,173,174,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,212,214,215,217,218,220,223,225,226,227,228,232,233,235,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,266,268,269,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,31,310,311,312,314,316,317,318,319,320,322,323,324,325,327,331,332,333,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,360,362,364,365,366,368,369,372,373,374,376,377,378,379,38,380,381,382,383,386,388,389,394,395,396,397,398,40,401,402,403,404,405,41,410,411,412,413,414,415,416,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,446,447,448,451,452,453,454,455,456,457,458,459,46,460,461,462,463,464,465,466,470,472,473,474,475,477,478,480,481,482,483,484,485,486,487,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,517,518,519,52,520,521,522,523,524,527,528,529,53,530,531,532,533,534,535,536,537,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,634,641,642,644,645,646,647,648,649,652,654,656,658,659,66,661,663,664,665,670,674,680,681,682,683,684,685,686,691,692,693,694,695,696,698,7,70,701,702,703,704,705,706,707,709,710,711,712,713,714,715,716,717,718,719,721,722,723,724,725,726,727,728,729,730,731,733,734,736,737,738,741,742,745,746,747,748,75,750,751,752,753,754,755,756,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,806,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,832,833,836,837,840,842,843,844,845,846,847,850,851,852,853,860,861,862,863,864,865,866,867,868,869,870,871,872,873,879,88,880,881,882,883,884,891,892,893,894,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,927,933,934,94,942,944,945,947,948,952,953,955,958,959,96,962,963,965,967,968,969,972,974,975,977,980,987,989,99,990,991,992,994,995,996,997,998,999,E812,E813,E814,E816,E817,E818,E819,E821,E826,E829,E849,E850,E853,E854,E858,E868,E870,E878,E879,E880,E881,E882,E883,E884,E885,E887,E888,E890,E900,E905,E906,E915,E916,E917,E918,E919,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E944,E945,E947,E950,E965,E968,E980,V02,V03,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V23,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.003123,0.007287,0.001041,0.196742,0.001041,0.001041,0.01041,0.001041,0.001041,0.003123,0.117629,0.005205,0.001041,0.020819,0.001041,0.002082,0.000000,0.034352,0.021860,0.011451,0.103055,0.046843,0.032270,0.016655,0.075990,0.396606,0.001041,0.001041,0.002082,0.008328,0.001041,0.023942,0.002082,0.001041,0.001041,0.014573,0.026024,0.001041,0.01041,0.046843,0.014573,0.001041,0.004164,0.001041,0.212356,0.403893,0.321657,0.013533,0.019778,0.019778,0.183209,0.089523,0.117629,0.054130,0.008328,0.047884,0.001041,0.008328,0.002082,0.003123,0.043720,0.007287,0.001041,0.005205,0.002082,0.006246,0.001041,0.001041,0.012492,0.001041,0.017696,0.003123,0.002082,0.011451,0.082236,0.155103,0.004164,0.004164,6.020923,1.424036,2.032998,0.213397,0.017696,0.077031,0.095768,0.103055,0.012492,0.004164,0.039557,0.003123,0.002082,0.001041,0.004164,0.005205,0.168636,0.212356,0.103055,0.033311,0.064540,0.067663,0.057253,0.023942,0.884818,0.122833,0.198824,0.077031,0.165513,0.034352,0.007287,0.008328,0.209233,0.022901,0.007287,0.020819,0.037475,0.069744,0.001041,0.003123,0.003123,0.01041,0.016655,0.013533,0.176964,0.007287,0.001041,0.002082,0.003123,0.001041,0.001041,0.420549,0.008328,0.027065,0.035393,6.537240,0.063499,0.273773,0.011451,0.585021,0.017696,0.048925,0.019778,0.163431,1.489616,0.115547,0.299797,0.071826,0.042679,0.047884,0.069744,0.097850,0.078072,0.146776,0.395566,0.166554,0.006246,0.020819,0.008328,0.141571,0.059335,0.001041,0.252954,0.167595,0.692240,0.003123,0.012492,0.003123,0.049966,0.004164,0.005205,0.085359,0.024983,0.012492,0.001041,0.009369,0.002082,0.018737,0.003123,0.007287,0.005205,0.009369,0.001041,0.034352,0.105137,0.043720,0.014573,0.009369,0.006246,0.051007,0.015614,0.01041,0.117629,0.001041,0.230053,0.006246,0.068703,0.044761,0.022901,0.001041,0.136366,0.033311,0.001041,0.001041,0.003123,0.002082,0.001041,0.01041,0.004164,0.013533,0.07599,0.029147,0.013533,0.004164,0.031229,0.001041,0.008328,0.002082,0.020819,0.007287,0.005205,0.003123,0.001041,0.003123,0.002082,0.013533,0.003123,0.443450,0.008328,0.002082,0.012492,0.003123,0.018737,0.001041,0.006246,0.02186,0.003123,0.173841,0.069744,0.040598,0.012492,3.741217,0.342476,2.848072,0.210274,0.003123,0.377869,0.553792,2.558684,0.105137,1.017020,2.660698,0.104096,0.096809,0.087441,0.024983,0.020819,0.004164,0.015614,1.060740,1.424036,0.298756,4.964347,6.547650,0.032270,0.006246,0.016655,0.021860,0.146776,0.190496,0.091605,0.024983,0.068703,0.269609,0.413262,0.039557,0.016655,0.072867,0.109301,0.031229,0.027065,0.003123,0.033311,0.007287,0.337272,0.005205,0.032270,0.072867,0.005205,0.144694,0.049966,0.001041,0.001041,0.009369,0.015614,0.003123,0.002082,0.055171,0.104096,0.002082,0.002082,0.037475,0.002082,0.001041,0.003123,0.029147,0.005205,0.036434,0.103055,0.002082,0.004164,0.009369,1.331390,0.018737,0.053089,1.421954,0.225889,0.868162,0.010410,0.005205,3.264456,0.000000,0.005205,0.004164,0.001041,0.184250,0.003123,0.010410,0.497580,0.046843,0.004164,0.012492,0.154062,0.029147,0.009369,1.328267,0.030188,0.001041,0.001041,0.005205,0.004164,0.001041,0.008328,0.004164,0.007287,0.001041,0.033311,0.288346,0.045802,0.022901,0.008328,0.002082,0.186332,0.192578,0.030188,0.01041,0.010410,0.003123,0.002082,0.015614,0.047884,0.079113,0.022901,0.018737,0.036434,0.104096,0.374746,0.138448,0.081195,0.008328,0.019778,0.093687,0.067663,0.174882,0.014573,0.401811,0.083277,0.046843,0.333108,0.062458,0.081195,0.385156,0.345599,0.009369,0.001041,0.079113,0.016655,1.650965,1.898714,0.01041,0.005205,0.133243,0.230053,0.077031,0.121793,0.007287,0.069744,0.060376,0.005205,3.170770,0.038516,0.021860,0.002082,0.003123,0.006246,0.001041,0.013533,0.01041,0.002082,0.022901,0.020819,0.001041,0.023942,0.020819,0.036434,0.007287,0.029147,0.007287,0.002082,0.005205,0.048925,0.027065,0.012492,0.002082,0.002082,0.028106,0.005205,0.003123,0.007287,0.005205,0.350804,0.002082,0.004164,0.002082,0.003123,0.001041,0.003123,0.001041,0.002082,0.002082,0.004164,0.001041,0.001041,0.001041,0.023942,0.039557,1.428200,0.001041,0.004164,0.006246,0.006246,0.003123,0.004164,0.011451,0.006246,0.002082,0.014573,0.005205,0.001041,0.272732,0.007287,0.001041,0.001041,0.001041,0.007287,0.01041,1.978868,0.008328,0.166554,0.042679,0.006246,0.005205,0.038516,0.122833,0.020819,0.011451,0.011451,0.092646,0.063499,0.143653,0.057253,0.143653,0.004164,0.028106,0.027065,0.13012,0.093687,0.249831,0.077031,0.180086,0.001041,0.018737,0.010410,0.026024,0.006246,0.003123,0.015614,0.016655,0.005205,0.001041,0.002082,0.008328,0.003123,0.001041,0.016655,0.001041,0.002082,0.013533,0.006246,0.006246,0.002082,1.470879,0.116588,0.074949,0.023942,0.188414,0.501744,0.642273,0.209233,0.382033,0.343517,0.029147,0.227971,0.006246,0.010410,0.005205,0.061417,0.002082,0.008328,0.002082,0.314370,0.194660,0.001041,0.004164,0.024983,0.081195,0.004164,0.045802,0.047884,0.004164,0.001041,0.039557,0.023942,0.002082,0.003123,0.011451,0.057253,0.020819,0.004164,0.014573,0.019778,0.008328,0.004164,0.004164,0.001041,0.001041,0.008328,0.003123,0.015614,0.003123,0.001041,0.004164,0.007287,0.001041,0.006246,0.031229,0.005205,0.016655,0.002082,0.020819,0.009369,0.003123,0.001041,0.006246,0.005205,0.002082,0.009369,0.005205,0.002082,0.003123,0.001041,0.001041,0.038516,0.001041,0.001041,0.001041,0.011451,0.007287,0.008328,0.001041,0.006246,0.007287,0.001041,0.001041,0.007287,0.012492,0.002082,0.004164,0.001041,0.005205,0.006246,0.002082,0.000000,0.003123,0.001041,0.002082,0.001041,0.002082,0.003123,0.022901,0.003123,0.008328,0.009369,0.024983,0.001041,0.003123,0.006246,0.027065,0.001041,0.001041,0.003123,0.000000,0.001041,0.002082,0.001041,0.001041,0.014573,0.012492,0.001041,0.000000,0.001041,0.003123,0.002082,0.001041,0.005205,0.003123,0.001041,0.001041,0.001041,0.002082,0.001041,0.004164,0.001041,0.001041,0.003123,0.002082,0.001041,0.102014,0.463228,0.375787,0.574611,0.034352,0.008328,0.001041,0.002082,0.003123,0.000000,0.001041,0.002082,0.002082,0.001041,0.001041,0.056212,0.001041,0.002082,0.001041,0.003123,0.001041,0.003123,0.107219,0.020819,0.012492,0.004164,0.001041,0.001041,0.020819,0.111383,0.003123,0.100973,0.001041,0.001041,0.003123,0.002082,0.000000,0.002082,0.006246,0.000000,0.001041,0.002082,0.005205,0.014573,0.001041,0.008328,0.003123,0.035393,0.005205,0.008328,0.023942,0.007287,0.005205,0.001041,0.011451,0.001041,0.032270,0.011451,0.001041,0.020819,0.007287,0.001041,0.001041,0.000000,0.004164,0.001041,0.007287,0.01041,0.104096,0.002082,0.069744,0.001041,0.003123,0.128038,0.002082,0.009369,0.008328,0.003123,0.001041,0.264404,0.135325,0.010410,0.415344,0.010410,0.040598,0.001041,0.002082,0.080154,0.002082,0.009369,0.157185,0.001041,0.002082,0.068703,0.031229,0.026024,0.023942,0.005205,0.001041,0.007287,0.012492,0.175923,0.002082
True,0.000000,0.018716,0.000000,0.224593,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.037432,0.018716,0.000000,0.037432,0.000000,0.000000,0.018716,0.037432,0.056148,0.037432,0.149729,0.000000,0.037432,0.000000,0.224593,0.374322,0.000000,0.000000,0.000000,0.000000,0.000000,0.074864,0.000000,0.000000,0.000000,0.000000,0.037432,0.000000,0.00000,0.056148,0.000000,0.000000,0.000000,0.000000,0.168445,0.411754,0.205877,0.000000,0.000000,0.018716,0.112296,0.074864,0.074864,0.112296,0.000000,0.149729,0.000000,0.000000,0.000000,0.000000,0.037432,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.280741,0.037432,0.018716,0.000000,5.371514,2.900992,2.264645,0.524050,0.000000,0.093580,0.074864,0.093580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.149729,0.449186,0.074864,0.093580,0.056148,0.018716,0.018716,0.037432,0.842223,0.224593,0.262025,0.374322,0.336889,0.112296,0.000000,0.000000,0.000000,0.000000,0.056148,0.018716,0.112296,0.037432,0.000000,0.018716,0.000000,0.00000,0.000000,0.000000,0.018716,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.299457,0.000000,0.000000,0.018716,8.833988,0.000000,0.131013,0.000000,0.823507,0.018716,0.056148,0.018716,0.205877,1.665731,0.112296,0.430470,0.112296,0.000000,0.056148,0.131013,0.056148,0.018716,0.299457,0.524050,0.093580,0.000000,0.000000,0.000000,0.205877,0.131013,0.000000,0.823507,0.187161,0.692495,0.018716,0.018716,0.000000,0.056148,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.056148,0.131013,0.018716,0.037432,0.037432,0.000000,0.056148,0.000000,0.00000,0.112296,0.018716,0.037432,0.000000,0.018716,0.000000,0.000000,0.000000,0.168445,0.056148,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.09358,0.018716,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.037432,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.917088,0.000000,0.000000,0.018716,0.000000,0.074864,0.000000,0.000000,0.00000,0.000000,0.224593,0.018716,0.000000,0.000000,2.657683,0.112296,1.628299,0.018716,0.000000,0.299457,0.318173,2.021336,0.018716,1.216545,1.759311,0.131013,0.056148,0.018716,0.018716,0.018716,0.000000,0.018716,0.973236,1.235261,0.262025,4.997193,6.962381,0.018716,0.000000,0.000000,0.018716,0.168445,0.074864,0.093580,0.018716,0.056148,0.074864,0.168445,0.056148,0.000000,0.112296,0.018716,0.037432,0.000000,0.000000,0.000000,0.000000,0.411754,0.018716,0.018716,0.112296,0.037432,0.112296,0.093580,0.000000,0.000000,0.018716,0.018716,0.000000,0.000000,0.037432,0.131013,0.018716,0.000000,0.056148,0.000000,0.000000,0.000000,0.037432,0.000000,0.074864,0.131013,0.000000,0.000000,0.018716,1.871608,0.000000,0.037432,3.350178,0.093580,0.879656,0.037432,0.000000,3.163017,0.018716,0.000000,0.000000,0.000000,0.336889,0.056148,0.018716,0.767359,0.018716,0.018716,0.000000,0.262025,0.018716,0.037432,1.478570,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.243309,0.037432,0.074864,0.018716,0.000000,0.262025,0.243309,0.018716,0.00000,0.037432,0.000000,0.000000,0.000000,0.056148,0.018716,0.000000,0.000000,0.056148,0.149729,0.636347,0.168445,0.037432,0.018716,0.037432,0.037432,0.074864,0.131013,0.000000,0.524050,0.056148,0.018716,0.486618,0.074864,0.112296,0.580198,0.336889,0.000000,0.000000,0.074864,0.093580,1.179113,0.879656,0.00000,0.000000,0.112296,0.224593,0.056148,0.093580,0.000000,0.000000,0.037432,0.000000,4.529291,0.018716,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.00000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.018716,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,1.141681,0.000000,0.037432,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.205877,0.000000,0.000000,0.000000,0.000000,0.018716,0.00000,1.834176,0.018716,0.093580,0.037432,0.000000,0.018716,0.037432,0.074864,0.018716,0.000000,0.018716,0.018716,0.018716,0.018716,0.056148,0.112296,0.000000,0.000000,0.000000,0.09358,0.037432,0.112296,0.112296,0.243309,0.000000,0.000000,0.018716,0.000000,0.056148,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037432,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,1.459854,0.205877,0.037432,0.018716,0.074864,0.636347,0.505334,0.131013,0.411754,0.243309,0.018716,0.112296,0.000000,0.037432,0.000000,0.018716,0.000000,0.000000,0.000000,0.243309,0.224593,0.000000,0.000000,0.018716,0.018716,0.000000,0.037432,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.074864,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037432,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.299457,0.168445,0.374322,0.355605,0.018716,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.187161,0.000000,0.131013,0.000000,0.000000,0.000000,0.018716,0.093580,0.000000,0.224593,0.000000,0.000000,0.000000,0.018716,0.018716,0.000000,0.000000,0.018716,0.000000,0.018716,0.018716,0.018716,0.000000,0.000000,0.000000,0.074864,0.000000,0.037432,0.018716,0.000000,0.000000,0.000000,0.037432,0.018716,0.056148,0.000000,0.000000,0.018716,0.056148,0.000000,0.000000,0.018716,0.000000,0.000000,0.000000,0.00000,0.018716,0.000000,0.000000,0.000000,0.000000,0.093580,0.000000,0.000000,0.000000,0.000000,0.000000,0.187161,0.000000,0.018716,0.168445,0.018716,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000,0.112296,0.000000,0.000000,0.000000,0.000000,0.037432,0.000000,0.000000,0.000000,0.000000,0.018716,0.000000,0.000000

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,157,158,161,162,163,164,17,170,171,172,173,174,175,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,214,215,216,217,218,220,223,225,226,227,228,230,233,235,236,238,239,240,241,242,243,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,265,266,268,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,310,311,312,313,314,315,317,318,319,323,327,331,332,333,334,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,353,354,355,356,357,358,359,360,361,362,365,365.44,366,368,369,370,372,373,374,376,377,378,379,38,380,381,382,383,384,385,386,387,388,389,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,47,470,472,473,475,477,478,480,481,482,483,484,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,514,515,516,517,518,519,521,522,523,524,525,527,528,529,53,530,531,532,533,534,535,536,537,538,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,607,608,610,611,614,616,617,618,619,620,621,622,623,624,625,626,627,641,642,643,644,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,670,671,674,680,681,682,684,685,686,690,692,693,694,695,696,697,698,7,70,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,741,742,744,745,746,747,75,750,751,752,753,754,755,756,757,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,834,836,837,838,840,841,842,844,845,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,872,873,875,876,877,879,88,880,881,882,883,884,890,891,892,893,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,928,930,933,934,935,94,942,943,944,945,948,951,952,953,955,956,958,959,962,965,966,967,969,970,971,972,980,987,989,991,992,995,996,997,998,999,E812,E813,E815,E816,E817,E818,E819,E822,E825,E826,E828,E849,E850,E852,E853,E854,E855,E858,E861,E864,E865,E870,E876,E878,E879,E880,E881,E882,E883,E884,E885,E886,E887,E888,E892,E894,E900,E901,E904,E905,E906,E912,E915,E916,E917,E919,E920,E922,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E943,E944,E945,E946,E947,E949,E950,E955,E956,E965,E966,E980,E987,V01,V02,V03,V06,V07,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V22,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
has_max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
False,0.002104,0.016828,0.001052,0.207196,0.001052,0.006311,0.001052,0.001052,0.006311,0.003155,0.067312,0.002104,0.022087,0.002104,0.001052,0.004207,0.001052,0.001052,0.012621,0.009466,0.003155,0.055743,0.012621,0.012621,0.004207,0.038915,0.001052,0.003155,0.184057,0.005259,0.001052,0.001052,0.004207,0.004207,0.005259,0.002104,0.044174,0.001052,0.007362,0.004207,0.004207,0.014725,0.051536,0.001052,0.015776,0.026294,0.005259,0.002104,0.001052,0.001052,0.103072,0.376529,0.235594,0.044174,0.009466,0.012621,0.124107,0.068364,0.064157,0.017880,0.009466,0.095710,0.003155,0.001052,0.001052,0.001052,0.054691,0.005259,0.002104,0.006311,0.001052,0.006311,0.007362,0.001052,0.005259,0.004207,0.001052,0.034708,0.006311,0.005259,0.010518,0.071519,0.001052,0.536396,0.003155,0.005259,11.533567,0.877165,1.339938,0.118849,0.019983,0.017880,0.038915,0.012621,0.005259,0.004207,0.015776,0.002104,0.001052,0.001052,0.422806,0.186161,0.133573,0.057847,0.108331,0.125159,0.076778,0.033656,1.079103,0.141987,0.298699,0.049433,0.110434,0.021035,0.009466,0.006311,0.156712,0.014725,0.007362,0.024190,0.045226,0.064157,0.005259,0.003155,0.004207,0.009466,0.015776,0.008414,0.257680,0.001052,0.016828,0.003155,0.000000,0.006311,0.002104,1.968889,0.010518,0.068364,0.084141,5.086297,0.039967,0.674176,0.009466,0.398616,0.035760,0.041019,0.012621,0.134625,1.200055,0.122004,0.379684,0.110434,0.041019,0.077830,0.043122,0.062054,0.077830,0.312372,0.288181,0.213507,0.006311,0.038915,0.004207,0.001052,0.233490,0.083089,0.188264,0.157764,0.929753,0.005259,0.014725,0.001052,0.045226,0.012621,0.213507,0.014725,0.004207,0.003155,0.001052,0.011569,0.009466,0.026294,0.003155,0.079934,0.179850,0.084141,0.028397,0.005259,0.003155,0.005259,0.098865,0.034708,0.006311,0.062054,0.001052,0.169333,0.018932,0.057847,0.037863,0.034708,0.002104,0.087296,0.016828,0.004207,0.002104,0.011569,0.003155,0.009466,0.017880,0.026294,0.395461,0.01788,0.006311,0.002104,0.001052,0.066261,0.018932,0.001052,0.005259,0.034708,0.025242,0.001052,0.007362,0.003155,0.002104,0.002104,0.001052,0.012621,0.006311,0.159867,0.009466,0.000000,0.014725,0.007362,0.002104,0.001052,0.018932,0.001052,0.005259,0.013673,0.001052,0.016828,0.001052,0.222972,0.154608,0.029449,8.360416,0.384943,2.424300,0.127263,0.009466,0.730971,0.211403,0.409133,0.356546,0.328148,3.670632,0.031553,0.161971,0.003155,0.023139,0.010518,0.006311,0.024190,1.029670,1.127483,0.269250,3.926209,4.542538,0.065209,0.002104,0.007362,0.009466,0.144091,0.056795,0.054691,0.007362,0.088348,0.319734,0.230335,0.055743,0.025242,0.198782,0.044174,0.003155,0.026294,0.039967,0.001052,0.009466,0.004207,0.215610,0.013673,0.080985,0.038915,0.023139,0.288181,0.102020,0.002104,0.022087,0.01788,0.001052,0.004207,0.065209,0.133573,0.001052,0.003155,0.005259,0.054691,0.001052,0.015776,0.031553,0.001052,0.005259,0.054691,0.002104,0.001052,0.001052,0.537448,0.014725,0.001052,0.055743,0.560586,0.175643,0.699418,0.014725,0.004207,2.600995,0.002104,0.004207,0.012621,0.004207,0.073623,0.004207,0.005259,0.383891,0.036811,0.013673,0.154608,0.013673,0.043122,0.845613,0.033656,0.012621,0.011569,0.004207,0.001052,0.003155,0.006311,0.004207,0.001052,0.024190,0.623692,0.049433,0.025242,0.021035,0.002104,0.265043,0.272405,0.030501,0.001052,0.013673,0.001052,0.001052,0.004207,0.004207,0.014725,0.140935,0.028397,0.015776,0.013673,0.107279,0.306061,0.188264,0.127263,0.004207,0.005259,0.021035,0.061002,0.108331,0.001052,0.012621,0.296595,0.049433,0.051536,0.136728,0.043122,0.041019,0.144091,0.252422,0.008414,0.009466,0.093606,0.011569,0.080985,0.936064,2.031994,0.014725,0.027346,0.046277,0.144091,0.063105,0.337614,0.009466,0.052588,0.090451,0.002104,0.014725,1.914198,0.079934,0.021035,0.001052,0.001052,0.004207,0.005259,0.009466,0.012621,0.008414,0.01788,0.032604,0.028397,0.026294,0.030501,0.005259,0.029449,0.013673,0.001052,0.004207,0.002104,0.050484,0.030501,0.016828,0.002104,0.034708,0.002104,0.006311,0.018932,0.012621,0.112538,0.008414,0.007362,0.004207,0.013673,0.003155,0.011569,0.001052,0.007362,0.028397,0.001052,0.006311,0.004207,0.014725,0.014725,0.005259,0.001052,0.002104,0.001052,0.001052,0.012621,0.075727,0.883476,0.001052,0.002104,0.010518,0.002104,0.015776,0.014725,0.011569,0.008414,0.023139,0.001052,0.010518,0.002104,0.272405,0.005259,0.002104,0.003155,0.007362,0.008414,0.002104,1.367284,0.007362,0.016828,0.111486,0.024190,0.006311,0.014725,0.080985,0.213507,0.076778,0.007362,0.009466,0.096762,0.003155,0.053640,0.125159,0.031553,0.145142,0.013673,0.033656,0.032604,0.109383,0.152505,0.187213,0.122004,0.001052,0.192472,0.002104,0.002104,0.023139,0.018932,0.02419,0.008414,0.005259,0.001052,0.018932,0.009466,0.009466,0.001052,0.001052,0.005259,0.005259,0.015776,0.001052,0.001052,0.006311,0.001052,0.005259,0.003155,0.003155,1.319955,0.132521,0.116745,0.057847,0.241904,0.378633,0.575311,0.360753,0.355494,0.293440,0.046277,0.190368,0.014725,0.013673,0.008414,0.106227,0.002104,0.013673,0.002104,0.312372,0.186161,0.002104,0.004207,0.021035,0.028397,0.037863,0.019983,0.006311,0.001052,0.032604,0.018932,0.002104,0.005259,0.003155,0.017880,0.006311,0.002104,0.010518,0.021035,0.007362,0.003155,0.004207,0.001052,0.009466,0.001052,0.001052,0.010518,0.001052,0.003155,0.003155,0.008414,0.004207,0.002104,0.004207,0.003155,0.003155,0.001052,0.002104,0.006311,0.007362,0.003155,0.001052,0.001052,0.004207,0.003155,0.010518,0.002104,0.002104,0.001052,0.001052,0.038915,0.001052,0.001052,0.001052,0.001052,0.001052,0.001052,0.006311,0.006311,0.010518,0.001052,0.000000,0.004207,0.007362,0.001052,0.005259,0.016828,0.004207,0.009466,0.005259,0.006311,0.004207,0.002104,0.002104,0.005259,0.004207,0.011569,0.006311,0.002104,0.003155,0.023139,0.003155,0.015776,0.015776,0.039967,0.002104,0.001052,0.003155,0.005259,0.001052,0.021035,0.001052,0.002104,0.001052,0.005259,0.002104,0.001052,0.001052,0.002104,0.001052,0.002104,0.010518,0.022087,0.006311,0.007362,0.003155,0.001052,0.010518,0.001052,0.001052,0.001052,0.001052,0.001052,0.002104,0.007362,0.001052,0.308165,0.280819,0.301854,0.323941,0.024190,0.022087,0.002104,0.001052,0.009466,0.001052,0.004207,0.007362,0.001052,0.001052,0.001052,0.001052,0.209300,0.005259,0.001052,0.001052,0.001052,0.002104,0.003155,0.000000,0.001052,0.001052,0.007362,0.001052,0.166178,0.055743,0.021035,0.009466,0.001052,0.000000,0.024190,0.115693,0.001052,0.004207,0.119900,0.001052,0.001052,0.001052,0.002104,0.000000,0.003155,0.005259,0.001052,0.001052,0.003155,0.004207,0.002104,0.003155,0.001052,0.002104,0.007362,0.008414,0.005259,0.011569,0.009466,0.064157,0.012621,0.021035,0.028397,0.006311,0.005259,0.005259,0.015776,0.005259,0.046277,0.003155,0.017880,0.001052,0.002104,0.035760,0.001052,0.014725,0.001052,0.003155,0.001052,0.001052,0.002104,0.001052,0.001052,0.004207,0.005259,0.002104,0.001052,0.018932,0.088348,0.241904,0.002104,0.207196,0.005259,0.012621,0.343925,0.006311,0.023139,0.015776,0.001052,0.004207,0.002104,0.038915,0.247163,0.221921,0.025242,1.406199,0.063105,0.056795,0.006311,0.057847,0.007362,0.007362,0.516413,0.004207,0.005259,0.030501,0.013673,0.044174,0.025242,0.018932,0.002104,0.008414,0.098865,0.003155
True,0.000000,0.075988,0.000000,0.170973,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.000000,0.037994,0.018997,0.000000,0.000000,0.018997,0.000000,0.000000,0.113982,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.018997,0.000000,0.037994,0.000000,0.000000,0.037994,0.000000,0.000000,0.000000,0.000000,0.132979,0.512918,0.265957,0.056991,0.000000,0.000000,0.075988,0.037994,0.094985,0.037994,0.018997,0.170973,0.000000,0.000000,0.018997,0.000000,0.018997,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056991,0.000000,0.000000,0.000000,0.170973,0.000000,0.569909,0.000000,0.018997,11.189210,1.538754,1.804711,0.398936,0.018997,0.018997,0.037994,0.000000,0.056991,0.000000,0.000000,0.000000,0.018997,0.000000,0.512918,0.417933,0.056991,0.075988,0.151976,0.170973,0.018997,0.056991,1.025836,0.113982,0.607903,0.056991,0.151976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.075988,0.151976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.132979,0.000000,0.018997,0.000000,0.018997,0.018997,0.000000,1.842705,0.037994,0.056991,0.075988,6.439970,0.000000,0.740881,0.018997,0.360942,0.037994,0.037994,0.000000,0.189970,1.120821,0.170973,0.512918,0.151976,0.000000,0.132979,0.037994,0.094985,0.132979,0.341945,0.588906,0.208967,0.000000,0.018997,0.000000,0.018997,0.360942,0.189970,0.531915,0.170973,0.759878,0.000000,0.037994,0.000000,0.037994,0.000000,0.265957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037994,0.018997,0.075988,0.265957,0.151976,0.075988,0.000000,0.018997,0.000000,0.056991,0.000000,0.000000,0.018997,0.018997,0.056991,0.018997,0.075988,0.056991,0.018997,0.037994,0.075988,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.341945,0.00000,0.018997,0.000000,0.000000,0.056991,0.018997,0.000000,0.018997,0.000000,0.018997,0.000000,0.018997,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.189970,0.018997,0.018997,0.000000,0.000000,0.000000,0.000000,0.037994,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.322948,0.056991,0.000000,6.458967,0.170973,0.987842,0.056991,0.000000,0.607903,0.151976,0.189970,0.132979,0.322948,3.305471,0.056991,0.303951,0.000000,0.018997,0.000000,0.000000,0.037994,1.595745,1.215805,0.303951,4.217325,4.901216,0.075988,0.000000,0.000000,0.018997,0.113982,0.037994,0.113982,0.018997,0.056991,0.265957,0.037994,0.018997,0.000000,0.303951,0.037994,0.000000,0.056991,0.018997,0.000000,0.000000,0.000000,0.113982,0.000000,0.075988,0.018997,0.000000,0.208967,0.132979,0.000000,0.000000,0.00000,0.000000,0.018997,0.170973,0.094985,0.000000,0.000000,0.000000,0.094985,0.000000,0.018997,0.037994,0.018997,0.000000,0.075988,0.000000,0.000000,0.000000,1.082827,0.056991,0.000000,0.056991,0.778875,0.037994,0.550912,0.000000,0.000000,2.507599,0.018997,0.000000,0.018997,0.018997,0.265957,0.018997,0.000000,0.284954,0.037994,0.000000,0.151976,0.000000,0.018997,0.949848,0.018997,0.018997,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.037994,0.037994,0.607903,0.056991,0.075988,0.056991,0.018997,0.626900,0.151976,0.037994,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.018997,0.132979,0.037994,0.018997,0.000000,0.113982,0.284954,0.189970,0.113982,0.000000,0.000000,0.056991,0.075988,0.075988,0.000000,0.018997,0.531915,0.075988,0.056991,0.113982,0.037994,0.113982,0.227964,0.189970,0.018997,0.000000,0.151976,0.018997,0.284954,1.386778,1.139818,0.018997,0.000000,0.056991,0.056991,0.094985,0.341945,0.000000,0.018997,0.037994,0.000000,0.000000,2.298632,0.056991,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.018997,0.000000,0.00000,0.000000,0.018997,0.000000,0.018997,0.018997,0.018997,0.000000,0.000000,0.018997,0.000000,0.018997,0.018997,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056991,0.892857,0.000000,0.018997,0.018997,0.000000,0.000000,0.037994,0.000000,0.018997,0.018997,0.000000,0.000000,0.000000,0.417933,0.018997,0.000000,0.000000,0.018997,0.000000,0.000000,1.139818,0.000000,0.000000,0.056991,0.037994,0.018997,0.000000,0.113982,0.208967,0.075988,0.000000,0.000000,0.075988,0.000000,0.037994,0.037994,0.018997,0.189970,0.056991,0.037994,0.000000,0.056991,0.037994,0.151976,0.189970,0.000000,0.341945,0.000000,0.000000,0.000000,0.037994,0.00000,0.018997,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,1.500760,0.132979,0.151976,0.037994,0.113982,0.531915,0.702888,0.284954,0.284954,0.208967,0.037994,0.246960,0.000000,0.056991,0.000000,0.170973,0.000000,0.000000,0.000000,0.284954,0.246960,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.018997,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.056991,0.000000,0.000000,0.000000,0.018997,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.018997,0.037994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037994,0.018997,0.018997,0.037994,0.037994,0.000000,0.000000,0.000000,0.018997,0.000000,0.018997,0.000000,0.000000,0.000000,0.056991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.037994,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.113982,0.265957,0.208967,0.151976,0.056991,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.379939,0.000000,0.018997,0.000000,0.000000,0.000000,0.018997,0.018997,0.000000,0.000000,0.000000,0.000000,0.113982,0.113982,0.113982,0.000000,0.000000,0.018997,0.018997,0.132979,0.000000,0.037994,0.322948,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037994,0.037994,0.075988,0.056991,0.189970,0.075988,0.037994,0.056991,0.018997,0.018997,0.018997,0.094985,0.000000,0.151976,0.000000,0.056991,0.000000,0.000000,0.075988,0.000000,0.056991,0.000000,0.000000,0.000000,0.000000,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018997,0.037994,0.170973,0.000000,0.132979,0.000000,0.000000,0.132979,0.018997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.151976,0.000000,0.056991,0.987842,0.000000,0.000000,0.018997,0.056991,0.018997,0.000000,0.189970,0.000000,0.000000,0.000000,0.000000,0.056991,0.000000,0.000000,0.000000,0.000000,0.037994,0.000000

--- number_diagnoses ---

                     count      mean       std  min  25%  50%  75%   max
has_max_glu_serum
False              96420.0  7.446318  1.933672  1.0  6.0  8.0  9.0  16.0
True                5346.0  6.994949  1.881865  1.0  6.0  7.0  9.0   9.0

max_glu_serum           >200       >300       Norm
has_max_glu_serum
True               27.777778  23.643846  48.578376

A1Cresult                 >7         >8       Norm
has_max_glu_serum
False              22.422249  48.080144  29.497608
True               21.140940  59.395973  19.463087

metformin              Down         No     Steady        Up
has_max_glu_serum
False              0.576644  80.080896  18.282514  1.059946
True               0.355406  85.372241  13.430602  0.841751

repaglinide            Down         No    Steady        Up
has_max_glu_serum
False              0.046671  98.434972  1.405310  0.113047
True               0.000000  99.438833  0.542462  0.018706

nateglinide            Down         No    Steady        Up
has_max_glu_serum
False              0.011408  99.272972  0.690728  0.024891
True               0.000000  99.962589  0.037411  0.000000

chlorpropamide         Down         No    Steady        Up
has_max_glu_serum
False              0.001037  99.918067  0.074673  0.006223
True               0.000000  99.869061  0.130939  0.000000

glimepiride            Down         No    Steady        Up
has_max_glu_serum
False              0.197055  94.723086  4.747978  0.331881
True               0.074822  98.073326  1.720913  0.130939

acetohexamide              No    Steady
has_max_glu_serum
False               99.998963  0.001037
True               100.000000  0.000000

glipizide              Down         No     Steady        Up
has_max_glu_serum
False              0.549678  87.570006  11.133582  0.746733
True               0.561167  86.887392  11.616162  0.935279

glyburide              Down         No    Steady        Up
has_max_glu_serum
False              0.546567  89.545737  9.111180  0.796515
True               0.692106  89.337823  9.147026  0.823045

tolbutamide               No    Steady
has_max_glu_serum
False              99.981332  0.018668
True               99.906472  0.093528

pioglitazone           Down         No    Steady        Up
has_max_glu_serum
False              0.114084  92.689276  6.965360  0.231280
True               0.149645  94.781145  4.863449  0.205761

rosiglitazone          Down         No    Steady        Up
has_max_glu_serum
False              0.086082  93.719145  6.019498  0.175275
True               0.074822  94.219978  5.536850  0.168350

acarbose               Down         No    Steady        Up
has_max_glu_serum
False              0.003111  99.699233  0.288322  0.009334
True               0.000000  99.663300  0.317995  0.018706

miglitol               Down          No    Steady        Up
has_max_glu_serum
False              0.005186   99.960589  0.032151  0.002074
True               0.000000  100.000000  0.000000  0.000000

troglitazone               No    Steady
has_max_glu_serum
False               99.996889  0.003111
True               100.000000  0.000000

tolazamide                No    Steady        Up
has_max_glu_serum
False              99.961626  0.037337  0.001037
True               99.962589  0.037411  0.000000

examide               No
has_max_glu_serum
False              100.0
True               100.0

citoglipton           No
has_max_glu_serum
False              100.0
True               100.0

insulin                 Down         No     Steady         Up
has_max_glu_serum
False              11.781788  46.494503  30.562124  11.161585
True               16.049383  47.755331  25.832398  10.362888

glyburide-metformin      Down         No    Steady        Up
has_max_glu_serum
False                0.006223  99.269861  0.715619  0.008297
True                 0.000000  99.962589  0.037411  0.000000

glipizide-metformin          No    Steady
has_max_glu_serum
False                 99.986517  0.013483
True                 100.000000  0.000000

glimepiride-pioglitazone          No    Steady
has_max_glu_serum
False                      99.998963  0.001037
True                      100.000000  0.000000

metformin-rosiglitazone          No    Steady
has_max_glu_serum
False                     99.997926  0.002074
True                     100.000000  0.000000

metformin-pioglitazone          No    Steady
has_max_glu_serum
False                    99.998963  0.001037
True                    100.000000  0.000000

change                    Ch         No
has_max_glu_serum
False              46.311968  53.688032
True               44.089039  55.910961

diabetesMed               No        Yes
has_max_glu_serum
False              22.806472  77.193528
True               26.430976  73.569024

readmitted               <30        >30         NO
has_max_glu_serum
False              11.093134  34.856876  54.049990
True               12.364385  36.213992  51.421624

Analizom atributa „has_max_glu_serum“ ispitano je da li dostupnost rezultata serumске glukoze pokazuje povezanost sa ostalim relevantnim atributima. Uoceno je da se nedostajanje ovog podatka ne razlikuje znacajno i konzistentno izmedju analiziranih kategorija, zbog cega sama informacija o tome da li je test evidentiran ne pruza dovoljno osnova za dalje zakljucivanje. Stoga je atribut „has_max_glu_serum“ uklonjen iz dalje analize. Medjutim, atribut „max_glu_serum“ je zadrzan, jer njegove vrednosti predstavljaju rezultat merenja serumske glukoze (Norm, >200, >300) i mogu sadrzati znacajnu informaciju o zdravstvenom stanju pacijenta i njegovoj povezanosti sa ishodom hospitalizacije.

In [15]:
data = data.drop(["has_max_glu_serum"], axis= 1)

In [16]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,NaN,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),1,1,7,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),2,1,4,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,NaN,NaN,No,No,No,No,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),1,3,7,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,NaN,Steady,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),1,6,7,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),3,1,2,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),1,3,7,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),1,1,7,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),1,1,7,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),1,1,7,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,NaN,Male,[70-80),3,6,2,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,NaN,NaN,No,No,No,No,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,NaN,Female,[50-60),2,1,4,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,NaN,Male,[60-70),2,1,4,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,NaN,NaN,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),2,1,4,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),2,6,1,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),3,1,2,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),1,1,7,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),1,3,7,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,NaN,>7,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),1,1,1,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),2,1,2,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),1,2,7,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),1,1,7,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,NaN,NaN,No,No,No,No,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),1,5,7,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),1,1,7,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),2,6,2,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
34,293118,3327282,Caucasian,Female,[70-80),2,11,2,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
35,325848,63023292,Caucasian,Female,[60-70),1,1,7,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),3,1,2,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),1,1,7,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,NaN,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),1,6,7,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),2,1,2,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),1,2,7,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),2,1,2,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),2,1,1,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,NaN,NaN,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),1,1,7,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,NaN,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
44,450210,80177094,Caucasian,Female,[80-90),1,11,7,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
45,464994,106936875,Caucasian,Female,[40-50),3,1,2,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),3,5,4,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,NaN,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),3,3,4,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,NaN,NaN,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),3,1,2,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),2,6,4,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

Number of rows:101766
Number of columns:49
                         Data type:  Missing values:  Percentage of na:  \
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id             int64                0           0.000000
discharge_disposition_id      int64                0           0.000000
admission_source_id           int64                0           0.000000
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
max_glu_serum                object            96420          94.746772
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000

                          Value count:
encounter_id                    101766
patient_nbr                      71518
race                                 5
gender                               3
age                                 10
admission_type_id                    8
discharge_disposition_id            26
admission_source_id                 17
time_in_hospital                    14
payer_code                          17
medical_specialty                   72
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             716
diag_2                             748
diag_3                             789
number_diagnoses                    16
max_glu_serum                        3
A1Cresult                            3
metformin                            4
repaglinide                          4
nateglinide                          4
chlorpropamide                       4
glimepiride                          4
acetohexamide                        2
glipizide                            4
glyburide                            4
tolbutamide                          2
pioglitazone                         4
rosiglitazone                        4
acarbose                             4
miglitol                             4
troglitazone                         2
tolazamide                           3
examide                              1
citoglipton                          1
insulin                              4
glyburide-metformin                  4
glipizide-metformin                  2
glimepiride-pioglitazone             2
metformin-rosiglitazone              2
metformin-pioglitazone               2
change                               2
diabetesMed                          2
readmitted                           3

In [17]:
data_id_mapping = pd.read_csv("../datasets/id_mapping.csv")

In [18]:
data_overview(data_id_mapping)

,ID mappings for the diabetes dataset,? - always means a missing value
0,admission_type_id,description
1,1,Emergency
2,2,Urgent
3,3,Elective
4,4,Newborn
5,5,Not Available
6,6,NaN
7,7,Trauma Center
8,8,Not Mapped
9,NaN,NaN
10,discharge_disposition_id,description
11,1,Discharged to home
12,2,Discharged/transferred to another short term h...
13,3,Discharged/transferred to SNF
14,4,Discharged/transferred to ICF
15,5,Discharged/transferred to another type of inpa...
16,6,Discharged/transferred to home with home healt...
17,7,Left AMA
18,8,Discharged/transferred to home under care of H...
19,9,Admitted as an inpatient to this hospital
20,10,Neonate discharged to another hospital for neo...
21,11,Expired
22,12,Still patient or expected to return for outpat...
23,13,Hospice / home
24,14,Hospice / medical facility
25,15,Discharged/transferred within this institution...
26,16,Discharged/transferred/referred another instit...
27,17,Discharged/transferred/referred to this instit...
28,18,NaN
29,19,"Expired at home. Medicaid only, hospice."
30,20,"Expired in a medical facility. Medicaid only, ..."
31,21,"Expired, place unknown. Medicaid only, hospice."
32,22,Discharged/transferred to another rehab fac in...
33,23,Discharged/transferred to a long term care hos...
34,24,Discharged/transferred to a nursing facility c...
35,25,Not Mapped
36,26,Unknown/Invalid
37,30,Discharged/transferred to another Type of Heal...
38,27,Discharged/transferred to a federal health car...
39,28,Discharged/transferred/referred to a psychiatr...
40,29,Discharged/transferred to a Critical Access Ho...
41,NaN,NaN
42,admission_source_id,description
43,1,Physician Referral
44,2,Clinic Referral
45,3,HMO Referral
46,4,Transfer from a hospital
47,5,Transfer from a Skilled Nursing Facility (SNF)
48,6,Transfer from another health care facility
49,7,Emergency Room

Number of rows:68
Number of columns:2
                                     Data type:  Missing values:  \
ID mappings for the diabetes dataset     object                2
 ? - always means a missing value        object                5

                                      Percentage of na:  Value count:
ID mappings for the diabetes dataset           2.941176            33
 ? - always means a missing value              7.352941            56

Pored standardnih nedostajucih vrednosti potrebno je analizirati i tabelu id_mapping.csv i proveriti da li postoje sifre koje se takodje mogu tretirati kao NaN.

In [19]:
data_id_mapping.columns

Index(['ID mappings for the diabetes dataset', ' ? - always means a missing value'], dtype='object')

In [20]:
admission_mapping = data_id_mapping[0:9]

In [21]:
admission_mapping.head(12)

  ID mappings for the diabetes dataset  ? - always means a missing value
0                    admission_type_id                       description
1                                    1                         Emergency
2                                    2                            Urgent
3                                    3                          Elective
4                                    4                           Newborn
5                                    5                     Not Available
6                                    6                               NaN
7                                    7                     Trauma Center
8                                    8                        Not Mapped

In [22]:
admission_mapping.columns= admission_mapping.iloc[0]

In [23]:
admission_mapping= admission_mapping[1:].reset_index(drop=True)

In [24]:
discharge_disposition_mapping = data_id_mapping[10:41]

In [25]:
discharge_disposition_mapping.head(40)

,ID mappings for the diabetes dataset,? - always means a missing value
10,discharge_disposition_id,description
11,1,Discharged to home
12,2,Discharged/transferred to another short term h...
13,3,Discharged/transferred to SNF
14,4,Discharged/transferred to ICF
15,5,Discharged/transferred to another type of inpa...
16,6,Discharged/transferred to home with home healt...
17,7,Left AMA
18,8,Discharged/transferred to home under care of H...
19,9,Admitted as an inpatient to this hospital
20,10,Neonate discharged to another hospital for neo...
21,11,Expired
22,12,Still patient or expected to return for outpat...
23,13,Hospice / home
24,14,Hospice / medical facility
25,15,Discharged/transferred within this institution...
26,16,Discharged/transferred/referred another instit...
27,17,Discharged/transferred/referred to this instit...
28,18,NaN
29,19,"Expired at home. Medicaid only, hospice."
30,20,"Expired in a medical facility. Medicaid only, ..."
31,21,"Expired, place unknown. Medicaid only, hospice."
32,22,Discharged/transferred to another rehab fac in...
33,23,Discharged/transferred to a long term care hos...
34,24,Discharged/transferred to a nursing facility c...
35,25,Not Mapped
36,26,Unknown/Invalid
37,30,Discharged/transferred to another Type of Heal...
38,27,Discharged/transferred to a federal health car...
39,28,Discharged/transferred/referred to a psychiatr...
40,29,Discharged/transferred to a Critical Access Ho...

In [26]:
discharge_disposition_mapping.columns = discharge_disposition_mapping.iloc[0]

In [27]:
discharge_disposition_mapping = discharge_disposition_mapping[1:].reset_index(drop = True)

In [28]:
discharge_disposition_mapping.columns

Index(['discharge_disposition_id', 'description'], dtype='object', name=10)

In [29]:
discharge_disposition_mapping.columns.name = None

In [30]:
admission_source_mapping = data_id_mapping[42:]

In [31]:
admission_source_mapping.head(30)

,ID mappings for the diabetes dataset,? - always means a missing value
42,admission_source_id,description
43,1,Physician Referral
44,2,Clinic Referral
45,3,HMO Referral
46,4,Transfer from a hospital
47,5,Transfer from a Skilled Nursing Facility (SNF)
48,6,Transfer from another health care facility
49,7,Emergency Room
50,8,Court/Law Enforcement
51,9,Not Available
52,10,Transfer from critial access hospital
53,11,Normal Delivery
54,12,Premature Delivery
55,13,Sick Baby
56,14,Extramural Birth
57,15,Not Available
58,17,NaN
59,18,Transfer From Another Home Health Agency
60,19,Readmission to Same Home Health Agency
61,20,Not Mapped
62,21,Unknown/Invalid
63,22,Transfer from hospital inpt/same fac reslt in ...
64,23,Born inside this hospital
65,24,Born outside this hospital
66,25,Transfer from Ambulatory Surgery Center
67,26,Transfer from Hospice

In [32]:
admission_source_mapping.columns = admission_source_mapping.iloc[0]

In [33]:
admission_source_mapping = admission_source_mapping[1:].reset_index(drop=True)

In [34]:
admission_source_mapping.columns.name = None

In [35]:
def data_frame_to_dict(x):
 dictionary = dict(
 zip(
    x[x.columns[0]].astype(int),
    x[x.columns[1]]
 )  
 )
 return dictionary

In [36]:
admission_dict = data_frame_to_dict(admission_mapping)

In [37]:
discharge_dict  =data_frame_to_dict(discharge_disposition_mapping)

In [38]:
admission_source_dict = data_frame_to_dict(admission_source_mapping)

In [39]:
data_raw = data.copy()

In [40]:
data["admission_type"]= data["admission_type_id"].map(admission_dict)
data["discharge_disposition"] = data["discharge_disposition_id"].map(discharge_dict)
data["admmission_source"]= data["admission_source_id"].map(admission_source_dict)

In [41]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,...,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,admission_type,discharge_disposition,admmission_source
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN,Not Mapped,Physician Referral
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
6,55842,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,NaN,NaN,Steady,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
7,63768,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,NaN,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
8,12522,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
9,15738,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,NaN,NaN,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
10,28236,89869032,AfricanAmerican,Female,[40-50),1,1,7,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
11,36900,77391171,AfricanAmerican,Male,[60-70),2,1,4,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,NaN,NaN,No,No,...,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Urgent,Discharged to home,Transfer from a hospital
12,40926,85504905,Caucasian,Female,[40-50),1,3,7,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,NaN,NaN,Steady,Up,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged/transferred to SNF,Emergency Room
13,42570,77586282,Caucasian,Male,[80-90),1,6,7,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
14,62256,49726791,AfricanAmerican,Female,[60-70),3,1,2,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Elective,Discharged to home,Clinic Referral
15,73578,86328819,AfricanAmerican,Male,[60-70),1,3,7,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
16,77076,92519352,AfricanAmerican,Male,[50-60),1,1,7,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged to home,Emergency Room
17,84222,108662661,Caucasian,Female,[50-60),1,1,7,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,NaN,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
18,89682,107389323,AfricanAmerican,Male,[70-80),1,1,7,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
19,148530,69422211,NaN,Male,[70-80),3,6,2,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,NaN,NaN,No,No,...,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to home with home healt...,Clinic Referral
20,150006,22864131,NaN,Female,[50-60),2,1,4,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
21,150048,21239181,NaN,Male,[60-70),2,1,4,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,NaN,NaN,Steady,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
22,182796,63000108,AfricanAmerican,Female,[70-80),2,1,4,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Urgent,Discharged to home,Transfer from a hospital
23,183930,107400762,Caucasian,Female,[80-90),2,6,1,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,Urgent,Discharged/transferred to home with home healt...,Physician Referral
24,216156,62718876,AfricanAmerican,Female,[70-80),3,1,2,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
25,221634,21861756,Other,Female,[50-60),1,1,7,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,NaN,NaN,Steady,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
26,236316,40523301,Caucasian,Male,[80-90),1,3,7,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,NaN,>7,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
27,248916,115196778,Caucasian,Female,[50-60),1,1,1,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Physician Referral
28,250872,41606064,Caucasian,Male,[20-30),2,1,2,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Clinic Referral
29,252822,18196434,Caucasian,Female,[80-90),1,2,7,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,NaN,NaN,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
30,253380,56480238,AfricanAmerican,Female,[60-70),1,1,7,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,NaN,NaN,No,No,...,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
31,253722,96664626,AfricanAmerican,Male,[70-80),1,5,7,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another type of inpa...,Emergency Room
32,260166,80845353,Caucasian,Female,[70-80),1,1,7,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
33,293058,114715242,Caucasian,Male,[60-70),2,6,2,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged/transferred to home with home healt...,Clinic Referral
34,293118,3327282,Caucasian,Female,[70-80),2,11,2,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Expired,Clinic Referral
35,325848,63023292,Caucasian,Female,[60-70),1,1,7,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,NaN,NaN,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
36,325866,98427861,Caucasian,Female,[70-80),3,1,2,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
37,326028,112002975,Caucasian,Female,[60-70),1,1,7,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,NaN,NaN,Steady,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
38,358776,101002446,Caucasian,Male,[70-80),1,6,7,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
39,377268,104672268,Caucasian,Male,[50-60),2,1,2,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
40,383430,80588529,Caucasian,Female,[70-80),1,2,7,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,NaN,NaN,Steady,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
41,419304,99715041,Caucasian,Male,[40-50),2,1,2,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
42,421194,96435585,Caucasian,Female,[70-80),2,1,1,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,NaN,NaN,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Physician Referral
43,449142,66274866,Caucasian,Male,[50-60),1,1,7,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,NaN,NaN,Steady,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
44,450210,80177094,Caucasian,Female,[80-90),1,11,7,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Expired,Emergency Room
45,464994,106936875,Caucasian,Female,[40-50),3,1,2,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
46,486156,86240259,Caucasian,Female,[70-80),3,5,4,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,NaN,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital
47,498030,51838164,Caucasian,Male,[70-80),3,3,4,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,NaN,NaN,Up,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
48,537834,90097839,Caucasian,Male,[50-60),3,1,2,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,NaN,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
49,544194,34997814,Caucasian,Male,[60-70),2,6,4,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,NaN,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital

Number of rows:101766
Number of columns:52
                         Data type:  Missing values:  Percentage of na:  \
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id             int64                0           0.000000
discharge_disposition_id      int64                0           0.000000
admission_source_id           int64                0           0.000000
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
max_glu_serum                object            96420          94.746772
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000
admission_type               object             5291           5.199182
discharge_disposition        object             3691           3.626948
admmission_source            object             6781           6.663326

                          Value count:
encounter_id                    101766
patient_nbr                      71518
race                                 5
gender                               3
age                                 10
admission_type_id                    8
discharge_disposition_id            26
admission_source_id                 17
time_in_hospital                    14
payer_code                          17
medical_specialty                   72
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             716
diag_2                             748
diag_3                             789
number_diagnoses                    16
max_glu_serum                        3
A1Cresult                            3
metformin                            4
repaglinide                          4
nateglinide                          4
chlorpropamide                       4
glimepiride                          4
acetohexamide                        2
glipizide                            4
glyburide                            4
tolbutamide                          2
pioglitazone                         4
rosiglitazone                        4
acarbose                             4
miglitol                             4
troglitazone                         2
tolazamide                           3
examide                              1
citoglipton                          1
insulin                              4
glyburide-metformin                  4
glipizide-metformin                  2
glimepiride-pioglitazone             2
metformin-rosiglitazone              2
metformin-pioglitazone               2
change                               2
diabetesMed                          2
readmitted                           3
admission_type                       7
discharge_disposition               25
admmission_source                   16

Svaki ID koji je u mapping tabeli bio označen kao NULL, zamenjen je vrednošću NaN u kolonama admission_type_id, discharge_disposition_id i admission_source_id.

Kako bi se atribut max_glu_serum adekvatnije procenio, potrebno je uzeti u obzir da nedostajuca vrednost ne mora predstavljati samo odsustvo podatka, vec moze nositi dodatnu informaciju. Na primer, cinjenica da laboratorijski test nije narucen za odredjenog pacijenta moze biti povezana sa karakteristikama pacijenta ili tokom njegovog lecenja. Zbog toga ce atribut max_glu_serum za sada biti detaljnije analiziran pre donosenja konacne odluke o njegovom uklanjanju ili zadrzavanju.

In [42]:
data["max_glu_serum"]= data["max_glu_serum"].fillna("not_measured")
data["max_glu_serum"].unique()
data["max_glu_serum"].value_counts(dropna=True)

max_glu_serum
not_measured    96420
Norm             2597
>200             1485
>300             1264
Name: count, dtype: int64

In [43]:
compare_column_with_all_columns("max_glu_serum")

--- encounter_id ---

,count,mean,std,min,25%,50%,75%,max
max_glu_serum,,,,,,,,
>200,1485.0,8.652990e+07,5.927419e+07,2521974.0,54621210.0,79662234.0,100232430.0,439020524.0
>300,1264.0,1.141084e+08,8.578641e+07,2265486.0,56707584.0,87266640.0,162983068.5,434911802.0
Norm,2597.0,9.068418e+07,6.214560e+07,2309268.0,56106606.0,82728468.0,103001604.0,436664606.0
not_measured,96420.0,1.690902e+08,1.028127e+08,12522.0,89035549.5,155899620.0,234767727.0,443867222.0

--- patient_nbr ---

,count,mean,std,min,25%,50%,75%,max
max_glu_serum,,,,,,,,
>200,1485.0,3.580077e+07,2.487625e+07,530577.0,23608431.00,24241932.0,28428084.0,115186365.0
>300,1264.0,4.717338e+07,3.142402e+07,302238.0,23797289.25,25892923.5,84428613.0,174774587.0
Norm,2597.0,3.526898e+07,2.419855e+07,209394.0,23605038.00,24239133.0,28371474.0,124870523.0
not_measured,96420.0,5.522301e+07,3.905976e+07,135.0,23273201.25,49196052.0,88476435.0,189502619.0

race           AfricanAmerican     Asian  Caucasian  Hispanic     Other
max_glu_serum
>200                  8.117326  0.477490  86.084584  3.751705  1.568895
>300                  9.497207  0.718276  84.596967  3.910615  1.276935
Norm                  8.556982  0.388954  86.658888  3.189420  1.205757
not_measured         19.905948  0.652845  75.951934  1.964906  1.524368

gender            Female       Male  Unknown/Invalid
max_glu_serum
>200           54.208754  45.791246         0.000000
>300           54.825949  45.174051         0.000000
Norm           53.946862  46.053138         0.000000
not_measured   53.732628  46.264261         0.003111

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
max_glu_serum,,,,,,,,,,
>200,0.000000,0.134680,0.942761,1.952862,7.744108,14.074074,16.835017,29.562290,24.511785,4.242424
>300,0.000000,0.949367,3.401899,5.617089,13.924051,14.715190,17.879747,24.604430,16.060127,2.848101
Norm,0.000000,0.038506,0.423566,2.887948,7.893724,12.475934,18.559877,31.112822,22.410474,4.197151
not_measured,0.166978,0.701099,1.647998,3.733665,9.530180,17.151006,22.324207,25.420037,16.643850,2.680979

--- admission_type_id ---

                 count      mean       std  min  25%  50%  75%  max
max_glu_serum
>200            1485.0  4.816162  1.466337  1.0  5.0  5.0  6.0  6.0
>300            1264.0  4.100475  1.994498  1.0  1.0  5.0  6.0  6.0
Norm            2597.0  4.535618  1.680803  1.0  5.0  5.0  6.0  6.0
not_measured   96420.0  1.886134  1.295472  1.0  1.0  1.0  3.0  8.0

--- discharge_disposition_id ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  5.145455  6.703812  1.0  1.0  3.0  6.0  25.0
>300            1264.0  4.578323  5.906385  1.0  1.0  3.0  6.0  28.0
Norm            2597.0  4.537158  6.138918  1.0  1.0  3.0  6.0  25.0
not_measured   96420.0  3.660185  5.215376  1.0  1.0  1.0  3.0  28.0

--- admission_source_id ---

                 count       mean       std  min   25%   50%   75%   max
max_glu_serum
>200            1485.0  14.435017  4.754695  1.0  17.0  17.0  17.0  17.0
>300            1264.0  12.605222  5.291054  1.0   7.0  17.0  17.0  17.0
Norm            2597.0  14.437813  4.917470  1.0  17.0  17.0  17.0  17.0
not_measured   96420.0   5.297055  3.471441  1.0   1.0   7.0   7.0  25.0

--- time_in_hospital ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  4.742088  3.049261  1.0  2.0  4.0  6.0  14.0
>300            1264.0  5.390032  3.199455  1.0  3.0  5.0  7.0  14.0
Norm            2597.0  3.977667  2.654088  1.0  2.0  3.0  5.0  14.0
not_measured   96420.0  4.388892  2.986389  1.0  2.0  4.0  6.0  14.0

payer_code,BC,CH,CM,CP,DM,FR,HM,MC,MD,MP,OG,OT,PO,SI,SP,UN,WC
max_glu_serum,,,,,,,,,,,,,,,,,
>200,3.010753,0.000000,0.430108,2.150538,0.645161,0.000000,13.333333,73.548387,3.870968,0.000000,0.000000,0.000000,0.000000,0.645161,1.290323,1.075269,0.000000
>300,6.407767,0.194175,0.388350,4.466019,0.776699,0.000000,32.233010,50.097087,2.524272,0.000000,0.000000,0.000000,0.000000,0.194175,0.970874,1.747573,0.000000
Norm,3.747323,0.321199,0.642398,1.820128,0.642398,0.000000,14.132762,71.627409,3.747323,0.000000,0.000000,0.000000,0.000000,1.177730,0.963597,0.963597,0.214133
not_measured,7.673334,0.238271,3.233438,4.166387,0.899389,0.001678,9.923485,52.302168,5.815827,0.132559,1.733338,0.159407,0.993355,0.067119,8.368011,4.069065,0.223169

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,Oncology,Ophthalmology,Orthopedics,Orthopedics-Reconstructive,Osteopath,Otolaryngology,OutreachServices,Pathology,Pediatrics,Pediatrics-AllergyandImmunology,Pediatrics-CriticalCare,Pediatrics-EmergencyMedicine,Pediatrics-Endocrinology,Pediatrics-Hematology-Oncology,Pediatrics-InfectiousDiseases,Pediatrics-Neurology,Pediatrics-Pulmonology,Perinatology,PhysicalMedicineandRehabilitation,PhysicianNotFound,Podiatry,Proctology,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
>200,0.000000,0.000000,0.00000,7.674419,0.000000,0.000000,0.116279,0.000000,0.000000,0.000000,0.000000,34.186047,0.813953,0.000000,0.000000,4.069767,0.000000,0.000000,28.604651,3.255814,0.116279,0.000000,0.000000,0.00000,0.697674,0.000000,0.116279,0.232558,4.883721,0.000000,0.116279,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.674419,0.000000,0.000000,0.000000,0.116279,0.000000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.395349,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.930233
>300,0.000000,0.000000,0.00000,6.055046,0.000000,0.000000,0.000000,0.000000,0.183486,0.000000,0.000000,37.431193,0.917431,0.000000,0.000000,4.403670,0.000000,0.000000,32.477064,5.504587,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.183486,0.000000,3.119266,0.000000,0.550459,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.467890,0.000000,0.000000,0.000000,0.183486,0.000000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.788991,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.733945
Norm,0.000000,0.000000,0.00000,8.294931,0.000000,0.000000,0.000000,0.000000,0.065833,0.000000,0.000000,32.126399,1.382488,0.000000,0.000000,4.015800,0.000000,0.131666,24.226465,3.489138,0.000000,0.000000,0.000000,0.00000,0.394997,0.000000,0.000000,0.197498,6.912442,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.213298,0.000000,0.000000,0.000000,0.065833,0.131666,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.639895,0.131666,0.000000,0.000000,0.065833,0.000000,0.000000,0.000000,0.000000,1.514154
not_measured,0.014317,0.024543,0.03886,10.486164,0.014317,0.012272,0.006136,0.002045,15.468472,0.245434,0.016362,13.200254,1.086045,0.118626,0.167713,0.177940,0.116581,0.071585,28.314892,3.072014,0.413147,0.002045,0.051132,0.03886,1.347841,0.711758,0.073630,2.853169,2.186407,0.079766,0.247479,0.024543,0.03477,0.519502,0.006136,0.17794,0.006136,0.3252,0.008181,0.002045,0.020453,0.051132,0.002045,0.799705,0.022498,0.204528,0.002045,1.552369,0.002045,0.014317,0.206574,1.775305,2.327532,0.1084,0.004091,0.03477,0.002045,0.002045,0.092038,0.200438,1.333524,0.022498,5.669523,0.018408,0.957192,0.016362,0.081811,0.002045,0.222936,1.090136,0.067494,1.329434

--- num_lab_procedures ---

                 count       mean        std  min   25%   50%   75%    max
max_glu_serum
>200            1485.0  28.370370  18.002514  8.0  17.0  23.0  27.0  106.0
>300            1264.0  36.796677  22.386703  1.0  19.0  25.0  55.0  114.0
Norm            2597.0  26.309588  16.672790  8.0  17.0  20.0  26.0  101.0
not_measured   96420.0  43.857125  19.428744  1.0  33.0  45.0  57.0  132.0

--- num_procedures ---

                 count      mean       std  min  25%  50%  75%  max
max_glu_serum
>200            1485.0  0.768350  1.140504  0.0  0.0  0.0  1.0  6.0
>300            1264.0  0.816456  1.234057  0.0  0.0  0.0  1.0  6.0
Norm            2597.0  0.753562  1.098795  0.0  0.0  0.0  1.0  6.0
not_measured   96420.0  1.371178  1.726202  0.0  0.0  1.0  2.0  6.0

--- num_medications ---

                 count       mean       std  min   25%   50%   75%   max
max_glu_serum
>200            1485.0  16.146128  6.983003  1.0  11.0  15.0  20.0  44.0
>300            1264.0  17.218354  7.260983  1.0  12.0  17.0  22.0  45.0
Norm            2597.0  14.049288  6.211901  1.0   9.0  13.0  18.0  43.0
not_measured   96420.0  16.057374  8.192361  1.0  10.0  15.0  20.0  81.0

--- number_outpatient ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  0.668013  1.550874  0.0  0.0  0.0  1.0  35.0
>300            1264.0  0.625000  1.283382  0.0  0.0  0.0  1.0  12.0
Norm            2597.0  0.673469  1.324636  0.0  0.0  0.0  1.0  13.0
not_measured   96420.0  0.353215  1.258644  0.0  0.0  0.0  0.0  42.0

--- number_emergency ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  0.277441  0.727629  0.0  0.0  0.0  0.0   8.0
>300            1264.0  0.462816  1.357147  0.0  0.0  0.0  0.0  25.0
Norm            2597.0  0.269157  0.718686  0.0  0.0  0.0  0.0   8.0
not_measured   96420.0  0.191216  0.930807  0.0  0.0  0.0  0.0  76.0

--- number_inpatient ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  0.688889  1.176553  0.0  0.0  0.0  1.0   8.0
>300            1264.0  1.038766  2.021088  0.0  0.0  0.0  1.0  19.0
Norm            2597.0  0.657682  1.216964  0.0  0.0  0.0  1.0  16.0
not_measured   96420.0  0.628863  1.251531  0.0  0.0  0.0  1.0  21.0

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,170,171,172,173,174,175,179,180,182,183,184,185,187,188,189,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,207,208,210,211,212,214,215,216,217,218,219,220,223,225,226,227,228,229,23,230,233,235,236,237,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,261,262,263,266,27,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,31,310,311,312,314,318,320,322,323,324,325,327,331,332,333,334,335,336,337,338,34,340,341,342,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,36,360,361,362,363,365,366,368,369,370,372,373,374,375,376,377,378,379,38,380,381,382,383,384,385,386,388,389,39,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,461,462,463,464,465,466,47,470,471,473,474,475,477,478,48,480,481,482,483,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,518,519,52,521,522,523,524,526,527,528,529,53,530,531,532,533,534,535,536,537,54,540,541,542,543,550,551,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,58,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,61,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,632,633,634,637,640,641,642,643,644,645,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,671,674,680,681,682,683,684,685,686,690,691,692,693,694,695,696,698,7,70,700,703,704,705,706,707,708,709,710,711,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,745,746,747,75,751,753,756,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,803,804,805,806,807,808,810,812,813,814,815,816,817,82,820,821,822,823,824,825,826,827,831,832,833,834,835,836,837,838,839,84,840,842,843,844,845,846,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,873,875,878,879,88,880,881,882,883,885,886,890,891,892,893,895,897,9,903,904,906,911,913,914,915,916,917,919,920,921,922,923,924,928,933,934,935,936,939,94,941,942,944,945,952,955,957,958,959,962,963,964,965,966,967,968,969,97,970,971,972,973,974,975,976,977,98,980,982,983,986,987,988,989,990,991,992,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
>200,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.00000,0.673401,0.202020,0.067340,0.000000,0.067340,0.000000,0.000000,0.067340,0.471380,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.134680,0.000000,0.202020,0.000000,0.00000,0.067340,0.000000,0.000000,0.000000,0.000000,0.269360,0.336700,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.202020,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.067340,0.269360,0.067340,0.067340,0.269360,0.134680,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.202020,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,1.077441,0.471380,1.952862,0.269360,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,2.356902,0.00000,0.740741,0.000000,0.202020,0.000000,0.000000,0.000000,0.000000,0.269360,0.000000,0.067340,0.067340,0.067340,0.067340,0.269360,0.134680,0.269360,0.134680,0.404040,1.077441,0.067340,0.134680,0.000000,0.000000,0.067340,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.067340,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.067340,0.000000,2.962963,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.067340,0.404040,0.269360,0.202020,0.134680,0.000000,0.000000,4.579125,0.471380,0.000000,0.202020,3.838384,0.808081,0.000000,0.000000,0.067340,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.673401,2.693603,6.936027,0.067340,0.067340,0.134680,0.000000,0.673401,2.356902,1.077441,0.404040,0.067340,0.067340,0.336700,0.000000,0.000000,0.067340,0.202020,0.000000,0.067340,0.134680,0.000000,0.067340,0.000000,0.269360,0.134680,0.067340,0.067340,0.000000,0.269360,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.202020,0.000000,0.000000,0.000000,0.067340,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.202020,0.538721,0.000000,0.000000,6.060606,0.067340,0.000000,0.067340,3.030303,0.000000,0.875421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.424242,0.067340,0.000000,0.404040,0.134680,0.000000,0.000000,0.202020,0.134680,1.818182,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.067340,0.06734,0.000000,0.202020,0.269360,0.336700,0.606061,0.000000,0.000000,0.336700,0.269360,0.067340,0.067340,0.336700,0.000000,0.067340,0.000000,0.067340,0.067340,0.471380,0.336700,0.20202,0.067340,0.269360,0.471380,1.481481,1.279461,0.134680,0.000000,0.000000,0.000000,0.067340,0.404040,0.000000,0.000000,0.134680,0.538721,0.067340,1.144781,0.336700,0.269360,1.144781,0.673401,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.616162,0.000000,0.067340,0.000000,0.269360,0.00000,0.404040,0.067340,0.000000,0.067340,0.067340,0.000000,1.548822,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.00000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.491582,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.067340,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.202020,0.000000,1.279461,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.067340,0.269360,0.000000,0.000000,0.000000,0.202020,0.000000,0.000000,0.000000,0.000000,0.336700,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.00000,0.000000,0.000000,1.818182,0.000000,0.067340,0.000000,0.067340,0.067340,3.569024,0.067340,0.067340,0.202020,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538721,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.087542,0.067340,0.067340,0.134680,0.134680,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.134680,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.875421,0.538721,0.740741,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.202020,0.000000,1.010101,0.134680,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000
>300,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.079114,0.00000,0.000000,0.079114,0.000000,0.079114,0.316456,0.000000,0.000000,0.000000,0.237342,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.158228,0.00000,0.000000,0.000000,0.000000,0.000000,0.079114,0.237342,0.158228,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.870253,0.000000,1.898734,0.316456,2.215190,3.006329,1.186709,2.452532,1.344937,0.237342,1.107595,0.158228,0.079114,0.000000,0.000000,0.00000,0.000000,0.079114,0.158228,0.000000,0.000000,0.000000,0.000000,0.079114,2.136076,0.395570,1.107595,0.474684,0.712025,0.949367,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,2.373418,0.00000,0.158228,0.000000,0.079114,0.000000,0.000000,0.158228,0.000000,0.158228,0.000000,0.158228,0.079114,0.000000,0.000000,0.158228,0.237342,0.000000,0.000000,0.237342,0.237342,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,2.927215,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.158228,0.000000,0.079114,0.079114,0.000000,0.000000,3.639241,0.316456,0.000000,0.158228,1.740506,0.316456,0.000000,0.000000,0.000000,0.158228,0.079114,0.000000,0.158228,0.000000,0.000000,0.395570,1.344937,7.120253,0.000000,0.000000,0.000000,0.000000,0.158228,1.186709,0.712025,0.079114,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.079114,0.000000,0.158228,0.079114,0.000000,0.158228,0.000000,0.237342,0.000000,0.000000,0.000000,0.000000,0.474684,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.079114,0.395570,0.158228,0.000000,0.000000,6.329114,0.000000,0.000000,0.079114,8.227848,0.000000,2.215190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.006329,0.000000,0.000000,0.237342,0.079114,0.000000,0.000000,0.079114,0.158228,2.768987,0.079114,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.079114,0.632911,0.395570,0.237342,0.000000,0.000000,0.474684,0.158228,0.079114,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.079114,0.237342,0.237342,0.395570,0.474684,0.079114,0.079114,0.158228,0.316456,0.000000,0.237342,0.000000,0.000000,0.553797,0.237342,0.158228,0.712025,0.158228,0.158228,2.689873,0.553797,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.870253,0.000000,0.000000,0.000000,0.237342,0.00000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,1.265823,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158228,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,1.898734,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.395570,0.000000,0.000000,0.079114,0.000000,0.000000,0.316456,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.316456,0.000000,0.079114,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.740506,0.000000,0.158228,0.079114,0.079114,0.079114,1.661392,0.237342,0.000000,0.316456,0.079114,0.237342,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.316456,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.712025,0.079114,0.000000,0.158228,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.000000,0.079114,0.000000,0.000000,0.000000,0.158228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.949367,0.158228,0.158228,0.079114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114,0.000000,0.316456,0.395570,0.000000,0.000000,0.000000,0.000000,0.000000,0.079114

diag_2,11,110,111,112,114,115,117,123,130,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,162,163,164,171,172,173,174,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,212,214,215,217,218,220,223,225,226,227,228,232,233,235,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,266,268,269,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,31,310,311,312,314,316,317,318,319,320,322,323,324,325,327,331,332,333,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,360,362,364,365,366,368,369,372,373,374,376,377,378,379,38,380,381,382,383,386,388,389,394,395,396,397,398,40,401,402,403,404,405,41,410,411,412,413,414,415,416,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,446,447,448,451,452,453,454,455,456,457,458,459,46,460,461,462,463,464,465,466,470,472,473,474,475,477,478,480,481,482,483,484,485,486,487,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,517,518,519,52,520,521,522,523,524,527,528,529,53,530,531,532,533,534,535,536,537,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,634,641,642,644,645,646,647,648,649,652,654,656,658,659,66,661,663,664,665,670,674,680,681,682,683,684,685,686,691,692,693,694,695,696,698,7,70,701,702,703,704,705,706,707,709,710,711,712,713,714,715,716,717,718,719,721,722,723,724,725,726,727,728,729,730,731,733,734,736,737,738,741,742,745,746,747,748,75,750,751,752,753,754,755,756,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,806,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,832,833,836,837,840,842,843,844,845,846,847,850,851,852,853,860,861,862,863,864,865,866,867,868,869,870,871,872,873,879,88,880,881,882,883,884,891,892,893,894,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,927,933,934,94,942,944,945,947,948,952,953,955,958,959,96,962,963,965,967,968,969,972,974,975,977,980,987,989,99,990,991,992,994,995,996,997,998,999,E812,E813,E814,E816,E817,E818,E819,E821,E826,E829,E849,E850,E853,E854,E858,E868,E870,E878,E879,E880,E881,E882,E883,E884,E885,E887,E888,E890,E900,E905,E906,E915,E916,E917,E918,E919,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E944,E945,E947,E950,E965,E968,E980,V02,V03,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V23,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
>200,0.000000,0.000000,0.000000,0.202020,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.067340,0.067340,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.067340,0.067340,0.000000,0.067340,0.000000,0.067340,0.202020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.00000,0.134680,0.000000,0.000000,0.000000,0.000000,0.067340,0.336700,0.404040,0.000000,0.000000,0.067340,0.067340,0.000000,0.134680,0.134680,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.13468,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.000000,0.000000,0.000000,4.983165,3.367003,2.626263,0.471380,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.269360,0.000000,0.134680,0.134680,0.067340,0.000000,0.067340,1.010101,0.202020,0.404040,0.269360,0.202020,0.067340,0.000000,0.000000,0.000000,0.000000,0.134680,0.067340,0.202020,0.067340,0.000000,0.067340,0.000000,0.00000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.000000,0.000000,0.067340,8.686869,0.000000,0.067340,0.000000,0.942761,0.067340,0.000000,0.067340,0.269360,1.279461,0.134680,0.336700,0.202020,0.000000,0.000000,0.067340,0.134680,0.000000,0.202020,0.404040,0.134680,0.000000,0.000000,0.000000,0.134680,0.134680,0.000000,0.875421,0.134680,0.538721,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.067340,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.00000,0.202020,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.808081,0.000000,0.000000,0.067340,0.000000,0.134680,0.000000,0.000000,0.00000,0.000000,0.067340,0.000000,0.000000,0.000000,1.481481,0.134680,1.414141,0.000000,0.000000,0.336700,0.336700,2.222222,0.000000,1.346801,2.087542,0.067340,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.673401,0.875421,0.067340,6.060606,9.090909,0.06734,0.000000,0.000000,0.000000,0.336700,0.000000,0.067340,0.000000,0.000000,0.000000,0.134680,0.134680,0.000000,0.067340,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.606061,0.000000,0.000000,0.067340,0.000000,0.202020,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.134680,0.067340,0.000000,0.000000,0.000000,2.020202,0.000000,0.000000,3.569024,0.000000,0.740741,0.067340,0.000000,3.164983,0.06734,0.000000,0.000000,0.000000,0.336700,0.067340,0.000000,1.010101,0.000000,0.000000,0.000000,0.269360,0.000000,0.000000,2.289562,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.134680,0.134680,0.000000,0.000000,0.336700,0.404040,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.202020,0.404040,0.202020,0.067340,0.000000,0.000000,0.134680,0.067340,0.202020,0.000000,0.471380,0.067340,0.067340,0.336700,0.134680,0.202020,0.336700,0.134680,0.000000,0.000000,0.000000,0.000000,1.077441,0.538721,0.00000,0.000000,0.000000,0.134680,0.067340,0.134680,0.000000,0.000000,0.000000,0.000000,4.848485,0.000000,0.06734,0.000000,0.000000,0.000000,0.000000,0.067340,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.212121,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.750842,0.067340,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.067340,0.000000,0.000000,0.000000,0.00000,0.000000,0.067340,0.269360,0.202020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.346801,0.067340,0.000000,0.000000,0.067340,0.471380,0.336700,0.202020,0.538721,0.067340,0.067340,0.067340,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.202020,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.06734,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.471380,0.067340,0.404040,0.404040,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.269360,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.202020,0.000000,0.269360,0.000000,0.000000,0.000000,0.000000,0.06734,0.000000,0.000000,0.06734,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.134680,0.000000,0.000000,0.06734,0.000000,0.000000,0.000000,0.00000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.134680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000,0.000000,0.000000,0.067340,0.000000,0.000000
>300,0.000000,0.000000,0.000000,0.317209,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158604,0.079302,0.079302,0.079302,0.000000,0.000000,0.000000,0.158604,0.555115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.079302,0.000000,0.000000,0.000000,0.000000,0.158604,0.396511,0.237906,0.000000,0.000000,0.000000,0.237906,0.000000,0.079302,0.317209,0.000000,0.237906,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,3.013481,2.061856,5.709754,1.586043,0.000000,0.396511,0.317209,0.317209,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.872324,0.317209,0.158604,0.000000,0.000000,0.079302,0.000000,1.110230,0.079302,0.158604,0.555115,0.951626,0.396511,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158604,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158604,0.000000,0.000000,0.000000,12.450436,0.000000,0.158604,0.000000,0.317209,0.000000,0.000000,0.000000,0.158604,0.951626,0.158604,0.475813,0.158604,0.000000,0.158604,0.317209,0.000000,0.000000,0.158604,0.158604,0.079302,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.713719,0.158604,0.872324,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.079302,0.000000,0.000000,0.000000,0.079302,0.000000,0.00000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.317209,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.237906,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.348136,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.396511,0.000000,0.000000,0.000000,1.189532,0.000000,2.220460,0.000000,0.000000,0.158604,0.317209,0.951626,0.000000,0.555115,1.030928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396511,0.634417,0.079302,2.299762,6.978588,0.00000,0.000000,0.000000,0.000000,0.079302,0.079302,0.000000,0.000000,0.000000,0.000000,0.237906,0.079302,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.317209,0.000000,0.079302,0.317209,0.000000,0.000000,0.079302,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.079302,0.079302,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396511,0.000000,0.000000,0.079302,2.775575,0.000000,0.079302,6.185567,0.000000,1.030928,0.079302,0.000000,2.141158,0.00000,0.000000,0.000000,0.000000,0.872324,0.158604,0.000000,0.396511,0.079302,0.000000,0.000000,0.317209,0.079302,0.000000,1.903251,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.475813,0.000000,0.079302,0.079302,0.000000,0.237906,0.079302,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.158604,0.079302,0.000000,0.000000,0.000000,0.079302,0.475813,0.158604,0.000000,0.079302,0.158604,0.000000,0.000000,0.000000,0.000000,0.237906,0.000000,0.000000,0.317209,0.000000,0.079302,0.793021,0.396511,0.000000,0.000000,0.079302,0.079302,1.586043,1.348136,0.00000,0.000000,0.079302,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.599524,0.079302,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.110230,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396511,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.506741,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.00000,0.000000,0.317209,0.000000,0.158604,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,1.268834,0.158604,0.079302,0.000000,0.000000,0.793021,0.475813,0.079302,0.000000,0.237906,0.000000,0.079302,0.000000,0.079302,0.000000,0.079302,0.000000,0.000000,0.000000,0.713719,0.158604,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.158604,0.237906,0.079302,0.317209,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.000000,0.000000,0.158604,0.000000,0.000000,0.000000,0.000000,0.000000,0.079302,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.317209,0.000000,0.000000,0.000000,0.000000,0.000000,0.158604,0.000000,0.079302,0.158604,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.237906,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,157,158,161,162,163,164,17,170,171,172,173,174,175,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,214,215,216,217,218,220,223,225,226,227,228,230,233,235,236,238,239,240,241,242,243,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,265,266,268,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,310,311,312,313,314,315,317,318,319,323,327,331,332,333,334,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,353,354,355,356,357,358,359,360,361,362,365,365.44,366,368,369,370,372,373,374,376,377,378,379,38,380,381,382,383,384,385,386,387,388,389,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,47,470,472,473,475,477,478,480,481,482,483,484,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,514,515,516,517,518,519,521,522,523,524,525,527,528,529,53,530,531,532,533,534,535,536,537,538,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,607,608,610,611,614,616,617,618,619,620,621,622,623,624,625,626,627,641,642,643,644,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,670,671,674,680,681,682,684,685,686,690,692,693,694,695,696,697,698,7,70,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,741,742,744,745,746,747,75,750,751,752,753,754,755,756,757,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,834,836,837,838,840,841,842,844,845,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,872,873,875,876,877,879,88,880,881,882,883,884,890,891,892,893,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,928,930,933,934,935,94,942,943,944,945,948,951,952,953,955,956,958,959,962,965,966,967,969,970,971,972,980,987,989,991,992,995,996,997,998,999,E812,E813,E815,E816,E817,E818,E819,E822,E825,E826,E828,E849,E850,E852,E853,E854,E855,E858,E861,E864,E865,E870,E876,E878,E879,E880,E881,E882,E883,E884,E885,E886,E887,E888,E892,E894,E900,E901,E904,E905,E906,E912,E915,E916,E917,E919,E920,E922,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E943,E944,E945,E946,E947,E949,E950,E955,E956,E965,E966,E980,E987,V01,V02,V03,V06,V07,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V22,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
>200,0.000000,0.000000,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.136333,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.136333,0.204499,0.272665,0.000000,0.000000,0.000000,0.068166,0.000000,0.136333,0.068166,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.204499,0.000000,0.272665,0.000000,0.000000,11.315610,2.249489,1.772324,0.204499,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.272665,0.272665,0.068166,0.000000,0.408998,0.068166,0.068166,0.068166,0.886162,0.136333,0.681663,0.068166,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.136333,0.340832,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.499659,0.000000,0.136333,0.068166,6.339468,0.000000,0.408998,0.068166,0.477164,0.000000,0.068166,0.000000,0.204499,0.886162,0.136333,0.545331,0.204499,0.000000,0.272665,0.068166,0.068166,0.204499,0.204499,0.613497,0.136333,0.000000,0.000000,0.000000,0.068166,0.408998,0.068166,0.681663,0.204499,0.613497,0.000000,0.000000,0.000000,0.136333,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.136333,0.136333,0.204499,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.068166,0.000000,0.068166,0.000000,0.000000,0.068166,0.068166,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.068166,0.408998,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.408998,0.068166,0.000000,6.612134,0.136333,0.681663,0.068166,0.000000,0.613497,0.000000,0.272665,0.000000,0.408998,2.862986,0.000000,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,2.044990,1.635992,0.340832,5.044308,4.771643,0.136333,0.000000,0.000000,0.000000,0.068166,0.068166,0.136333,0.000000,0.000000,0.204499,0.068166,0.068166,0.000000,0.340832,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.204499,0.000000,0.272665,0.000000,0.000000,0.204499,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.136333,0.204499,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.499659,0.000000,0.000000,0.068166,0.886162,0.068166,0.408998,0.000000,0.000000,2.453988,0.000000,0.000000,0.000000,0.068166,0.204499,0.000000,0.000000,0.340832,0.068166,0.000000,0.204499,0.000000,0.000000,1.022495,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.477164,0.068166,0.068166,0.000000,0.000000,0.749830,0.204499,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.204499,0.000000,0.000000,0.000000,0.272665,0.408998,0.136333,0.204499,0.000000,0.000000,0.136333,0.000000,0.068166,0.000000,0.068166,0.681663,0.000000,0.000000,0.068166,0.068166,0.136333,0.272665,0.136333,0.000000,0.000000,0.136333,0.068166,0.408998,1.635992,0.886162,0.000000,0.000000,0.068166,0.068166,0.068166,0.340832,0.000000,0.000000,0.068166,0.000000,0.000000,3.135651,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.00000,0.000000,0.068166,0.000000,0.068166,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.681663,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.408998,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.363327,0.000000,0.000000,0.136333,0.000000,0.000000,0.000000,0.068166,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.068166,0.000000,0.204499,0.068166,0.000000,0.000000,0.136333,0.000000,0.204499,0.204499,0.000000,0.477164,0.000000,0.000000,0.000000,0.068166,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.363327,0.136333,0.068166,0.000000,0.068166,0.749830,0.545331,0.408998,0.204499,0.068166,0.000000,0.204499,0.000000,0.068166,0.000000,0.068166,0.000000,0.000000,0.000000,0.136333,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.272665,0.136333,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.204499,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.136333,0.204499,0.000000,0.000000,0.000000,0.000000,0.272665,0.000000,0.000000,0.408998,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.136333,0.068166,0.068166,0.068166,0.136333,0.068166,0.000000,0.000000,0.068166,0.000000,0.000000,0.204499,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.136333,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.136333,0.000000,0.136333,0.000000,0.000000,0.136333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.204499,0.000000,0.000000,0.681663,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068166,0.000000
>300,0.000000,0.080775,0.000000,0.323102,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.646204,0.242326,0.000000,0.000000,0.000000,0.080775,0.161551,0.080775,0.000000,0.080775,0.323102,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.161551,0.000000,0.484653,0.000000,0.000000,5.411955,1.211632,4.200323,1.292407,0.080775,0.080775,0.080775,0.000000,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,0.323102,0.726979,0.161551,0.323102,0.000000,0.323102,0.000000,0.161551,1.373183,0.080775,0.807754,0.080775,0.161551,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.161551,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.323102,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,1.534733,0.080775,0.080775,0.161551,11.147011,0.000000,1.211632,0.000000,0.323102,0.000000,0.000000,0.000000,0.323102,1.292407,0.000000,0.403877,0.161551,0.000000,0.161551,0.000000,0.000000,0.000000,0.323102,0.646204,0.080775,0.000000,0.000000,0.000000,0.000000,0.403877,0.000000,0.646204,0.323102,0.807754,0.000000,0.080775,0.000000,0.000000,0.000000,0.484653,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.323102,0.161551,0.000000,0.000000,0.080775,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.080775,0.000000,0.000000,0.000000,0.161551,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.403877,0.00000,0.080775,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.403877,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.323102,0.000000,0.000000,4.846527,0.161551,1.453958,0.080775,0.000000,0.807754,0.242326,0.242326,0.161551,0.323102,3.311793,0.080775,0.161551,0.000000,0.000000,0.000000,0.000000,0.161551,0.565428,0.888530,0.242326,2.504039,4.281099,0.000000,0.000000,0.000000,0.000000,0.161551,0.000000,0.080775,0.080775,0.080775,0.080775,0.000000,0.000000,0.000000,0.161551,0.080775,0.000000,0.161551,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.161551,0.080775,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.080775,0.000000,0.080775,0.000000,0.000000,0.000000,1.453958,0.161551,0.000000,0.080775,1.130856,0.080775,0.565428,0.000000,0.000000,1.696284,0.000000,0.000000,0.000000,0.000000,0.565428,0.000000,0.000000,0.161551,0.000000,0.000000,0.000000,0.000000,0.000000,1.696284,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.807754,0.080775,0.000000,0.080775,0.000000,0.726979,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.000000,0.000000,0.000000,0.323102,0.161551,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.646204,0.161551,0.161551,0.080775,0.000000,0.161551,0.403877,0.242326,0.000000,0.000000,0.161551,0.000000,0.565428,1.938611,1.696284,0.000000,0.000000,0.080775,0.080775,0.080775,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,1.938611,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.807754,0.000000,0.080775,0.080775,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.242326,0.080775,0.000000,0.000000,0.080775,0.000000,0.000000,1.211632,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.161551,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.000000,0.000000,0.000000,0.080775,0.080775,0.000000,0.403877,0.000000,0.000000,0.000000,0.000000,0.00000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,1.534733,0.000000,0.161551,0.080775,0.242326,0.646204,0.403877,0.080775,0.242326,0.323102,0.161551,0.242326,0.000000,0.080775,0.000000,0.323102,0.000000,0.000000,0.000000,0.888530,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.242326,0.161551,0.080775,0.161551,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.080775,0.080775,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.242326,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.323102,0.161551,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.161551,0.080775,0.000000,0.000000,0.000000,0.000000,0.323102,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.000000,1.050081,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000,0.565428,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080775,0.000000

--- number_diagnoses ---

                 count      mean       std  min  25%  50%  75%   max
max_glu_serum
>200            1485.0  7.027609  1.855252  2.0  6.0  8.0  9.0   9.0
>300            1264.0  7.127373  1.950799  1.0  6.0  8.0  9.0   9.0
Norm            2597.0  6.911821  1.859139  2.0  6.0  7.0  9.0   9.0
not_measured   96420.0  7.446318  1.933672  1.0  6.0  8.0  9.0  16.0

A1Cresult             >7         >8       Norm
max_glu_serum
>200           25.352113  50.704225  23.943662
>300           11.627907  86.821705   1.550388
Norm           30.612245  29.591837  39.795918
not_measured   22.422249  48.080144  29.497608

metformin          Down         No     Steady        Up
max_glu_serum
>200           0.269360  84.646465  14.074074  1.010101
>300           0.395570  85.284810  12.420886  1.898734
Norm           0.385060  85.829804  13.554101  0.231036
not_measured   0.576644  80.080896  18.282514  1.059946

repaglinide        Down         No    Steady        Up
max_glu_serum
>200           0.000000  99.595960  0.404040  0.000000
>300           0.000000  98.892405  1.107595  0.000000
Norm           0.000000  99.614940  0.346554  0.038506
not_measured   0.046671  98.434972  1.405310  0.113047

nateglinide        Down          No    Steady        Up
max_glu_serum
>200           0.000000   99.865320  0.134680  0.000000
>300           0.000000  100.000000  0.000000  0.000000
Norm           0.000000  100.000000  0.000000  0.000000
not_measured   0.011408   99.272972  0.690728  0.024891

chlorpropamide      Down         No    Steady        Up
max_glu_serum
>200            0.000000  99.865320  0.134680  0.000000
>300            0.000000  99.841772  0.158228  0.000000
Norm            0.000000  99.884482  0.115518  0.000000
not_measured    0.001037  99.918067  0.074673  0.006223

glimepiride        Down         No    Steady        Up
max_glu_serum
>200           0.067340  98.181818  1.548822  0.202020
>300           0.000000  97.547468  2.294304  0.158228
Norm           0.115518  98.267231  1.540239  0.077012
not_measured   0.197055  94.723086  4.747978  0.331881

acetohexamide          No    Steady
max_glu_serum
>200           100.000000  0.000000
>300           100.000000  0.000000
Norm           100.000000  0.000000
not_measured    99.998963  0.001037

glipizide          Down         No     Steady        Up
max_glu_serum
>200           0.336700  87.272727  11.245791  1.144781
>300           0.553797  86.313291  10.996835  2.136076
Norm           0.693107  86.946477  12.129380  0.231036
not_measured   0.549678  87.570006  11.133582  0.746733

glyburide          Down         No     Steady        Up
max_glu_serum
>200           0.875421  87.340067  10.841751  0.942761
>300           0.712025  90.585443   7.436709  1.265823
Norm           0.577590  89.872930   9.010397  0.539084
not_measured   0.546567  89.545737   9.111180  0.796515

tolbutamide            No    Steady
max_glu_serum
>200            99.865320  0.134680
>300           100.000000  0.000000
Norm            99.884482  0.115518
not_measured    99.981332  0.018668

pioglitazone       Down         No    Steady        Up
max_glu_serum
>200           0.067340  94.478114  5.117845  0.336700
>300           0.316456  94.462025  4.905063  0.316456
Norm           0.115518  95.109742  4.697728  0.077012
not_measured   0.114084  92.689276  6.965360  0.231280

rosiglitazone      Down         No    Steady        Up
max_glu_serum
>200           0.067340  93.333333  6.329966  0.269360
>300           0.079114  95.094937  4.509494  0.316456
Norm           0.077012  94.301117  5.583365  0.038506
not_measured   0.086082  93.719145  6.019498  0.175275

acarbose           Down         No    Steady        Up
max_glu_serum
>200           0.000000  99.663300  0.336700  0.000000
>300           0.000000  99.367089  0.553797  0.079114
Norm           0.000000  99.807470  0.192530  0.000000
not_measured   0.003111  99.699233  0.288322  0.009334

miglitol           Down          No    Steady        Up
max_glu_serum
>200           0.000000  100.000000  0.000000  0.000000
>300           0.000000  100.000000  0.000000  0.000000
Norm           0.000000  100.000000  0.000000  0.000000
not_measured   0.005186   99.960589  0.032151  0.002074

troglitazone           No    Steady
max_glu_serum
>200           100.000000  0.000000
>300           100.000000  0.000000
Norm           100.000000  0.000000
not_measured    99.996889  0.003111

tolazamide             No    Steady        Up
max_glu_serum
>200            99.932660  0.067340  0.000000
>300           100.000000  0.000000  0.000000
Norm            99.961494  0.038506  0.000000
not_measured    99.961626  0.037337  0.001037

examide           No
max_glu_serum
>200           100.0
>300           100.0
Norm           100.0
not_measured   100.0

citoglipton       No
max_glu_serum
>200           100.0
>300           100.0
Norm           100.0
not_measured   100.0

insulin             Down         No     Steady         Up
max_glu_serum
>200           18.720539  37.037037  32.996633  11.245791
>300           25.395570  31.803797  23.575949  19.224684
Norm            9.973046  61.648055  22.834039   5.544859
not_measured   11.781788  46.494503  30.562124  11.161585

glyburide-metformin      Down          No    Steady        Up
max_glu_serum
>200                 0.000000  100.000000  0.000000  0.000000
>300                 0.000000   99.841772  0.158228  0.000000
Norm                 0.000000  100.000000  0.000000  0.000000
not_measured         0.006223   99.269861  0.715619  0.008297

glipizide-metformin          No    Steady
max_glu_serum
>200                 100.000000  0.000000
>300                 100.000000  0.000000
Norm                 100.000000  0.000000
not_measured          99.986517  0.013483

glimepiride-pioglitazone          No    Steady
max_glu_serum
>200                      100.000000  0.000000
>300                      100.000000  0.000000
Norm                      100.000000  0.000000
not_measured               99.998963  0.001037

metformin-rosiglitazone          No    Steady
max_glu_serum
>200                     100.000000  0.000000
>300                     100.000000  0.000000
Norm                     100.000000  0.000000
not_measured              99.997926  0.002074

metformin-pioglitazone          No    Steady
max_glu_serum
>200                    100.000000  0.000000
>300                    100.000000  0.000000
Norm                    100.000000  0.000000
not_measured             99.998963  0.001037

change                Ch         No
max_glu_serum
>200           51.245791  48.754209
>300           60.759494  39.240506
Norm           31.882942  68.117058
not_measured   46.311968  53.688032

diabetesMed           No        Yes
max_glu_serum
>200           18.653199  81.346801
>300           17.721519  82.278481
Norm           35.117443  64.882557
not_measured   22.806472  77.193528

readmitted           <30        >30         NO
max_glu_serum
>200           12.457912  35.690236  51.851852
>300           14.319620  41.218354  44.462025
Norm           11.359261  34.077782  54.562957
not_measured   11.093134  34.856876  54.049990

admission_type,Elective,Emergency,Newborn,Not Available,Not Mapped,Trauma Center,Urgent
max_glu_serum,,,,,,,
>200,0.097561,14.243902,0.000000,80.878049,0.000000,0.000000,4.780488
>300,0.641026,35.683761,0.000000,59.508547,0.000000,0.000000,4.166667
Norm,0.844773,19.746568,0.000000,72.703273,0.000000,0.000000,6.705385
not_measured,20.347657,57.369899,0.010797,2.183114,0.345498,0.022673,19.720363

discharge_disposition,Admitted as an inpatient to this hospital,Discharged to home,Discharged/transferred to ICF,Discharged/transferred to SNF,Discharged/transferred to a federal health care facility.,Discharged/transferred to a long term care hospital.,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.,Discharged/transferred to another rehab fac including rehab units of a hospital .,Discharged/transferred to another short term hospital,Discharged/transferred to another type of inpatient care institution,Discharged/transferred to home under care of Home IV provider,Discharged/transferred to home with home health service,Discharged/transferred within this institution to Medicare approved swing bed,Discharged/transferred/referred another institution for outpatient services,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital,Discharged/transferred/referred to this institution for outpatient services,Expired,"Expired at home. Medicaid only, hospice.","Expired in a medical facility. Medicaid only, hospice.",Hospice / home,Hospice / medical facility,Left AMA,Neonate discharged to another hospital for neonatal aftercare,Not Mapped,Still patient or expected to return for outpatient services
max_glu_serum,,,,,,,,,,,,,,,,,,,,,,,,,
>200,0.000000,35.892256,0.067340,27.609428,0.000000,0.067340,0.000000,0.673401,4.915825,1.548822,0.134680,15.353535,0.00000,0.134680,0.000000,0.202020,3.030303,0.000000,0.000000,0.269360,1.144781,0.606061,0.202020,8.148148,0.000000
>300,0.000000,42.642405,0.237342,21.360759,0.000000,0.000000,0.000000,0.474684,3.639241,1.661392,0.158228,17.088608,0.00000,0.079114,0.158228,0.237342,4.193038,0.000000,0.000000,0.158228,1.661392,0.949367,0.000000,5.300633,0.000000
Norm,0.000000,41.701964,0.231036,25.067385,0.000000,0.077012,0.000000,0.616095,3.388525,1.925298,0.115518,17.096650,0.00000,0.231036,0.000000,0.269542,0.885637,0.000000,0.038506,0.154024,0.924143,0.770119,0.077012,6.430497,0.000000
not_measured,0.022647,62.633049,0.868121,13.612786,0.005392,0.441070,0.051764,2.114765,2.071628,1.175468,0.108920,12.956033,0.06794,0.002157,0.147742,0.001078,1.640264,0.008627,0.001078,0.419502,0.334307,0.627635,0.001078,0.683713,0.003235

admmission_source,Clinic Referral,Court/Law Enforcement,Emergency Room,Extramural Birth,HMO Referral,Normal Delivery,Not Available,Not Mapped,Physician Referral,Sick Baby,Transfer from Ambulatory Surgery Center,Transfer from a Skilled Nursing Facility (SNF),Transfer from a hospital,Transfer from another health care facility,Transfer from critial access hospital,Transfer from hospital inpt/same fac reslt in a sep claim
max_glu_serum,,,,,,,,,,,,,,,,
>200,2.011494,0.000000,83.908046,0.000000,0.000000,0.000000,0.000000,0.000000,14.080460,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
>300,0.378072,0.000000,91.493384,0.000000,0.000000,0.000000,0.000000,0.000000,7.939509,0.000000,0.000000,0.000000,0.189036,0.000000,0.000000,0.000000
Norm,2.061856,0.000000,75.773196,0.000000,0.000000,0.000000,0.000000,0.000000,22.164948,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
not_measured,1.157967,0.017108,60.172572,0.002138,0.199944,0.002138,0.133653,0.172145,31.376302,0.001069,0.002138,0.914184,3.406539,2.420717,0.008554,0.012831

Posmatranjem promenljive max_glu_serum, ukljucujuci i kategoriju not measured, mogu se uociti odredjeni obrasci u odnosu na druge atribute. Ova promenljiva pruza informaciju o tome da li su kod pacijenta utvrdjene promene nivoa glukoze u serumu, kao i o kategoriji izmerene vrednosti. Uocava se da pacijenti sa normalnim nivoom max_glu_serum najcesce pripadaju kategoriji pacijenata koji nisu ponovo hospitalizovani.

In [44]:
table_with_missing = pd.crosstab(data["max_glu_serum"],data["readmitted"])
chi2_with, p_value_with, dof, expected = chi2_contingency(table_with_missing)
print(f"chi2={chi2_with}, p_value={p_value_with}, dof= {dof},\n expected= {expected}")

chi2=51.92209834623324, p_value=1.9333043719858424e-09, dof= 6,
 expected= [[  165.7247509    518.68330287   800.59194623]
 [  141.06133679   441.49205039   681.44661282]
 [  289.82301555   907.08453708  1400.09244738]
 [10760.39089676 33677.74010966 51981.86899357]]

Kako bi se proverilo da li su uoceni obrasci izmedju promenljivih max_glu_serum i readmitted statisticki znacajni, primenjen je hi-kvadrat test nezavisnosti. U test je ukljucena i kategorija not measured, buduci da ona predstavlja informaciju o tome da vrednost max_glu_serum kod pacijenta nije bila izmerena. Dobijena je vrednost hi-kvadrat statistike od 51,92 uz 6 stepeni slobode i p-vrednost 1,93 x 10^-9. Kako je p-vrednost manja od nivoa znacajnosti od 0,05, odbacuje se nulta hipoteza o nezavisnosti promenljivih. Na osnovu toga moze se zakljuciti da postoji statisticki znacajna povezanost izmedju promenljivih max_glu_serum i readmitted.

In [45]:
crosstab_without_missing = pd.crosstab(data[data["max_glu_serum"]!="not_measured"]["max_glu_serum"],
                                 data[data["max_glu_serum"]!="not_measured"]["readmitted"], normalize="index"  )*100
print(crosstab_without_missing)
table_without_missing = pd.crosstab(data[data["max_glu_serum"]!="not_measured"]["max_glu_serum"],
                                 data[data["max_glu_serum"]!="not_measured"]["readmitted"])

readmitted           <30        >30         NO
max_glu_serum
>200           12.457912  35.690236  51.851852
>300           14.319620  41.218354  44.462025
Norm           11.359261  34.077782  54.562957

In [46]:
chi2_without, p_value_without, dof, expected = chi2_contingency(table_without_missing)
print(f"chi2={chi2_without}, p_value={p_value_without}, dof= {dof},\n expected= {expected}")

chi2=35.11008068370349, p_value=4.40965642294135e-07, dof= 4,
 expected= [[ 183.61111111  537.77777778  763.61111111]
 [ 156.28582117  457.74485597  649.96932286]
 [ 321.10306771  940.47736626 1335.41956603]]

Posmatranjem raspodele pacijenata prema kategorijama max_glu_serum i readmitted uocava se da pacijenti sa normalnim nivoom glukoze imaju najveci udeo pacijenata koji nisu ponovo hospitalizovani, sa 54,56%. Kod pacijenata sa vrednostima vecim od 200 ovaj udeo iznosi 51,85%, dok kod pacijenata sa vrednostima vecim od 300 iznosi 44,46%. Takodje, u kategoriji >300 uocava se veci udeo ponovne hospitalizacije u periodu duzem od 30 dana, koji iznosi 41,22%.

In [47]:
n_with = table_with_missing.sum().sum()
r_with, k_with = table_with_missing.shape

cramers_v_with = (chi2_with / (n_with * min(r_with - 1, k_with - 1))) ** 0.5
n_without = table_without_missing.sum().sum()
r_without, k_without = table_without_missing.shape

cramers_v_without = (chi2_without / (n_without * min(r_without - 1, k_without - 1))) ** 0.5
print(f"With not_measured: Cramer's V = {cramers_v_with}")
print(f"Without not_measured: Cramer's V = {cramers_v_without}")

With not_measured: Cramer's V = 0.015972017141724526
Without not_measured: Cramer's V = 0.05730419799383266

Kako bi se dodatno ispitala jacina povezanosti izmedju promenljivih max_glu_serum i readmitted, izracunata je Cramer's V statistika. Kada je u analizu ukljucena kategorija not measured, dobijena vrednost Cramer's V iznosi 0,016. Kada se kategorija not measured izostavi, vrednost Cramer's V iznosi 0,057.

Dobijene vrednosti ukazuju da je povezanost izmedju promenljivih max_glu_serum i readmitted veoma slaba, iako je hi-kvadrat test pokazao da je ona statisticki znacajna. To pokazuje da statisticka znacajnost povezanosti ne podrazumeva i njenu veliku prakticnu jacinu. Uklanjanjem kategorije not measured vrednost Cramer's V raste, ali povezanost i dalje ostaje veoma slaba.

Na osnovu sprovedene analize, promenljiva max_glu_serum se za sada zadrzava u skupu podataka. Iako je jacina povezanosti sa promenljivom readmitted veoma slaba, hi-kvadrat test je pokazao statisticki znacajnu povezanost, a deskriptivnom analizom su uoceni odredjeni obrasci izmedju kategorija max_glu_serum i ponovne hospitalizacije. Zbog toga se u ovoj fazi promenljiva ne uklanja, vec se ostavlja za dalju analizu i procenu njenog znacaja u procesu izgradnje modela.

In [48]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,...,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,admission_type,discharge_disposition,admmission_source
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN,Not Mapped,Physician Referral
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
6,55842,84259809,Caucasian,Male,[60-70),3,1,2,4,NaN,NaN,70,1,21,0,0,0,414,411,V45,7,not_measured,NaN,Steady,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
7,63768,114882984,Caucasian,Male,[70-80),1,1,7,5,NaN,NaN,73,0,12,0,0,0,428,492,250,8,not_measured,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
8,12522,48330783,Caucasian,Female,[80-90),2,1,4,13,NaN,NaN,68,2,28,0,0,0,398,427,38,8,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
9,15738,63555939,Caucasian,Female,[90-100),3,3,4,12,NaN,InternalMedicine,33,3,18,0,0,0,434,198,486,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
10,28236,89869032,AfricanAmerican,Female,[40-50),1,1,7,9,NaN,NaN,47,2,17,0,0,0,250.7,403,996,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
11,36900,77391171,AfricanAmerican,Male,[60-70),2,1,4,7,NaN,NaN,62,0,11,0,0,0,157,288,197,7,not_measured,NaN,No,No,...,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Urgent,Discharged to home,Transfer from a hospital
12,40926,85504905,Caucasian,Female,[40-50),1,3,7,7,NaN,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,not_measured,NaN,Steady,Up,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged/transferred to SNF,Emergency Room
13,42570,77586282,Caucasian,Male,[80-90),1,6,7,10,NaN,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
14,62256,49726791,AfricanAmerican,Female,[60-70),3,1,2,1,NaN,NaN,49,5,2,0,0,0,518,998,627,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Elective,Discharged to home,Clinic Referral
15,73578,86328819,AfricanAmerican,Male,[60-70),1,3,7,12,NaN,NaN,75,5,13,0,0,0,999,507,996,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
16,77076,92519352,AfricanAmerican,Male,[50-60),1,1,7,4,NaN,NaN,45,4,17,0,0,0,410,411,414,8,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30,Emergency,Discharged to home,Emergency Room
17,84222,108662661,Caucasian,Female,[50-60),1,1,7,3,NaN,Cardiology,29,0,11,0,0,0,682,174,250,3,not_measured,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
18,89682,107389323,AfricanAmerican,Male,[70-80),1,1,7,5,NaN,NaN,35,5,23,0,0,0,402,425,416,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
19,148530,69422211,NaN,Male,[70-80),3,6,2,6,NaN,NaN,42,2,23,0,0,0,737,427,714,8,not_measured,NaN,No,No,...,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to home with home healt...,Clinic Referral
20,150006,22864131,NaN,Female,[50-60),2,1,4,2,NaN,NaN,66,1,19,0,0,0,410,427,428,7,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
21,150048,21239181,NaN,Male,[60-70),2,1,4,2,NaN,NaN,36,2,11,0,0,0,572,456,427,6,not_measured,NaN,Steady,No,...,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged to home,Transfer from a hospital
22,182796,63000108,AfricanAmerican,Female,[70-80),2,1,4,2,NaN,NaN,47,0,12,0,0,0,410,401,582,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Urgent,Discharged to home,Transfer from a hospital
23,183930,107400762,Caucasian,Female,[80-90),2,6,1,11,NaN,NaN,42,2,19,0,0,0,V57,715,V43,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,Urgent,Discharged/transferred to home with home healt...,Physician Referral
24,216156,62718876,AfricanAmerican,Female,[70-80),3,1,2,3,NaN,NaN,19,4,18,0,0,0,189,496,427,6,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
25,221634,21861756,Other,Female,[50-60),1,1,7,1,NaN,NaN,33,0,7,0,0,0,786,401,250,3,not_measured,NaN,Steady,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Emergency,Discharged to home,Emergency Room
26,236316,40523301,Caucasian,Male,[80-90),1,3,7,6,NaN,Cardiology,64,3,18,0,0,0,427,428,414,7,not_measured,>7,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to SNF,Emergency Room
27,248916,115196778,Caucasian,Female,[50-60),1,1,1,2,NaN,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Physician Referral
28,250872,41606064,Caucasian,Male,[20-30),2,1,2,10,NaN,NaN,53,0,20,0,0,0,277,250.02,263,6,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Clinic Referral
29,252822,18196434,Caucasian,Female,[80-90),1,2,7,5,NaN,Cardiology,52,0,14,0,0,0,428,410,414,8,not_measured,NaN,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
30,253380,56480238,AfricanAmerican,Female,[60-70),1,1,7,6,NaN,NaN,87,0,18,0,0,0,584,496,250.42,9,not_measured,NaN,No,No,...,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged to home,Emergency Room
31,253722,96664626,AfricanAmerican,Male,[70-80),1,5,7,1,NaN,NaN,53,0,10,0,0,0,462,250.01,276,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another type of inpa...,Emergency Room
32,260166,80845353,Caucasian,Female,[70-80),1,1,7,6,NaN,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Emergency,Discharged to home,Emergency Room
33,293058,114715242,Caucasian,Male,[60-70),2,6,2,5,NaN,NaN,37,0,18,0,0,0,473,996,482,8,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged/transferred to home with home healt...,Clinic Referral
34,293118,3327282,Caucasian,Female,[70-80),2,11,2,5,NaN,NaN,46,2,20,0,0,0,428,585,414,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,Urgent,Expired,Clinic Referral
35,325848,63023292,Caucasian,Female,[60-70),1,1,7,2,NaN,Cardiology,41,0,11,0,0,0,411,250.01,401,6,not_measured,NaN,No,No,...,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
36,325866,98427861,Caucasian,Female,[70-80),3,1,2,3,NaN,NaN,33,1,8,0,0,0,174,135,250,5,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
37,326028,112002975,Caucasian,Female,[60-70),1,1,7,4,NaN,NaN,33,0,12,0,0,0,486,244,250,3,not_measured,NaN,Steady,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
38,358776,101002446,Caucasian,Male,[70-80),1,6,7,7,NaN,NaN,47,2,22,0,0,0,998,41,414,8,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Emergency,Discharged/transferred to home with home healt...,Emergency Room
39,377268,104672268,Caucasian,Male,[50-60),2,1,2,1,NaN,NaN,44,1,15,0,0,0,996,403,250.41,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
40,383430,80588529,Caucasian,Female,[70-80),1,2,7,1,NaN,Cardiology,28,0,15,0,0,0,414,411,250.01,4,not_measured,NaN,Steady,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged/transferred to another short term h...,Emergency Room
41,419304,99715041,Caucasian,Male,[40-50),2,1,2,7,NaN,NaN,36,2,9,0,0,0,511,571,585,5,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,Urgent,Discharged to home,Clinic Referral
42,421194,96435585,Caucasian,Female,[70-80),2,1,1,13,NaN,NaN,48,2,18,0,0,1,V57,276,781,8,not_measured,NaN,Steady,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Urgent,Discharged to home,Physician Referral
43,449142,66274866,Caucasian,Male,[50-60),1,1,7,3,NaN,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,not_measured,NaN,Steady,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30,Emergency,Discharged to home,Emergency Room
44,450210,80177094,Caucasian,Female,[80-90),1,11,7,7,NaN,NaN,72,1,27,0,0,0,432,997,427,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Emergency,Expired,Emergency Room
45,464994,106936875,Caucasian,Female,[40-50),3,1,2,2,NaN,NaN,10,3,8,0,0,0,626,250.01,998,5,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO,Elective,Discharged to home,Clinic Referral
46,486156,86240259,Caucasian,Female,[70-80),3,5,4,9,NaN,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,not_measured,NaN,No,No,...,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30,Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital
47,498030,51838164,Caucasian,Male,[70-80),3,3,4,9,NaN,NaN,2,0,12,0,0,1,295,599,250,3,not_measured,NaN,Up,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged/transferred to SNF,Transfer from a hospital
48,537834,90097839,Caucasian,Male,[50-60),3,1,2,6,NaN,NaN,65,5,19,0,0,0,414,424,428,9,not_measured,NaN,No,No,...,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,Elective,Discharged to home,Clinic Referral
49,544194,34997814,Caucasian,Male,[60-70),2,6,4,11,NaN,NaN,67,2,25,0,0,0,428,491,427,9,not_measured,NaN,No,No,...,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital

Number of rows:101766
Number of columns:52
                         Data type:  Missing values:  Percentage of na:  \
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2273           2.233555
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id             int64                0           0.000000
discharge_disposition_id      int64                0           0.000000
admission_source_id           int64                0           0.000000
time_in_hospital              int64                0           0.000000
payer_code                   object            40256          39.557416
medical_specialty            object            49949          49.082208
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               21           0.020636
diag_2                       object              358           0.351787
diag_3                       object             1423           1.398306
number_diagnoses              int64                0           0.000000
max_glu_serum                object                0           0.000000
A1Cresult                    object            84748          83.277322
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000
admission_type               object             5291           5.199182
discharge_disposition        object             3691           3.626948
admmission_source            object             6781           6.663326

                          Value count:
encounter_id                    101766
patient_nbr                      71518
race                                 5
gender                               3
age                                 10
admission_type_id                    8
discharge_disposition_id            26
admission_source_id                 17
time_in_hospital                    14
payer_code                          17
medical_specialty                   72
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             716
diag_2                             748
diag_3                             789
number_diagnoses                    16
max_glu_serum                        4
A1Cresult                            3
metformin                            4
repaglinide                          4
nateglinide                          4
chlorpropamide                       4
glimepiride                          4
acetohexamide                        2
glipizide                            4
glyburide                            4
tolbutamide                          2
pioglitazone                         4
rosiglitazone                        4
acarbose                             4
miglitol                             4
troglitazone                         2
tolazamide                           3
examide                              1
citoglipton                          1
insulin                              4
glyburide-metformin                  4
glipizide-metformin                  2
glimepiride-pioglitazone             2
metformin-rosiglitazone              2
metformin-pioglitazone               2
change                               2
diabetesMed                          2
readmitted                           3
admission_type                       7
discharge_disposition               25
admmission_source                   16

In [49]:
for col in data[["admission_type","discharge_disposition","admmission_source"]].columns:
     data.loc[data[col].isna(), col] = "Missing"

In [50]:
data["admission_type_id"] = data["admission_type"]
data["discharge_disposition_id"] = data["discharge_disposition"]
data["admission_source_id"] = data["admmission_source"]

In [51]:
data.drop(data[["admission_type","discharge_disposition","admmission_source"]].columns, axis= 1, inplace = True)

Vrednosti NULL u atributima admission_type, discharge_disposition i admmission_source pretvorene su u nedostajuce vrednosti, posto za njih nije bilo dostupno konkretno znacenje tipa prijema. Pri tome su kategorije Unknown, Not Mapped i Not Available zadrzane odvojeno, jer predstavljaju zasebne vrednosti u mapping tabeli. Nedostajuce vrednosti su zatim oznacene kao Missing, cime su zadrzani svi redovi u skupu podataka.

In [52]:
data["payer_code"].describe()

count     61510
unique       17
top          MC
freq      32439
Name: payer_code, dtype: object

In [53]:
data.drop(columns="payer_code", inplace=True)

Atribut payer_code je uklonjen iz skupa podataka zbog visokog udela nedostajucih vrednosti, koji iznosi oko 40%. Imputacija nedostajucih vrednosti najcescom kategorijom ne bi bila opravdana, jer bi se veliki broj nepoznatih vrednosti svrstao u kategoriju MC, koja je najzastupljenija u atributu, bez osnova da se pretpostavi da su te vrednosti zaista pripadale toj kategoriji. Dodatno, atribut opisuje nacin finansiranja zdravstvene usluge, a ne direktnu karakteristiku zdravstvenog stanja ili toka hospitalizacije, zbog cega je procenjeno da njegova potencijalna korist za analizu readmisije nije dovoljna da opravda zadrzavanje atributa sa tolikim udelom nedostajucih podataka.

In [54]:
data["A1Cresult"] = data["A1Cresult"].fillna("Not measured")

Atribut A1Cresult je zadrzan jer predstavlja rezultat jednog od dva laboratorijska merenja dostupna u skupu podataka, pored atributa max_glu_serum. Iako su tokom hospitalizacije pacijentima obavljane brojne laboratorijske procedure, skup podataka ne sadrzi rezultate svih izvedenih analiza, vec su od pojedinacnih laboratorijskih rezultata dostupni upravo HbA1c i maksimalna vrednost glukoze u serumu. S obzirom na to da je analiza usmerena na pacijente sa dijabetesom i njihovu readmisiju, rezultat HbA1c predstavlja relevantan atribut za dalju analizu. Nedostajuce vrednosti su zato izdvojene u posebnu kategoriju Not measured, cime je sacuvana informacija da HbA1c merenje nije evidentirano.

In [55]:
data["medical_specialty"] = data["medical_specialty"].fillna("Missing")

Atribut medical_specialty je zadrzan jer predstavlja specijalnost lekara ukljucenog u hospitalizaciju i moze pruziti informaciju o vrsti i slozenosti zdravstvenog stanja pacijenta, sto ga cini potencijalno relevantnim za analizu readmisije. Zbog visokog udela nedostajucih vrednosti, one su izdvojene u posebnu kategoriju Missing, cime je izbegnuto proizvoljno pripisivanje konkretne medicinske specijalnosti.

In [56]:
data["discharge_disposition_id"].value_counts()

discharge_disposition_id
Discharged to home                                                                                           60234
Discharged/transferred to SNF                                                                                13954
Discharged/transferred to home with home health service                                                      12902
Missing                                                                                                       3691
Discharged/transferred to another short term hospital                                                         2128
Discharged/transferred to another rehab fac including rehab units of a hospital .                             1993
Expired                                                                                                       1642
Discharged/transferred to another type of inpatient care institution                                          1184
Not Mapped                                                                                                     989
Discharged/transferred to ICF                                                                                  815
Left AMA                                                                                                       623
Discharged/transferred to a long term care hospital.                                                           412
Hospice / home                                                                                                 399
Hospice / medical facility                                                                                     372
Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital      139
Discharged/transferred to home under care of Home IV provider                                                  108
Discharged/transferred within this institution to Medicare approved swing bed                                   63
Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.         48
Admitted as an inpatient to this hospital                                                                       21
Discharged/transferred/referred to this institution for outpatient services                                     14
Discharged/transferred/referred another institution for outpatient services                                     11
Expired at home. Medicaid only, hospice.                                                                         8
Neonate discharged to another hospital for neonatal aftercare                                                    6
Discharged/transferred to a federal health care facility.                                                        5
Still patient or expected to return for outpatient services                                                      3
Expired in a medical facility. Medicaid only, hospice.                                                           2
Name: count, dtype: int64

In [57]:
remove_disposition = [
    "Expired",
    "Hospice / home",
    "Hospice / medical facility",
    "Expired at home. Medicaid only, hospice.",
    "Expired in a medical facility. Medicaid only, hospice."
]

data["discharge_disposition_id"].isin(remove_disposition).sum()

np.int64(2423)

In [58]:
data = data[
    ~data["discharge_disposition_id"].isin(remove_disposition)
]

In [59]:
data_overview(data)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),Missing,Not Mapped,Physician Referral,1,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),Emergency,Discharged to home,Emergency Room,3,Missing,59,0,18,0,0,0,276,250.01,255,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),Emergency,Discharged to home,Emergency Room,2,Missing,11,5,13,2,0,1,648,250,V27,6,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),Emergency,Discharged to home,Emergency Room,2,Missing,44,1,16,0,0,0,8,250.43,403,7,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),Emergency,Discharged to home,Emergency Room,1,Missing,51,0,8,0,0,0,197,157,250,5,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),Urgent,Discharged to home,Clinic Referral,3,Missing,31,6,16,0,0,0,414,411,250,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),Elective,Discharged to home,Clinic Referral,4,Missing,70,1,21,0,0,0,414,411,V45,7,not_measured,Not measured,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),Emergency,Discharged to home,Emergency Room,5,Missing,73,0,12,0,0,0,428,492,250,8,not_measured,Not measured,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),Urgent,Discharged to home,Transfer from a hospital,13,Missing,68,2,28,0,0,0,398,427,38,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),Elective,Discharged/transferred to SNF,Transfer from a hospital,12,InternalMedicine,33,3,18,0,0,0,434,198,486,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),Emergency,Discharged to home,Emergency Room,9,Missing,47,2,17,0,0,0,250.7,403,996,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),Urgent,Discharged to home,Transfer from a hospital,7,Missing,62,0,11,0,0,0,157,288,197,7,not_measured,Not measured,No,No,No,No,No,No,No,Up,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),Emergency,Discharged/transferred to SNF,Emergency Room,7,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,not_measured,Not measured,Steady,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),Emergency,Discharged/transferred to home with home healt...,Emergency Room,10,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),Elective,Discharged to home,Clinic Referral,1,Missing,49,5,2,0,0,0,518,998,627,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),Emergency,Discharged/transferred to SNF,Emergency Room,12,Missing,75,5,13,0,0,0,999,507,996,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),Emergency,Discharged to home,Emergency Room,4,Missing,45,4,17,0,0,0,410,411,414,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),Emergency,Discharged to home,Emergency Room,3,Cardiology,29,0,11,0,0,0,682,174,250,3,not_measured,Not measured,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),Emergency,Discharged to home,Emergency Room,5,Missing,35,5,23,0,0,0,402,425,416,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,NaN,Male,[70-80),Elective,Discharged/transferred to home with home healt...,Clinic Referral,6,Missing,42,2,23,0,0,0,737,427,714,8,not_measured,Not measured,No,No,No,No,No,No,No,Down,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,NaN,Female,[50-60),Urgent,Discharged to home,Transfer from a hospital,2,Missing,66,1,19,0,0,0,410,427,428,7,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,NaN,Male,[60-70),Urgent,Discharged to home,Transfer from a hospital,2,Missing,36,2,11,0,0,0,572,456,427,6,not_measured,Not measured,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),Urgent,Discharged to home,Transfer from a hospital,2,Missing,47,0,12,0,0,0,410,401,582,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),Urgent,Discharged/transferred to home with home healt...,Physician Referral,11,Missing,42,2,19,0,0,0,V57,715,V43,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),Elective,Discharged to home,Clinic Referral,3,Missing,19,4,18,0,0,0,189,496,427,6,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),Emergency,Discharged to home,Emergency Room,1,Missing,33,0,7,0,0,0,786,401,250,3,not_measured,Not measured,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),Emergency,Discharged/transferred to SNF,Emergency Room,6,Cardiology,64,3,18,0,0,0,427,428,414,7,not_measured,>7,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),Emergency,Discharged to home,Physician Referral,2,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),Urgent,Discharged to home,Clinic Referral,10,Missing,53,0,20,0,0,0,277,250.02,263,6,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),Emergency,Discharged/transferred to another short term h...,Emergency Room,5,Cardiology,52,0,14,0,0,0,428,410,414,8,not_measured,Not measured,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),Emergency,Discharged to home,Emergency Room,6,Missing,87,0,18,0,0,0,584,496,250.42,9,not_measured,Not measured,No,No,No,No,No,No,No,Up,No,No,No,Steady,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),Emergency,Discharged/transferred to another type of inpa...,Emergency Room,1,Missing,53,0,10,0,0,0,462,250.01,276,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),Emergency,Discharged to home,Emergency Room,6,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),Urgent,Discharged/transferred to home with home healt...,Clinic Referral,5,Missing,37,0,18,0,0,0,473,996,482,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
35,325848,63023292,Caucasian,Female,[60-70),Emergency,Discharged to home,Emergency Room,2,Cardiology,41,0,11,0,0,0,411,250.01,401,6,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),Elective,Discharged to home,Clinic Referral,3,Missing,33,1,8,0,0,0,174,135,250,5,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),Emergency,Discharged to home,Emergency Room,4,Missing,33,0,12,0,0,0,486,244,250,3,not_measured,Not measured,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),Emergency,Discharged/transferred to home with home healt...,Emergency Room,7,Missing,47,2,22,0,0,0,998,41,414,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),Urgent,Discharged to home,Clinic Referral,1,Missing,44,1,15,0,0,0,996,403,250.41,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),Emergency,Discharged/transferred to another short term h...,Emergency Room,1,Cardiology,28,0,15,0,0,0,414,411,250.01,4,not_measured,Not measured,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),Urgent,Discharged to home,Clinic Referral,7,Missing,36,2,9,0,0,0,511,571,585,5,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),Urgent,Discharged to home,Physician Referral,13,Missing,48,2,18,0,0,1,V57,276,781,8,not_measured,Not measured,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),Emergency,Discharged to home,Emergency Room,3,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,not_measured,Not measured,Steady,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,>30
45,464994,106936875,Caucasian,Female,[40-50),Elective,Discharged to home,Clinic Referral,2,Missing,10,3,8,0,0,0,626,250.01,998,5,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital,9,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,not_measured,Not measured,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),Elective,Discharged/transferred to SNF,Transfer from a hospital,9,Missing,2,0,12,0,0,1,295,599,250,3,not_measured,Not measured,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),Elective,Discharged to home,Clinic Referral,6,Missing,65,5,19,0,0,0,414,424,428,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital,11,Missing,67,2,25,0,0,0,428,491,427,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
50,550098,21820806,AfricanAmerican,Male,[50-60),Urgent,Discharged to home,Clinic Referral,4,Missing,40,1,14,0,0,0,196,198,197,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,<30
51,584136,72200358,Caucasian,Male,[70-80),Elective,Discharged to home,Clinic Referral,5,Missing,44,5,13,0,0,0,998,553,568,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30

Number of rows:99343
Number of columns:48
                         Data type:  Missing values:  Percentage of na:  \
encounter_id                  int64                0           0.000000
patient_nbr                   int64                0           0.000000
race                         object             2234           2.248774
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id            object                0           0.000000
discharge_disposition_id     object                0           0.000000
admission_source_id          object                0           0.000000
time_in_hospital              int64                0           0.000000
medical_specialty            object                0           0.000000
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               20           0.020132
diag_2                       object              356           0.358354
diag_3                       object             1419           1.428384
number_diagnoses              int64                0           0.000000
max_glu_serum                object                0           0.000000
A1Cresult                    object                0           0.000000
metformin                    object                0           0.000000
repaglinide                  object                0           0.000000
nateglinide                  object                0           0.000000
chlorpropamide               object                0           0.000000
glimepiride                  object                0           0.000000
acetohexamide                object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
tolbutamide                  object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
acarbose                     object                0           0.000000
miglitol                     object                0           0.000000
troglitazone                 object                0           0.000000
tolazamide                   object                0           0.000000
examide                      object                0           0.000000
citoglipton                  object                0           0.000000
insulin                      object                0           0.000000
glyburide-metformin          object                0           0.000000
glipizide-metformin          object                0           0.000000
glimepiride-pioglitazone     object                0           0.000000
metformin-rosiglitazone      object                0           0.000000
metformin-pioglitazone       object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000

                          Value count:
encounter_id                     99343
patient_nbr                      69990
race                                 5
gender                               3
age                                 10
admission_type_id                    8
discharge_disposition_id            21
admission_source_id                 17
time_in_hospital                    14
medical_specialty                   73
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             715
diag_2                             747
diag_3                             786
number_diagnoses                    16
max_glu_serum                        4
A1Cresult                            4
metformin                            4
repaglinide                          4
nateglinide                          4
chlorpropamide                       4
glimepiride                          4
acetohexamide                        2
glipizide                            4
glyburide                            4
tolbutamide                          2
pioglitazone                         4
rosiglitazone                        4
acarbose                             4
miglitol                             4
troglitazone                         2
tolazamide                           3
examide                              1
citoglipton                          1
insulin                              4
glyburide-metformin                  4
glipizide-metformin                  2
glimepiride-pioglitazone             2
metformin-rosiglitazone              2
metformin-pioglitazone               2
change                               2
diabetesMed                          2
readmitted                           3

Uklonjeni su redovi kod kojih je ishod hospitalizacije bio Expired ili Hospice, jer kod ovih pacijenata readmisija nije moguca ili nije uporediva sa ostalim slucajevima. Ukupno je uklonjeno 2.423 redova.

### Selekcija atrbitua

In [60]:
data.drop("encounter_id", axis= 1, inplace=True)

Atribut "encounter_id" predstavlja jedinstveni identifikator, pa je zbog toga uklonjen iz dalje analize.

In [61]:
data["patient_nbr"].nunique()

69990

Atribut patient_nbr se za sada zadrzava jer se koristi za grupisanje hospitalizacija istog pacijenta prilikom podele podataka na skupove za treniranje i testiranje. Nece biti koriscen kao ulazni atribut modela.

In [62]:
data.nunique().sort_values()

citoglipton                     1
examide                         1
diabetesMed                     2
change                          2
acetohexamide                   2
metformin-pioglitazone          2
metformin-rosiglitazone         2
glimepiride-pioglitazone        2
glipizide-metformin             2
tolbutamide                     2
troglitazone                    2
readmitted                      3
gender                          3
tolazamide                      3
insulin                         4
miglitol                        4
acarbose                        4
rosiglitazone                   4
pioglitazone                    4
glyburide-metformin             4
glyburide                       4
glipizide                       4
glimepiride                     4
chlorpropamide                  4
nateglinide                     4
metformin                       4
A1Cresult                       4
max_glu_serum                   4
repaglinide                     4
race                            5
num_procedures                  7
admission_type_id               8
age                            10
time_in_hospital               14
number_diagnoses               16
admission_source_id            17
number_inpatient               21
discharge_disposition_id       21
number_emergency               33
number_outpatient              39
medical_specialty              73
num_medications                75
num_lab_procedures            118
diag_1                        715
diag_2                        747
diag_3                        786
patient_nbr                 69990
dtype: int64

In [63]:
data = data.drop(["citoglipton", "examide"], axis=1)

Atributi citoglipton i examide su uklonjeni jer imaju samo jednu jedinstvenu vrednost u celom skupu podataka i samim tim ne sadrze korisnu informaciju za model.

In [64]:
data[["acetohexamide","metformin-pioglitazone","metformin-rosiglitazone","glimepiride-pioglitazone","glipizide-metformin","tolbutamide","troglitazone"]].apply(pd.Series.value_counts)

,acetohexamide,metformin-pioglitazone,metformin-rosiglitazone,glimepiride-pioglitazone,glipizide-metformin,tolbutamide,troglitazone
No,99342,99342,99341,99342,99330,99322,99340
Steady,1,1,2,1,13,21,3

Kod navedenih atributa uocena je izrazito mala varijabilnost, pri cemu kategorija „Steady“ cini svega 0,001–0,02% vrednosti, dok gotovo sve preostale vrednosti pripadaju kategoriji „No“. Zadrzavanje ovakvih atributa moglo bi dovesti do nestabilnog ucenja i overfittinga, jer bi model mogao da pridaje preveliki znacaj veoma malom broju primera iz retke kategorije, cime bi se smanjila sposobnost generalizacije na nove podatke.

In [65]:
data = data.drop([
    "acetohexamide",
    "metformin-pioglitazone",
    "metformin-rosiglitazone",
    "glimepiride-pioglitazone",
    "glipizide-metformin",
    "tolbutamide",
    "troglitazone"
], axis=1)

In [66]:
data[["tolazamide","repaglinide","metformin","glimepiride","glipizide","glyburide","pioglitazone","acarbose","nateglinide","miglitol","insulin","glyburide-metformin","rosiglitazone","chlorpropamide"]].apply(pd.Series.value_counts)

,tolazamide,repaglinide,metformin,glimepiride,glipizide,glyburide,pioglitazone,acarbose,nateglinide,miglitol,insulin,glyburide-metformin,rosiglitazone,chlorpropamide
Down,NaN,43,574,191,548,560,117,3,11,5,11908,6,85,1
No,99304.0,97825,79499,94221,86812,88820,92088,99038,98654,99305,46379,98645,93039,99258
Steady,38.0,1368,18207,4609,11219,9162,6908,292,654,31,30069,684,6048,78
Up,1.0,107,1063,322,764,801,230,10,24,2,10987,8,171,6

In [67]:
data = data.drop(["tolazamide","miglitol","chlorpropamide"], axis= 1)

Atributi tolazamide, miglitol i chlorpropamide uklonjeni su zbog izrazito male varijabilnosti, odnosno veoma malog broja vrednosti koje se razlikuju od kategorije No, sto ogranicava njihov potencijalni doprinos modelu.

In [68]:
drug_columns = [
    "repaglinide",
    "acarbose",
    "nateglinide",
    "glyburide-metformin"
]

for column in drug_columns:
    display(
        pd.crosstab(
            data[column],
            data["readmitted"],
            normalize="index"
        ) * 100
    )

readmitted         <30        >30         NO
repaglinide
Down          6.976744  44.186047  48.837209
No           11.355993  35.637107  53.006900
Steady       13.304094  42.982456  43.713450
Up           18.691589  30.841121  50.467290

readmitted        <30        >30         NO
acarbose
Down        33.333333  33.333333  33.333333
No          11.395626  35.690341  52.914033
Steady       8.561644  51.369863  40.068493
Up          20.000000  40.000000  40.000000

readmitted         <30        >30         NO
nateglinide
Down          9.090909  36.363636  54.545455
No           11.387273  35.720802  52.891925
Steady       11.926606  37.920489  50.152905
Up            4.166667  41.666667  54.166667

readmitted                 <30        >30         NO
glyburide-metformin
Down                 16.666667   0.000000  83.333333
No                   11.390339  35.728116  52.881545
Steady               11.257310  37.573099  51.169591
Up                    0.000000  12.500000  87.500000

In [69]:
for column in drug_columns:
    table = pd.crosstab(data[column], data["readmitted"])
    chi2, p_value, dof, expected = chi2_contingency(table)

    print(f"{column}:")
    print(f"Chi-square = {chi2:.2f}")
    print(f"p-value = {p_value:.4f}")
    n = table.to_numpy().sum()
    r, k = table.shape

    cramer_v = np.sqrt(
        chi2 / (n * min(r - 1, k - 1))
    )

    print(f"{column}: Cramer's V = {cramer_v:.4f}")

repaglinide:
Chi-square = 54.48
p-value = 0.0000
repaglinide: Cramer's V = 0.0166
acarbose:
Chi-square = 33.67
p-value = 0.0000
acarbose: Cramer's V = 0.0130
nateglinide:
Chi-square = 3.37
p-value = 0.7613
nateglinide: Cramer's V = 0.0041
glyburide-metformin:
Chi-square = 8.31
p-value = 0.2161
glyburide-metformin: Cramer's V = 0.0065

Za preostale atribute terapije koji pokazuju relativno slabu varijabilnost ispitana je povezanost sa readmitted pomocu Chi-square testa i Cramerovog testa. Iako su repaglinide i acarbose pokazali statisticki znacajnu povezanost, vrednosti Cramerovog testa bile su veoma male, sto ukazuje na veoma slabu prakticnu povezanost. Kod nateglinide i glyburide-metformin nije utvrdjena statisticki znacajna povezanost, uz takodje veoma male vrednosti Cramerovog testa. Na osnovu ovih rezultata, sva cetiri atributa su uklonjena iz dalje analize.

In [70]:
data = data.drop(["repaglinide","acarbose","nateglinide","glyburide-metformin"], axis = 1)

In [71]:
data_overview(data)

,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,8222157,Caucasian,Female,[0-10),Missing,Not Mapped,Physician Referral,1,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,not_measured,Not measured,No,No,No,No,No,No,No,No,No,NO
1,55629189,Caucasian,Female,[10-20),Emergency,Discharged to home,Emergency Room,3,Missing,59,0,18,0,0,0,276,250.01,255,9,not_measured,Not measured,No,No,No,No,No,No,Up,Ch,Yes,>30
2,86047875,AfricanAmerican,Female,[20-30),Emergency,Discharged to home,Emergency Room,2,Missing,11,5,13,2,0,1,648,250,V27,6,not_measured,Not measured,No,No,Steady,No,No,No,No,No,Yes,NO
3,82442376,Caucasian,Male,[30-40),Emergency,Discharged to home,Emergency Room,2,Missing,44,1,16,0,0,0,8,250.43,403,7,not_measured,Not measured,No,No,No,No,No,No,Up,Ch,Yes,NO
4,42519267,Caucasian,Male,[40-50),Emergency,Discharged to home,Emergency Room,1,Missing,51,0,8,0,0,0,197,157,250,5,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
5,82637451,Caucasian,Male,[50-60),Urgent,Discharged to home,Clinic Referral,3,Missing,31,6,16,0,0,0,414,411,250,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
6,84259809,Caucasian,Male,[60-70),Elective,Discharged to home,Clinic Referral,4,Missing,70,1,21,0,0,0,414,411,V45,7,not_measured,Not measured,Steady,Steady,No,No,No,No,Steady,Ch,Yes,NO
7,114882984,Caucasian,Male,[70-80),Emergency,Discharged to home,Emergency Room,5,Missing,73,0,12,0,0,0,428,492,250,8,not_measured,Not measured,No,No,No,Steady,No,No,No,No,Yes,>30
8,48330783,Caucasian,Female,[80-90),Urgent,Discharged to home,Transfer from a hospital,13,Missing,68,2,28,0,0,0,398,427,38,8,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
9,63555939,Caucasian,Female,[90-100),Elective,Discharged/transferred to SNF,Transfer from a hospital,12,InternalMedicine,33,3,18,0,0,0,434,198,486,8,not_measured,Not measured,No,No,No,No,No,Steady,Steady,Ch,Yes,NO
10,89869032,AfricanAmerican,Female,[40-50),Emergency,Discharged to home,Emergency Room,9,Missing,47,2,17,0,0,0,250.7,403,996,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
11,77391171,AfricanAmerican,Male,[60-70),Urgent,Discharged to home,Transfer from a hospital,7,Missing,62,0,11,0,0,0,157,288,197,7,not_measured,Not measured,No,No,No,Up,No,No,Steady,Ch,Yes,<30
12,85504905,Caucasian,Female,[40-50),Emergency,Discharged/transferred to SNF,Emergency Room,7,Family/GeneralPractice,60,0,15,0,1,0,428,250.43,250.6,8,not_measured,Not measured,Steady,No,No,No,No,No,Down,Ch,Yes,<30
13,77586282,Caucasian,Male,[80-90),Emergency,Discharged/transferred to home with home healt...,Emergency Room,10,Family/GeneralPractice,55,1,31,0,0,0,428,411,427,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,NO
14,49726791,AfricanAmerican,Female,[60-70),Elective,Discharged to home,Clinic Referral,1,Missing,49,5,2,0,0,0,518,998,627,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
15,86328819,AfricanAmerican,Male,[60-70),Emergency,Discharged/transferred to SNF,Emergency Room,12,Missing,75,5,13,0,0,0,999,507,996,9,not_measured,Not measured,No,No,No,No,No,No,Up,Ch,Yes,NO
16,92519352,AfricanAmerican,Male,[50-60),Emergency,Discharged to home,Emergency Room,4,Missing,45,4,17,0,0,0,410,411,414,8,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,<30
17,108662661,Caucasian,Female,[50-60),Emergency,Discharged to home,Emergency Room,3,Cardiology,29,0,11,0,0,0,682,174,250,3,not_measured,Not measured,No,No,No,Steady,No,No,No,No,Yes,NO
18,107389323,AfricanAmerican,Male,[70-80),Emergency,Discharged to home,Emergency Room,5,Missing,35,5,23,0,0,0,402,425,416,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
19,69422211,NaN,Male,[70-80),Elective,Discharged/transferred to home with home healt...,Clinic Referral,6,Missing,42,2,23,0,0,0,737,427,714,8,not_measured,Not measured,No,No,No,Down,No,No,Steady,Ch,Yes,NO
20,22864131,NaN,Female,[50-60),Urgent,Discharged to home,Transfer from a hospital,2,Missing,66,1,19,0,0,0,410,427,428,7,not_measured,Not measured,No,No,No,No,No,No,Down,Ch,Yes,NO
21,21239181,NaN,Male,[60-70),Urgent,Discharged to home,Transfer from a hospital,2,Missing,36,2,11,0,0,0,572,456,427,6,not_measured,Not measured,Steady,Steady,No,No,No,No,Steady,Ch,Yes,NO
22,63000108,AfricanAmerican,Female,[70-80),Urgent,Discharged to home,Transfer from a hospital,2,Missing,47,0,12,0,0,0,410,401,582,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,NO
23,107400762,Caucasian,Female,[80-90),Urgent,Discharged/transferred to home with home healt...,Physician Referral,11,Missing,42,2,19,0,0,0,V57,715,V43,8,not_measured,Not measured,No,No,No,No,No,No,No,No,No,>30
24,62718876,AfricanAmerican,Female,[70-80),Elective,Discharged to home,Clinic Referral,3,Missing,19,4,18,0,0,0,189,496,427,6,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
25,21861756,Other,Female,[50-60),Emergency,Discharged to home,Emergency Room,1,Missing,33,0,7,0,0,0,786,401,250,3,not_measured,Not measured,Steady,No,No,No,No,No,No,No,Yes,NO
26,40523301,Caucasian,Male,[80-90),Emergency,Discharged/transferred to SNF,Emergency Room,6,Cardiology,64,3,18,0,0,0,427,428,414,7,not_measured,>7,Steady,No,No,Steady,No,No,No,Ch,Yes,NO
27,115196778,Caucasian,Female,[50-60),Emergency,Discharged to home,Physician Referral,2,Surgery-General,25,2,11,0,0,0,996,585,250.01,3,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
28,41606064,Caucasian,Male,[20-30),Urgent,Discharged to home,Clinic Referral,10,Missing,53,0,20,0,0,0,277,250.02,263,6,not_measured,Not measured,No,No,No,No,No,No,Down,Ch,Yes,>30
29,18196434,Caucasian,Female,[80-90),Emergency,Discharged/transferred to another short term h...,Emergency Room,5,Cardiology,52,0,14,0,0,0,428,410,414,8,not_measured,Not measured,Steady,No,No,Steady,No,No,No,Ch,Yes,>30
30,56480238,AfricanAmerican,Female,[60-70),Emergency,Discharged to home,Emergency Room,6,Missing,87,0,18,0,0,0,584,496,250.42,9,not_measured,Not measured,No,No,No,Up,No,No,Steady,Ch,Yes,NO
31,96664626,AfricanAmerican,Male,[70-80),Emergency,Discharged/transferred to another type of inpa...,Emergency Room,1,Missing,53,0,10,0,0,0,462,250.01,276,8,not_measured,Not measured,No,No,No,No,No,No,Down,Ch,Yes,>30
32,80845353,Caucasian,Female,[70-80),Emergency,Discharged to home,Emergency Room,6,Family/GeneralPractice,27,0,16,0,0,0,996,999,250.01,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
33,114715242,Caucasian,Male,[60-70),Urgent,Discharged/transferred to home with home healt...,Clinic Referral,5,Missing,37,0,18,0,0,0,473,996,482,8,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
35,63023292,Caucasian,Female,[60-70),Emergency,Discharged to home,Emergency Room,2,Cardiology,41,0,11,0,0,0,411,250.01,401,6,not_measured,Not measured,No,No,No,No,No,Steady,Down,Ch,Yes,>30
36,98427861,Caucasian,Female,[70-80),Elective,Discharged to home,Clinic Referral,3,Missing,33,1,8,0,0,0,174,135,250,5,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,NO
37,112002975,Caucasian,Female,[60-70),Emergency,Discharged to home,Emergency Room,4,Missing,33,0,12,0,0,0,486,244,250,3,not_measured,Not measured,Steady,No,Steady,No,No,No,Steady,Ch,Yes,>30
38,101002446,Caucasian,Male,[70-80),Emergency,Discharged/transferred to home with home healt...,Emergency Room,7,Missing,47,2,22,0,0,0,998,41,414,8,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
39,104672268,Caucasian,Male,[50-60),Urgent,Discharged to home,Clinic Referral,1,Missing,44,1,15,0,0,0,996,403,250.41,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
40,80588529,Caucasian,Female,[70-80),Emergency,Discharged/transferred to another short term h...,Emergency Room,1,Cardiology,28,0,15,0,0,0,414,411,250.01,4,not_measured,Not measured,Steady,No,No,No,No,No,Down,Ch,Yes,>30
41,99715041,Caucasian,Male,[40-50),Urgent,Discharged to home,Clinic Referral,7,Missing,36,2,9,0,0,0,511,571,585,5,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30
42,96435585,Caucasian,Female,[70-80),Urgent,Discharged to home,Physician Referral,13,Missing,48,2,18,0,0,1,V57,276,781,8,not_measured,Not measured,Steady,No,No,Steady,No,No,Steady,Ch,Yes,>30
43,66274866,Caucasian,Male,[50-60),Emergency,Discharged to home,Emergency Room,3,Family/GeneralPractice,59,0,11,0,0,0,428,496,278,6,not_measured,Not measured,Steady,No,Steady,No,No,No,Steady,Ch,Yes,>30
45,106936875,Caucasian,Female,[40-50),Elective,Discharged to home,Clinic Referral,2,Missing,10,3,8,0,0,0,626,250.01,998,5,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,NO
46,86240259,Caucasian,Female,[70-80),Elective,Discharged/transferred to another type of inpa...,Transfer from a hospital,9,InternalMedicine,25,3,16,0,0,2,428,427,250.01,7,not_measured,Not measured,No,No,No,Steady,No,No,Down,Ch,Yes,<30
47,51838164,Caucasian,Male,[70-80),Elective,Discharged/transferred to SNF,Transfer from a hospital,9,Missing,2,0,12,0,0,1,295,599,250,3,not_measured,Not measured,Up,No,No,No,No,No,Steady,Ch,Yes,NO
48,90097839,Caucasian,Male,[50-60),Elective,Discharged to home,Clinic Referral,6,Missing,65,5,19,0,0,0,414,424,428,9,not_measured,Not measured,No,No,No,No,No,No,Up,Ch,Yes,NO
49,34997814,Caucasian,Male,[60-70),Urgent,Discharged/transferred to home with home healt...,Transfer from a hospital,11,Missing,67,2,25,0,0,0,428,491,427,9,not_measured,Not measured,No,No,Steady,No,No,No,Steady,Ch,Yes,NO
50,21820806,AfricanAmerican,Male,[50-60),Urgent,Discharged to home,Clinic Referral,4,Missing,40,1,14,0,0,0,196,198,197,9,not_measured,Not measured,No,No,No,No,No,No,No,No,No,<30
51,72200358,Caucasian,Male,[70-80),Elective,Discharged to home,Clinic Referral,5,Missing,44,5,13,0,0,0,998,553,568,9,not_measured,Not measured,No,No,No,No,No,No,Steady,No,Yes,>30

Number of rows:99343
Number of columns:31
                         Data type:  Missing values:  Percentage of na:  \
patient_nbr                   int64                0           0.000000
race                         object             2234           2.248774
gender                       object                0           0.000000
age                          object                0           0.000000
admission_type_id            object                0           0.000000
discharge_disposition_id     object                0           0.000000
admission_source_id          object                0           0.000000
time_in_hospital              int64                0           0.000000
medical_specialty            object                0           0.000000
num_lab_procedures            int64                0           0.000000
num_procedures                int64                0           0.000000
num_medications               int64                0           0.000000
number_outpatient             int64                0           0.000000
number_emergency              int64                0           0.000000
number_inpatient              int64                0           0.000000
diag_1                       object               20           0.020132
diag_2                       object              356           0.358354
diag_3                       object             1419           1.428384
number_diagnoses              int64                0           0.000000
max_glu_serum                object                0           0.000000
A1Cresult                    object                0           0.000000
metformin                    object                0           0.000000
glimepiride                  object                0           0.000000
glipizide                    object                0           0.000000
glyburide                    object                0           0.000000
pioglitazone                 object                0           0.000000
rosiglitazone                object                0           0.000000
insulin                      object                0           0.000000
change                       object                0           0.000000
diabetesMed                  object                0           0.000000
readmitted                   object                0           0.000000

                          Value count:
patient_nbr                      69990
race                                 5
gender                               3
age                                 10
admission_type_id                    8
discharge_disposition_id            21
admission_source_id                 17
time_in_hospital                    14
medical_specialty                   73
num_lab_procedures                 118
num_procedures                       7
num_medications                     75
number_outpatient                   39
number_emergency                    33
number_inpatient                    21
diag_1                             715
diag_2                             747
diag_3                             786
number_diagnoses                    16
max_glu_serum                        4
A1Cresult                            4
metformin                            4
glimepiride                          4
glipizide                            4
glyburide                            4
pioglitazone                         4
rosiglitazone                        4
insulin                              4
change                               2
diabetesMed                          2
readmitted                           3

In [72]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['admission_type_id'] != 'Missing')
].copy()

In [73]:
table = pd.crosstab(
    medical_data['medical_specialty'],
    medical_data['admission_type_id']
)
print(table)

admission_type_id                     Elective  Emergency  Newborn  \
medical_specialty
AllergyandImmunology                         0          0        0
Anesthesiology                               6          3        0
Anesthesiology-Pediatric                     2         12        0
Cardiology                                1711       1604        0
Cardiology-Pediatric                         0          0        0
DCPTEAM                                      3          2        0
Dentistry                                    0          1        0
Dermatology                                  0          0        0
Emergency/Trauma                           877       2389        0
Endocrinology                                4         71        0
Endocrinology-Metabolism                     1          7        0
Family/GeneralPractice                    1050       3384        1
Gastroenterology                           100        155        0
Gynecology                                  54          1        0
Hematology                                  60          6        0
Hematology/Oncology                         16         42        0
Hospitalist                                 50          4        0
InfectiousDiseases                          14         11        0
InternalMedicine                           974       9286        1
Nephrology                                 325        723        0
Neurology                                  123         35        0
Neurophysiology                              1          0        0
Obsterics&Gynecology-GynecologicOnco        17          1        0
Obstetrics                                   3          0        0
ObstetricsandGynecology                    437         26        0
Oncology                                    73         73        0
Ophthalmology                               32          1        0
Orthopedics                               1147        113        0
Orthopedics-Reconstructive                 475        150        0
Osteopath                                    5         31        0
Otolaryngology                              92         18        0
OutreachServices                             8          4        0
Pathology                                    0          0        0
Pediatrics                                  25        163        0
Pediatrics-AllergyandImmunology              0          3        0
Pediatrics-CriticalCare                      5         56        0
Pediatrics-EmergencyMedicine                 0          3        0
Pediatrics-Endocrinology                    18        106        0
Pediatrics-Hematology-Oncology               0          3        0
Pediatrics-InfectiousDiseases                0          1        0
Pediatrics-Neurology                         0          7        0
Pediatrics-Pulmonology                      13          4        0
Perinatology                                 1          0        0
PhysicalMedicineandRehabilitation          256          4        0
PhysicianNotFound                            2          5        0
Podiatry                                    45          0        0
Proctology                                   0          0        0
Psychiatry                                 154        340        0
Psychiatry-Addictive                         0          1        0
Psychiatry-Child/Adolescent                  0          5        0
Psychology                                  76         16        0
Pulmonology                                166        351        0
Radiologist                                756        113        0
Radiology                                   14         13        0
Resident                                     0          2        0
Rheumatology                                 4          3        0
SportsMedicine                               0          0        0
Surgeon                                     29          7        0
Surgery-Cardiovascular                      72          1        0
Surgery-Cardiovascular/Thoracic            357         73        0
Surgery-Colon&Rectal                         6          3        0
Surgery-General                           1149        524        0
Surgery-Maxillofacial                        0          2        0
Surgery-Neuro                              283         64        0
Surgery-Pediatric                            3          3        0
Surgery-Plastic                             20          4        0
Surgery-Thoracic                            72          6        0
Surgery-Vascular                           382         16        0
SurgicalSpecialty                           20          3        0
Urology                                    394         82        0

admission_type_id                     Not Available  Not Mapped  Urgent
medical_specialty
AllergyandImmunology                              0           0       1
Anesthesiology                                    0           0       3
Anesthesiology-Pediatric                          0           0       4
Cardiology                                      152          27    1004
Cardiology-Pediatric                              0           0       7
DCPTEAM                                           0           0       0
Dentistry                                         0           0       2
Dermatology                                       0           0       1
Emergency/Trauma                                  1           0    4130
Endocrinology                                     0           0      35
Endocrinology-Metabolism                          0           0       0
Family/GeneralPractice                          737          10    1374
Gastroenterology                                 22           0     231
Gynecology                                        0           0       3
Hematology                                        0           0       8
Hematology/Oncology                              60           0      51
Hospitalist                                       1           0       2
InfectiousDiseases                                1           0      10
InternalMedicine                                 80          97    2481
Nephrology                                       71           0     329
Neurology                                         0           0      41
Neurophysiology                                   0           0       0
Obsterics&Gynecology-GynecologicOnco              0           0       3
Obstetrics                                       10           0       6
ObstetricsandGynecology                          23          11     126
Oncology                                          0           0     171
Ophthalmology                                     2           0       3
Orthopedics                                      19           0     107
Orthopedics-Reconstructive                      161          39     167
Osteopath                                         0           0       2
Otolaryngology                                    6           0       7
OutreachServices                                  0           0       0
Pathology                                         0           0      16
Pediatrics                                        0           1      53
Pediatrics-AllergyandImmunology                   0           0       0
Pediatrics-CriticalCare                           0           0      20
Pediatrics-EmergencyMedicine                      0           0       0
Pediatrics-Endocrinology                          0           0      21
Pediatrics-Hematology-Oncology                    0           0       1
Pediatrics-InfectiousDiseases                     0           0       0
Pediatrics-Neurology                              0           0       3
Pediatrics-Pulmonology                            0           0       7
Perinatology                                      0           0       0
PhysicalMedicineandRehabilitation                 0           0     123
PhysicianNotFound                                 0           0       3
Podiatry                                          0           0      53
Proctology                                        0           0       1
Psychiatry                                       84           0     219
Psychiatry-Addictive                              0           0       0
Psychiatry-Child/Adolescent                       0           0       1
Psychology                                        0           0       9
Pulmonology                                       2           1     178
Radiologist                                       0           0     252
Radiology                                         0           0      25
Resident                                          0           0       0
Rheumatology                                      0           0      10
SportsMedicine                                    0           0       1
Surgeon                                           4           0       5
Surgery-Cardiovascular                            0           0      25
Surgery-Cardiovascular/Thoracic                   1           0     191
Surgery-Colon&Rectal                              0           0       0
Surgery-General                                 211          35     890
Surgery-Maxillofacial                             0           0       6
Surgery-Neuro                                     0          12      91
Surgery-Pediatric                                 0           0       2
Surgery-Plastic                                   1           4       8
Surgery-Thoracic                                  0          17       6
Surgery-Vascular                                  0          22     101
SurgicalSpecialty                                 0           0      10
Urology                                          44           8     121

In [74]:
def cramers_v(x, y):
    table = pd.crosstab(x, y)
    chi2 = chi2_contingency(table)[0]
    n = table.sum().sum()
    r, k = table.shape
    
    return np.sqrt((chi2 / n) / min(r - 1, k - 1))

In [75]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['admission_type_id']
)

np.float64(0.3055287396546277)

In [76]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['discharge_disposition_id'] != 'Missing')
].copy()

In [77]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['discharge_disposition_id']
)

np.float64(0.09039242358157046)

In [78]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['admission_source_id'] != 'Missing')
].copy()

In [79]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['admission_source_id']
)

np.float64(0.20980333671833734)

In [80]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['diag_1'].notna())
].copy()

In [81]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['diag_1']
)

np.float64(0.3115135803891224)

In [82]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['diag_2'].notna())
].copy()

In [83]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['diag_2']
)

np.float64(0.22736980919190505)

In [84]:
medical_data = data[
    (data['medical_specialty'] != 'Missing') &
    (data['diag_3'].notna())
].copy()

In [85]:
cramers_v(
    medical_data['medical_specialty'],
    medical_data['diag_3']
)

np.float64(0.20704981486034818)

Proverena je povezanost promenljive medical_specialty sa ostalim kategorijskim atributima koji bi potencijalno mogli sadržati sličnu informaciju. Za procenu stepena povezanosti korišćen je Cramer's V. Dobijene vrednosti nisu ukazale na jaku povezanost između medical_specialty i analiziranih atributa, zbog čega nije uočena značajna redundantnost informacija. Na osnovu ovog rezultata, medical_specialty nije eliminisana zbog potencijalnog dupliranja informacija sa drugim atributima.

In [86]:
table = pd.crosstab(
    data['medical_specialty'],
    data['readmitted']
)

table

readmitted                             <30    >30     NO
medical_specialty
AllergyandImmunology                     3      3      1
Anesthesiology                           1      3      8
Anesthesiology-Pediatric                 1      5     13
Cardiology                             424   1853   3002
Cardiology-Pediatric                     1      4      2
DCPTEAM                                  0      1      4
Dentistry                                0      3      1
Dermatology                              0      1      0
Emergency/Trauma                       845   3004   3570
Endocrinology                            6     39     74
Endocrinology-Metabolism                 1      1      6
Family/GeneralPractice                 879   2663   3710
Gastroenterology                        61    213    264
Gynecology                               0     10     48
Hematology                              26     24     25
Hematology/Oncology                     40     64     83
Hospitalist                              4     19     34
InfectiousDiseases                       8     12     17
InternalMedicine                      1642   4719   7876
Missing                               5753  18182  24681
Nephrology                             248    666    625
Neurology                               12     46    143
Neurophysiology                          0      0      1
Obsterics&Gynecology-GynecologicOnco     2      5     18
Obstetrics                               1      2     16
ObstetricsandGynecology                 32    110    527
Oncology                                64    100    155
Ophthalmology                            2     11     25
Orthopedics                            151    327    914
Orthopedics-Reconstructive              92    293    845
Osteopath                                3     18     17
Otolaryngology                           2     29     94
OutreachServices                         1      5      6
Pathology                                1     10      5
Pediatrics                              16     79    158
Pediatrics-AllergyandImmunology          0      3      0
Pediatrics-CriticalCare                  3     28     56
Pediatrics-EmergencyMedicine             0      1      2
Pediatrics-Endocrinology                 1     23    135
Pediatrics-Hematology-Oncology           1      0      3
Pediatrics-InfectiousDiseases            0      1      0
Pediatrics-Neurology                     0      4      6
Pediatrics-Pulmonology                   2     17      6
Perinatology                             0      0      1
PhysicalMedicineandRehabilitation       60     94    237
PhysicianNotFound                        2      4      4
Podiatry                                10     48     42
Proctology                               0      0      1
Psychiatry                             104    262    487
Psychiatry-Addictive                     0      0      1
Psychiatry-Child/Adolescent              1      2      4
Psychology                               8     35     58
Pulmonology                             96    328    430
Radiologist                            102    383    636
Radiology                                8     14     31
Resident                                 1      1      0
Rheumatology                             3      5      9
Speech                                   0      0      1
SportsMedicine                           0      1      0
Surgeon                                  4      8     33
Surgery-Cardiovascular                   6     24     68
Surgery-Cardiovascular/Thoracic         43    130    469
Surgery-Colon&Rectal                     1      3      7
Surgery-General                        342   1045   1672
Surgery-Maxillofacial                    1      2      6
Surgery-Neuro                           32     76    354
Surgery-Pediatric                        0      2      6
Surgery-Plastic                          7      9     24
Surgery-PlasticwithinHeadandNeck         0      1      0
Surgery-Thoracic                        11     30     67
Surgery-Vascular                        74    200    251
SurgicalSpecialty                        2      9     22
Urology                                 67    185    430

In [87]:
chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("p-value:", p_value)

Chi-square: 1471.5740613189244
p-value: 1.2749422741591935e-218

In [88]:
n = table.sum().sum()
r, k = table.shape

cramers_v_value = np.sqrt(
    (chi2 / n) / min(r - 1, k - 1)
)

print("Cramer's V:", cramers_v_value)

Cramer's V: 0.08606120622375836

In [89]:
pd.crosstab(
    data['medical_specialty'],
    data['readmitted'],
    normalize='index'
).round(3)

readmitted                              <30    >30     NO
medical_specialty
AllergyandImmunology                  0.429  0.429  0.143
Anesthesiology                        0.083  0.250  0.667
Anesthesiology-Pediatric              0.053  0.263  0.684
Cardiology                            0.080  0.351  0.569
Cardiology-Pediatric                  0.143  0.571  0.286
DCPTEAM                               0.000  0.200  0.800
Dentistry                             0.000  0.750  0.250
Dermatology                           0.000  1.000  0.000
Emergency/Trauma                      0.114  0.405  0.481
Endocrinology                         0.050  0.328  0.622
Endocrinology-Metabolism              0.125  0.125  0.750
Family/GeneralPractice                0.121  0.367  0.512
Gastroenterology                      0.113  0.396  0.491
Gynecology                            0.000  0.172  0.828
Hematology                            0.347  0.320  0.333
Hematology/Oncology                   0.214  0.342  0.444
Hospitalist                           0.070  0.333  0.596
InfectiousDiseases                    0.216  0.324  0.459
InternalMedicine                      0.115  0.331  0.553
Missing                               0.118  0.374  0.508
Nephrology                            0.161  0.433  0.406
Neurology                             0.060  0.229  0.711
Neurophysiology                       0.000  0.000  1.000
Obsterics&Gynecology-GynecologicOnco  0.080  0.200  0.720
Obstetrics                            0.053  0.105  0.842
ObstetricsandGynecology               0.048  0.164  0.788
Oncology                              0.201  0.313  0.486
Ophthalmology                         0.053  0.289  0.658
Orthopedics                           0.108  0.235  0.657
Orthopedics-Reconstructive            0.075  0.238  0.687
Osteopath                             0.079  0.474  0.447
Otolaryngology                        0.016  0.232  0.752
OutreachServices                      0.083  0.417  0.500
Pathology                             0.062  0.625  0.312
Pediatrics                            0.063  0.312  0.625
Pediatrics-AllergyandImmunology       0.000  1.000  0.000
Pediatrics-CriticalCare               0.034  0.322  0.644
Pediatrics-EmergencyMedicine          0.000  0.333  0.667
Pediatrics-Endocrinology              0.006  0.145  0.849
Pediatrics-Hematology-Oncology        0.250  0.000  0.750
Pediatrics-InfectiousDiseases         0.000  1.000  0.000
Pediatrics-Neurology                  0.000  0.400  0.600
Pediatrics-Pulmonology                0.080  0.680  0.240
Perinatology                          0.000  0.000  1.000
PhysicalMedicineandRehabilitation     0.153  0.240  0.606
PhysicianNotFound                     0.200  0.400  0.400
Podiatry                              0.100  0.480  0.420
Proctology                            0.000  0.000  1.000
Psychiatry                            0.122  0.307  0.571
Psychiatry-Addictive                  0.000  0.000  1.000
Psychiatry-Child/Adolescent           0.143  0.286  0.571
Psychology                            0.079  0.347  0.574
Pulmonology                           0.112  0.384  0.504
Radiologist                           0.091  0.342  0.567
Radiology                             0.151  0.264  0.585
Resident                              0.500  0.500  0.000
Rheumatology                          0.176  0.294  0.529
Speech                                0.000  0.000  1.000
SportsMedicine                        0.000  1.000  0.000
Surgeon                               0.089  0.178  0.733
Surgery-Cardiovascular                0.061  0.245  0.694
Surgery-Cardiovascular/Thoracic       0.067  0.202  0.731
Surgery-Colon&Rectal                  0.091  0.273  0.636
Surgery-General                       0.112  0.342  0.547
Surgery-Maxillofacial                 0.111  0.222  0.667
Surgery-Neuro                         0.069  0.165  0.766
Surgery-Pediatric                     0.000  0.250  0.750
Surgery-Plastic                       0.175  0.225  0.600
Surgery-PlasticwithinHeadandNeck      0.000  1.000  0.000
Surgery-Thoracic                      0.102  0.278  0.620
Surgery-Vascular                      0.141  0.381  0.478
SurgicalSpecialty                     0.061  0.273  0.667
Urology                               0.098  0.271  0.630

Analizom povezanosti sa ciljnom promenljivom readmitted utvrđena je statistički značajna povezanost (χ² test, p < 0.001), ali je intenzitet povezanosti veoma slab (Cramer's V = 0.086). Iako je uticaj promenljive na ciljnu promenljivu slab, zbog postojanja statistički značajne povezanosti odlučeno je da se medical_specialty zadrži u daljoj analizi i modeliranju.

In [90]:
compare_column_with_all_columns("readmitted")

--- patient_nbr ---

,count,mean,std,min,25%,50%,75%,max
readmitted,,,,,,,,
<30,11314.0,5.520815e+07,3.780236e+07,135.0,23583822.75,48139200.0,88227540.0,188970179.0
>30,35502.0,5.814380e+07,3.661933e+07,135.0,24800184.00,57902751.0,89308872.0,189481478.0
NO,52527.0,5.143300e+07,4.006361e+07,378.0,20185015.50,42050817.0,85699066.5,189502619.0

race        AfricanAmerican     Asian  Caucasian  Hispanic     Other
readmitted
<30               19.315118  0.584217  76.900953  1.905447  1.294266
>30               18.928040  0.460474  77.502574  1.833314  1.275598
NO                19.610341  0.787942  75.591446  2.281503  1.728768

gender         Female       Male  Unknown/Invalid
readmitted
<30         54.162984  45.837016         0.000000
>30         54.906766  45.093234         0.000000
NO          52.987987  47.006302         0.005711

age,[0-10),[10-20),[20-30),[30-40),[40-50),[50-60),[60-70),[70-80),[80-90),[90-100)
readmitted,,,,,,,,,,
<30,0.026516,0.353544,2.085911,3.747569,9.050734,14.733958,22.034647,26.993106,18.251724,2.722291
>30,0.073235,0.630950,1.436539,3.343474,9.224832,16.649766,22.218467,26.654836,17.494789,2.273111
NO,0.249396,0.811011,1.719116,4.098844,10.105279,18.051669,22.232376,24.395073,15.531060,2.806176

admission_type_id,Elective,Emergency,Missing,Newborn,Not Available,Not Mapped,Trauma Center,Urgent
readmitted,,,,,,,,
<30,17.305993,54.746332,5.152908,0.008839,4.357433,0.238642,0.000000,18.189853
>30,16.170920,54.292716,6.284153,0.005633,4.847614,0.236606,0.000000,18.162357
NO,20.882594,51.215565,4.555752,0.013326,4.574790,0.397891,0.034268,18.325813

discharge_disposition_id,Admitted as an inpatient to this hospital,Discharged to home,Discharged/transferred to ICF,Discharged/transferred to SNF,Discharged/transferred to a federal health care facility.,Discharged/transferred to a long term care hospital.,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.,Discharged/transferred to another rehab fac including rehab units of a hospital .,Discharged/transferred to another short term hospital,Discharged/transferred to another type of inpatient care institution,Discharged/transferred to home under care of Home IV provider,Discharged/transferred to home with home health service,Discharged/transferred within this institution to Medicare approved swing bed,Discharged/transferred/referred another institution for outpatient services,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital,Discharged/transferred/referred to this institution for outpatient services,Left AMA,Missing,Neonate discharged to another hospital for neonatal aftercare,Not Mapped,Still patient or expected to return for outpatient services
readmitted,,,,,,,,,,,,,,,,,,,,,
<30,0.079547,49.513877,0.919215,18.083790,0.000000,0.265158,0.061870,4.878911,3.022804,2.183136,0.132579,14.477638,0.247481,0.000000,0.450769,0.000000,0.795475,4.056921,0.000000,0.813152,0.017677
>30,0.005633,60.607853,0.783054,13.847107,0.002817,0.405611,0.045068,1.461889,1.881584,0.985860,0.107036,15.103374,0.050701,0.016900,0.095769,0.014084,0.622500,2.892795,0.011267,1.059095,0.000000
NO,0.019038,63.043768,0.824338,13.311249,0.007615,0.453100,0.047595,1.755288,2.128429,1.117521,0.104708,11.236126,0.032364,0.009519,0.102804,0.017134,0.593980,4.197841,0.003808,0.991871,0.001904

admission_source_id,Clinic Referral,Court/Law Enforcement,Emergency Room,Extramural Birth,HMO Referral,Missing,Normal Delivery,Not Available,Not Mapped,Physician Referral,Sick Baby,Transfer from Ambulatory Surgery Center,Transfer from a Skilled Nursing Facility (SNF),Transfer from a hospital,Transfer from another health care facility,Transfer from critial access hospital,Transfer from hospital inpt/same fac reslt in a sep claim
readmitted,,,,,,,,,,,,,,,,,
<30,0.981085,0.017677,59.130281,0.000000,0.256320,6.222379,0.000000,0.114902,0.194449,27.576454,0.000000,0.000000,0.883861,2.731130,1.873785,0.000000,0.017677
>30,0.873190,0.011267,60.931778,0.000000,0.163371,6.923554,0.000000,0.045068,0.228156,27.130866,0.000000,0.000000,0.664751,1.892851,1.121064,0.005633,0.008450
NO,1.256497,0.017134,52.407333,0.003808,0.186571,6.488092,0.003808,0.182763,0.106612,31.252499,0.001904,0.003808,0.894778,4.068384,3.101262,0.011423,0.013326

--- time_in_hospital ---

              count      mean       std  min  25%  50%  75%   max
readmitted
<30         11314.0  4.767545  3.027740  1.0  2.0  4.0  6.0  14.0
>30         35502.0  4.495521  2.988390  1.0  2.0  4.0  6.0  14.0
NO          52527.0  4.217184  2.930331  1.0  2.0  3.0  6.0  14.0

medical_specialty,AllergyandImmunology,Anesthesiology,Anesthesiology-Pediatric,Cardiology,Cardiology-Pediatric,DCPTEAM,Dentistry,Dermatology,Emergency/Trauma,Endocrinology,Endocrinology-Metabolism,Family/GeneralPractice,Gastroenterology,Gynecology,Hematology,Hematology/Oncology,Hospitalist,InfectiousDiseases,InternalMedicine,Missing,Nephrology,Neurology,Neurophysiology,Obsterics&Gynecology-GynecologicOnco,Obstetrics,ObstetricsandGynecology,Oncology,Ophthalmology,Orthopedics,Orthopedics-Reconstructive,Osteopath,Otolaryngology,OutreachServices,Pathology,Pediatrics,Pediatrics-AllergyandImmunology,Pediatrics-CriticalCare,Pediatrics-EmergencyMedicine,Pediatrics-Endocrinology,Pediatrics-Hematology-Oncology,Pediatrics-InfectiousDiseases,Pediatrics-Neurology,Pediatrics-Pulmonology,Perinatology,PhysicalMedicineandRehabilitation,PhysicianNotFound,Podiatry,Proctology,Psychiatry,Psychiatry-Addictive,Psychiatry-Child/Adolescent,Psychology,Pulmonology,Radiologist,Radiology,Resident,Rheumatology,Speech,SportsMedicine,Surgeon,Surgery-Cardiovascular,Surgery-Cardiovascular/Thoracic,Surgery-Colon&Rectal,Surgery-General,Surgery-Maxillofacial,Surgery-Neuro,Surgery-Pediatric,Surgery-Plastic,Surgery-PlasticwithinHeadandNeck,Surgery-Thoracic,Surgery-Vascular,SurgicalSpecialty,Urology
readmitted,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<30,0.026516,0.008839,0.008839,3.747569,0.008839,0.000000,0.000000,0.000000,7.468623,0.053032,0.008839,7.769136,0.539155,0.000000,0.229804,0.353544,0.035354,0.070709,14.512993,50.848506,2.191975,0.106063,0.000000,0.017677,0.008839,0.282835,0.565671,0.017677,1.334630,0.813152,0.026516,0.017677,0.008839,0.008839,0.141418,0.00000,0.026516,0.000000,0.008839,0.008839,0.000000,0.000000,0.017677,0.000000,0.530316,0.017677,0.088386,0.000000,0.919215,0.000000,0.008839,0.070709,0.848506,0.901538,0.070709,0.008839,0.026516,0.000000,0.000000,0.035354,0.053032,0.380060,0.008839,3.022804,0.008839,0.282835,0.000000,0.061870,0.000000,0.097225,0.654057,0.017677,0.592187
>30,0.008450,0.008450,0.014084,5.219424,0.011267,0.002817,0.008450,0.002817,8.461495,0.109853,0.002817,7.500986,0.599966,0.028167,0.067602,0.180272,0.053518,0.033801,13.292209,51.214016,1.875951,0.129570,0.000000,0.014084,0.005633,0.309842,0.281674,0.030984,0.921075,0.825306,0.050701,0.081686,0.014084,0.028167,0.222523,0.00845,0.078869,0.002817,0.064785,0.000000,0.002817,0.011267,0.047885,0.000000,0.264774,0.011267,0.135204,0.000000,0.737987,0.000000,0.005633,0.098586,0.923892,1.078812,0.039434,0.002817,0.014084,0.000000,0.002817,0.022534,0.067602,0.366177,0.008450,2.943496,0.005633,0.214072,0.005633,0.025351,0.002817,0.084502,0.563349,0.025351,0.521097
NO,0.001904,0.015230,0.024749,5.715156,0.003808,0.007615,0.001904,0.000000,6.796505,0.140880,0.011423,7.063034,0.502599,0.091382,0.047595,0.158014,0.064729,0.032364,14.994193,46.987264,1.189864,0.272241,0.001904,0.034268,0.030461,1.003294,0.295086,0.047595,1.740057,1.608696,0.032364,0.178956,0.011423,0.009519,0.300798,0.00000,0.106612,0.003808,0.257011,0.005711,0.000000,0.011423,0.011423,0.001904,0.451197,0.007615,0.079959,0.001904,0.927142,0.001904,0.007615,0.110419,0.818627,1.210806,0.059017,0.000000,0.017134,0.001904,0.000000,0.062825,0.129457,0.892874,0.013326,3.183125,0.011423,0.673939,0.011423,0.045691,0.000000,0.127553,0.477849,0.041883,0.818627

--- num_lab_procedures ---

              count       mean        std  min   25%   50%   75%    max
readmitted
<30         11314.0  44.222114  19.271325  1.0  33.0  45.0  58.0  132.0
>30         35502.0  43.835671  19.566701  1.0  32.0  45.0  58.0  129.0
NO          52527.0  41.995926  19.666373  1.0  30.0  43.0  56.0  126.0

--- num_procedures ---

              count      mean       std  min  25%  50%  75%  max
readmitted
<30         11314.0  1.282747  1.636575  0.0  0.0  1.0  2.0  6.0
>30         35502.0  1.250268  1.670056  0.0  0.0  1.0  2.0  6.0
NO          52527.0  1.402079  1.735477  0.0  0.0  1.0  2.0  6.0

--- num_medications ---

              count       mean       std  min   25%   50%   75%   max
readmitted
<30         11314.0  16.908874  8.098173  1.0  11.0  16.0  21.0  81.0
>30         35502.0  16.281195  7.617126  1.0  11.0  15.0  20.0  70.0
NO          52527.0  15.574581  8.377404  1.0  10.0  14.0  20.0  79.0

--- number_outpatient ---

              count      mean       std  min  25%  50%  75%   max
readmitted
<30         11314.0  0.436892  1.300220  0.0  0.0  0.0  0.0  40.0
>30         35502.0  0.496648  1.544775  0.0  0.0  0.0  0.0  42.0
NO          52527.0  0.268567  1.013956  0.0  0.0  0.0  0.0  36.0

--- number_emergency ---

              count      mean       std  min  25%  50%  75%   max
readmitted
<30         11314.0  0.357698  1.372257  0.0  0.0  0.0  0.0  64.0
>30         35502.0  0.283702  1.195545  0.0  0.0  0.0  0.0  76.0
NO          52527.0  0.106517  0.522156  0.0  0.0  0.0  0.0  37.0

--- number_inpatient ---

              count      mean       std  min  25%  50%  75%   max
readmitted
<30         11314.0  1.222733  1.955636  0.0  0.0  0.0  2.0  21.0
>30         35502.0  0.838995  1.393665  0.0  0.0  0.0  1.0  19.0
NO          52527.0  0.362842  0.831632  0.0  0.0  0.0  0.0  16.0

diag_1,10,11,110,112,114,115,117,131,133,135,136,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,170,171,172,173,174,175,179,180,182,183,184,185,187,188,189,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,207,208,210,211,212,214,215,216,217,218,219,220,223,225,226,227,228,229,23,230,233,235,236,237,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,261,262,263,266,27,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,31,310,311,312,314,318,320,322,323,324,325,327,331,332,333,334,335,336,337,338,34,340,341,342,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,36,360,361,362,363,365,366,368,369,370,372,373,374,375,376,377,378,379,38,380,381,382,383,384,385,386,388,389,39,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,461,462,463,464,465,466,47,470,471,473,474,475,477,478,48,480,481,482,483,485,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,518,519,52,521,522,523,524,526,527,528,529,53,530,531,532,533,534,535,536,537,54,540,541,542,543,550,551,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,58,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,61,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,632,633,634,637,640,641,642,643,644,645,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,671,674,680,681,682,683,684,685,686,690,691,692,693,694,695,696,698,7,70,700,703,704,705,706,707,708,709,710,711,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,745,746,747,75,751,753,756,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,803,805,806,807,808,810,812,813,814,815,816,817,82,820,821,822,823,824,825,826,827,831,832,833,834,835,836,837,838,839,84,840,842,843,844,845,846,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,873,875,878,879,88,880,881,882,883,885,886,890,891,892,893,895,897,9,903,904,906,911,913,914,915,916,917,919,920,921,922,923,924,928,933,934,935,936,939,94,941,942,944,945,952,955,957,958,959,962,963,964,965,966,967,968,969,97,970,971,972,973,974,975,976,977,98,980,982,983,986,987,988,989,990,991,992,994,995,996,997,998,999,E909,V07,V25,V26,V43,V45,V51,V53,V54,V55,V56,V57,V58,V60,V63,V66,V67,V70,V71
readmitted,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<30,0.000000,0.000000,0.000000,0.123795,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.017685,0.000000,0.000000,0.000000,0.044213,0.035370,0.035370,0.274118,0.061898,0.035370,0.008843,0.123795,0.008843,0.000000,0.008843,0.371386,0.008843,0.000000,0.000000,0.017685,0.008843,0.000000,0.097268,0.000000,0.008843,0.000000,0.061898,0.035370,0.000000,0.079583,0.000000,0.097268,0.088425,0.044213,0.000000,0.017685,0.000000,0.017685,0.026528,0.371386,0.291803,0.026528,0.035370,0.008843,0.176850,0.044213,0.061898,0.008843,0.000000,0.017685,0.000000,0.053055,0.000000,0.000000,0.000000,0.000000,0.000000,0.017685,0.000000,0.026528,0.000000,0.061898,0.000000,0.017685,0.000000,0.000000,0.008843,0.008843,0.008843,0.008843,0.000000,0.000000,0.061898,0.061898,0.000000,0.044213,0.035370,0.000000,0.000000,0.000000,0.141480,0.017685,0.468653,0.123795,0.327173,0.778141,0.336016,0.999204,0.061898,0.017685,0.088425,0.044213,0.017685,0.026528,0.017685,0.008843,0.194535,0.212220,0.176850,0.061898,0.000000,0.000000,0.000000,0.000000,1.936511,1.459015,1.582810,0.212220,0.557078,0.070740,0.000000,0.000000,0.079583,0.017685,0.017685,0.017685,0.044213,0.035370,0.000000,0.008843,0.035370,0.000000,0.008843,0.026528,0.000000,0.000000,0.097268,0.035370,2.254841,0.035370,0.185693,0.008843,0.282960,0.053055,0.123795,0.008843,0.088425,0.459811,0.035370,0.123795,0.123795,0.008843,0.079583,0.106110,0.132638,0.088425,0.168008,0.442126,0.910779,0.026528,0.123795,0.008843,0.000000,0.088425,0.000000,0.053055,0.000000,0.017685,0.017685,0.026528,0.000000,0.044213,0.008843,0.017685,0.061898,0.026528,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017685,0.203378,0.061898,0.035370,0.000000,0.000000,0.000000,0.000000,0.053055,0.017685,0.097268,0.017685,0.000000,0.000000,0.079583,0.035370,0.008843,0.194535,0.026528,0.000000,0.026528,0.008843,0.008843,0.000000,0.008843,0.008843,0.026528,0.017685,0.044213,0.026528,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017685,0.000000,0.000000,0.000000,0.000000,0.008843,0.000000,0.008843,0.000000,0.000000,0.000000,1.635865,0.008843,0.000000,0.008843,0.008843,0.000000,0.000000,0.035370,0.000000,0.000000,0.000000,0.008843,0.008843,0.000000,0.044213,0.008843,0.141480,0.318331,0.450968,0.689716,0.291803,0.000000,0.000000,3.280573,0.185693,0.000000,0.106110,5.243611,0.362543,0.044213,0.000000,0.044213,0.097268,0.053055,0.000000,0.097268,0.185693,0.053055,0.247590,2.219471,8.533027,0.053055,0.017685,0.088425,0.088425,0.689716,2.891502,0.689716,0.176850,0.088425,0.150323,1.176054,0.106110,0.026528,0.212220,0.221063,0.017685,0.017685,0.097268,0.000000,0.035370,0.008843,0.512866,0.000000,0.061898,0.017685,0.035370,0.362543,0.070740,0.008843,0.000000,0.000000,0.017685,0.035370,0.221063,0.017685,0.000000,0.000000,0.026528,0.000000,0.026528,0.000000,0.044213,0.008843,0.008843,0.026528,0.380228,0.000000,0.035370,2.776550,0.079583,0.000000,0.070740,2.537802,0.026528,0.866566,0.035370,0.000000,0.070740,0.008843,0.000000,0.000000,0.017685,0.795826,0.017685,0.008843,0.362543,0.070740,0.008843,0.079583,0.123795,0.035370,0.972677,0.044213,0.008843,0.000000,0.000000,0.000000,0.000000,0.026528,0.008843,0.000000,0.008843,0.061898,0.433283,0.203378,0.141480,0.017685,0.017685,0.344858,0.185693,0.159165,0.008843,0.061898,0.008843,0.000000,0.008843,0.053055,0.008843,0.185693,0.079583,0.026528,0.017685,0.159165,0.371386,0.804669,0.786984,0.150323,0.008843,0.008843,0.123795,0.026528,0.247590,0.000000,0.008843,0.389071,0.424441,0.026528,0.742771,0.221063,0.132638,1.246795,0.618976,0.000000,0.000000,0.008843,0.017685,0.000000,0.000000,1.777345,0.088425,0.044213,0.017685,0.203378,0.017685,0.309488,0.185693,0.017685,0.079583,0.026528,0.008843,1.494385,0.212220,0.000000,0.000000,0.000000,0.035370,0.000000,0.008843,0.079583,0.000000,0.000000,0.035370,0.008843,0.000000,0.000000,0.008843,0.044213,0.008843,0.008843,0.000000,0.000000,0.008843,0.026528,0.035370,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.053055,0.026528,0.035370,0.000000,0.026528,0.000000,0.185693,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.017685,0.008843,0.000000,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.114953,1.618180,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.000000,0.017685,0.008843,0.008843,0.017685,0.000000,0.000000,0.053055,0.000000,0.000000,0.000000,0.008843,0.000000,0.380228,0.000000,0.017685,0.026528,0.079583,0.053055,1.901141,0.044213,0.008843,0.026528,0.053055,0.000000,0.114953,0.442126,0.035370,0.353701,0.000000,0.026528,0.044213,0.123795,0.097268,0.265275,0.026528,0.000000,0.362543,0.000000,0.000000,0.017685,0.017685,0.044213,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.026528,0.000000,0.000000,1.680078,0.141480,0.053055,0.026528,0.079583,0.088425,2.564329,0.433283,0.053055,0.574763,0.070740,0.238748,0.000000,0.008843,0.000000,0.017685,0.000000,0.008843,0.000000,0.070740,0.627819,0.000000,0.017685,0.017685,0.000000,0.176850,0.008843,0.061898,0.194535,0.000000,0.212220,0.061898,0.000000,0.008843,0.008843,0.000000,0.026528,1.512070,0.141480,0.044213,0.123795,0.389071,0.017685,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.008843,0.000000,0.017685,0.026528,0.132638,0.026528,0.008843,0.053055,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.017685,0.000000,0.017685,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017685,0.000000,0.053055,0.000000,0.044213,0.008843,0.008843,0.000000,0.026528,0.000000,0.000000,0.017685,0.000000,0.008843,0.000000,0.000000,0.008843,0.000000,0.000000,0.008843,0.044213,0.079583,0.000000,0.017685,0.070740,0.035370,0.053055,0.008843,0.070740,0.000000,0.000000,0.008843,0.026528,0.008843,0.008843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.000000,0.000000,0.000000,0.000000,0.070740,2.334424,0.353701,0.769299,0.017685,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008843,0.017685,0.017685,0.008843,1.432487,0.840039,0.008843,0.008843,0.000000,0.000000,0.000000,0.000000
>30,0.000000,0.008451,0.002817,0.073244,0.002817,0.000000,0.011268,0.005634,0.000000,0.045073,0.002817,0.005634,0.005634,0.000000,0.002817,0.002817,0.002817,0.002817,0.000000,0.030988,0.045073,0.008451,0.273255,0.070427,0.022536,0.008451,0.036622,0.008451,0.000000,0.014085,0.259170,0.008451,0.000000,0.002817,0.014085,0.002817,0.002817,0.098597,0.008451,0.000000,0.000000,0.045073,0.014085,0.014085,0.104231,0.002817,0.132402,0.095780,0.016902,0.002817,0.019719,0.002817,0.005634,0.019719,0.166207,0.123951,0.000000,0.011268,0.005634,0.081695,0.033805,0.011268,0.005634,0.000000,0.002817,0.000000,0.101414,0.005634,0.002817,0.000000,0.000000,0.002817,0.056341,0.000000,0.011268,0.005634,0.022536,0.014085,0.028171,0.008451,0.000000,0.002817,0.002817,0.025354,0.005634,0.005634,0.002817,0.064792,0.016902,0.002817,0.025354,0.022536,0.011268,0.002817,0.002817,0.121134,0.025354,0.647924,0.132402,0.304242,0.715533,0.377486,0.833850,0.095780,0.011268,0.146487,0.028171,0.025354,0.014085,0.008451,0.016902,0.369035,0.101414,0.109865,0.025354,0.008451,0.000000,0.011268,0.005634,1.470505,0.887374,1.977576,0.188743,0.495803,0.112682,0.002817,0.002817,0.053524,0.014085,0.025354,0.019719,0.053524,0.022536,0.002817,0.000000,0.008451,0.002817,0.002817,0.000000,0.008451,0.000000,0.107048,0.039439,2.005747,0.053524,0.126768,0.000000,0.400023,0.014085,0.121134,0.033805,0.070427,0.388754,0.042256,0.076061,0.076061,0.014085,0.042256,0.073244,0.129585,0.067609,0.073244,0.543693,0.862020,0.011268,0.036622,0.000000,0.011268,0.095780,0.000000,0.078878,0.014085,0.016902,0.008451,0.025354,0.000000,0.025354,0.002817,0.005634,0.059158,0.019719,0.000000,0.000000,0.002817,0.000000,0.011268,0.005634,0.000000,0.014085,0.140853,0.061975,0.028171,0.002817,0.014085,0.002817,0.011268,0.014085,0.008451,0.045073,0.005634,0.002817,0.005634,0.104231,0.087329,0.000000,0.115499,0.033805,0.011268,0.005634,0.025354,0.000000,0.008451,0.008451,0.014085,0.002817,0.019719,0.005634,0.008451,0.002817,0.000000,0.005634,0.008451,0.000000,0.002817,0.002817,0.016902,0.005634,0.002817,0.002817,0.002817,0.002817,0.002817,0.011268,0.002817,0.002817,0.005634,1.555017,0.014085,0.000000,0.000000,0.014085,0.000000,0.000000,0.157755,0.005634,0.000000,0.002817,0.000000,0.002817,0.008451,0.011268,0.008451,0.152121,0.374669,0.476083,0.625387,0.338047,0.002817,0.011268,2.991718,0.267621,0.000000,0.107048,5.986253,0.371852,0.087329,0.000000,0.039439,0.036622,0.036622,0.002817,0.061975,0.132402,0.076061,0.228182,2.740999,8.687813,0.030988,0.008451,0.104231,0.045073,0.754972,1.653614,1.042312,0.154938,0.092963,0.067609,0.856386,0.109865,0.016902,0.135219,0.146487,0.008451,0.022536,0.070427,0.000000,0.047890,0.002817,0.512705,0.008451,0.104231,0.025354,0.005634,0.478900,0.104231,0.011268,0.005634,0.002817,0.002817,0.042256,0.256352,0.008451,0.000000,0.002817,0.025354,0.000000,0.005634,0.000000,0.022536,0.000000,0.019719,0.084512,0.363401,0.002817,0.045073,3.850921,0.098597,0.000000,0.098597,3.022706,0.036622,1.425432,0.039439,0.005634,0.107048,0.014085,0.005634,0.002817,0.002817,0.400023,0.002817,0.022536,0.239450,0.039439,0.011268,0.042256,0.132402,0.028171,1.028227,0.036622,0.000000,0.014085,0.039439,0.000000,0.000000,0.008451,0.016902,0.016902,0.002817,0.053524,0.492986,0.318328,0.191560,0.025354,0.019719,0.518339,0.157755,0.146487,0.008451,0.107048,0.002817,0.000000,0.000000,0.030988,0.005634,0.202828,0.123951,0.047890,0.042256,0.163389,0.354950,0.918362,1.022593,0.146487,0.011268,0.078878,0.064792,0.036622,0.326779,0.000000,0.005634,0.225365,0.250718,0.047890,0.800045,0.205645,0.104231,1.138092,0.735253,0.014085,0.005634,0.000000,0.022536,0.000000,0.014085,1.473322,0.084512,0.016902,0.014085,0.315511,0.019719,0.250718,0.087329,0.005634,0.109865,0.059158,0.000000,1.738126,0.163389,0.005634,0.000000,0.000000,0.039439,0.000000,0.022536,0.053524,0.000000,0.002817,0.022536,0.016902,0.005634,0.030988,0.019719,0.078878,0.000000,0.042256,0.011268,0.000000,0.002817,0.025354,0.025354,0.002817,0.002817,0.000000,0.002817,0.000000,0.002817,0.005634,0.025354,0.002817,0.008451,0.000000,0.008451,0.005634,0.197194,0.000000,0.002817,0.000000,0.014085,0.000000,0.008451,0.000000,0.011268,0.005634,0.011268,0.002817,0.005634,0.002817,0.000000,0.000000,0.002817,0.000000,0.000000,0.008451,0.118317,2.180405,0.000000,0.000000,0.002817,0.011268,0.000000,0.000000,0.005634,0.039439,0.005634,0.014085,0.005634,0.002817,0.002817,0.045073,0.002817,0.002817,0.002817,0.016902,0.002817,0.281706,0.008451,0.011268,0.022536,0.067609,0.047890,1.600090,0.047890,0.008451,0.008451,0.061975,0.000000,0.143670,0.523973,0.064792,0.397205,0.014085,0.084512,0.033805,0.109865,0.118317,0.304242,0.000000,0.000000,0.419742,0.002817,0.002817,0.014085,0.002817,0.039439,0.011268,0.000000,0.002817,0.002817,0.005634,0.005634,0.005634,0.002817,0.005634,2.056454,0.095780,0.061975,0.019719,0.169024,0.064792,3.994591,0.284523,0.045073,0.633839,0.073244,0.118317,0.000000,0.005634,0.000000,0.016902,0.002817,0.002817,0.002817,0.087329,0.543693,0.002817,0.016902,0.025354,0.002817,0.185926,0.005634,0.061975,0.115499,0.005634,0.188743,0.047890,0.000000,0.000000,0.005634,0.000000,0.000000,0.836667,0.104231,0.022536,0.090146,0.216914,0.016902,0.005634,0.002817,0.000000,0.000000,0.000000,0.000000,0.005634,0.002817,0.002817,0.002817,0.002817,0.000000,0.025354,0.000000,0.008451,0.011268,0.019719,0.002817,0.019719,0.000000,0.019719,0.028171,0.047890,0.014085,0.000000,0.014085,0.002817,0.000000,0.002817,0.008451,0.000000,0.005634,0.011268,0.002817,0.000000,0.000000,0.016902,0.000000,0.005634,0.002817,0.005634,0.000000,0.002817,0.000000,0.002817,0.000000,0.005634,0.005634,0.014085,0.016902,0.005634,0.002817,0.000000,0.064792,0.000000,0.000000,0.000000,0.000000,0.000000,0.002817,0.000000,0.008451,0.005634,0.002817,0.028171,0.000000,0.030988,0.005634,0.081695,0.002817,0.019719,0.005634,0.005634,0.002817,0.000000,0.002817,0.000000,0.008451,0.005634,0.011268,0.008451,0.000000,0.000000,0.011268,0.036622,0.042256,0.002817,0.000000,0.042256,0.008451,0.014085,0.008451,0.064792,0.002817,0.005634,0.005634,0.016902,0.000000,0.000000,0.002817,0.000000,0.011268,0.000000,0.005634,0.000000,0.005634,0.000000,0.005634,0.002817,0.005634,0.005634,0.008451,0.008451,0.000000,0.076061,2.166319,0.416925,0.740887,0.028171,0.000000,0.000000,0.002817,0.000000,0.002817,0.002817,0.000000,0.028171,0.042256,0.081695,0.022536,1.197251,0.188743,0.000000,0.002817,0.000000,0.002817,0.000000,0.005634

diag_2,11,110,111,112,114,115,117,123,131,135,136,137,138,140,141,145,150,151,152,153,154,155,156,157,162,163,164,171,172,173,174,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,212,214,215,217,218,220,223,225,226,227,228,232,233,235,238,239,240,241,242,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.32,250.33,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,266,268,269,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,31,310,311,312,314,316,317,318,319,320,322,323,324,325,327,331,332,333,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,352,353,354,355,356,357,358,359,360,362,364,365,366,368,369,372,373,374,376,377,378,379,38,380,381,382,383,386,388,389,394,395,396,397,398,40,401,402,403,404,405,41,410,411,412,413,414,415,416,42,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,446,447,448,451,452,453,454,455,456,457,458,459,46,460,461,462,463,464,465,466,470,472,473,474,475,477,478,480,481,482,483,484,485,486,487,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,513,514,515,516,517,518,519,52,520,521,522,523,524,527,528,529,53,530,531,532,533,534,535,536,537,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,583,584,585,586,588,590,591,592,593,594,595,596,598,599,600,601,602,603,604,605,607,608,610,611,614,615,616,617,618,619,620,621,622,623,625,626,627,634,641,642,644,645,646,647,648,649,652,654,656,658,659,66,661,663,664,665,670,674,680,681,682,683,684,685,686,691,692,693,694,695,696,698,7,70,701,702,703,704,705,706,707,709,710,711,712,713,714,715,716,717,718,719,721,722,723,724,725,726,727,728,729,730,731,733,734,736,737,738,741,742,745,746,747,748,75,750,751,752,753,754,755,756,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,806,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,832,833,836,837,840,842,843,844,845,846,847,850,851,852,853,860,861,862,863,864,865,866,867,868,869,870,871,872,873,879,88,880,881,882,883,884,891,892,893,894,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,927,933,934,94,942,944,945,947,948,952,953,955,958,959,96,962,963,965,967,968,969,972,974,975,977,980,987,989,99,990,991,992,994,995,996,997,998,999,E812,E813,E814,E816,E817,E818,E819,E821,E826,E829,E849,E850,E853,E854,E858,E868,E870,E878,E879,E880,E881,E882,E883,E884,E885,E887,E888,E890,E900,E905,E906,E915,E916,E917,E918,E919,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E944,E945,E947,E950,E965,E968,E980,V02,V03,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V23,V25,V42,V43,V44,V45,V46,V49,V50,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V69,V70,V72,V85,V86
readmitted,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<30,0.008861,0.017723,0.000000,0.248117,0.008861,0.000000,0.008861,0.000000,0.000000,0.132920,0.026584,0.000000,0.017723,0.000000,0.000000,0.000000,0.088613,0.017723,0.053168,0.168365,0.053168,0.008861,0.044307,0.106336,0.513957,0.000000,0.000000,0.000000,0.008861,0.000000,0.017723,0.008861,0.000000,0.000000,0.026584,0.008861,0.008861,0.000000,0.035445,0.017723,0.000000,0.008861,0.000000,0.212672,0.505095,0.425343,0.008861,0.035445,0.026584,0.381037,0.168365,0.124058,0.141781,0.008861,0.053168,0.000000,0.008861,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.026584,0.000000,0.000000,0.000000,0.106336,0.150642,0.008861,0.000000,3.943288,1.736819,1.949490,0.327869,0.053168,0.062029,0.124058,0.177226,0.008861,0.008861,0.026584,0.000000,0.000000,0.008861,0.000000,0.000000,0.186088,0.505095,0.124058,0.088613,0.079752,0.079752,0.106336,0.053168,1.284891,0.248117,0.194949,0.141781,0.203810,0.044307,0.000000,0.000000,0.186088,0.026584,0.000000,0.008861,0.017723,0.106336,0.000000,0.008861,0.000000,0.017723,0.017723,0.008861,0.168365,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.177226,0.000000,0.008861,0.000000,7.159947,0.044307,0.124058,0.008861,0.567125,0.026584,0.035445,0.026584,0.141781,1.249446,0.097475,0.283562,0.062029,0.000000,0.053168,0.044307,0.150642,0.097475,0.141781,0.327869,0.230394,0.008861,0.026584,0.000000,0.106336,0.026584,0.000000,0.319008,0.239256,0.567125,0.000000,0.035445,0.000000,0.035445,0.000000,0.000000,0.106336,0.017723,0.000000,0.000000,0.000000,0.000000,0.026584,0.017723,0.000000,0.000000,0.000000,0.000000,0.000000,0.088613,0.088613,0.000000,0.017723,0.008861,0.088613,0.017723,0.000000,0.124058,0.008861,0.451927,0.008861,0.044307,0.062029,0.008861,0.000000,0.159504,0.044307,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.070891,0.035445,0.000000,0.000000,0.008861,0.008861,0.000000,0.000000,0.026584,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.540541,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.026584,0.000000,0.168365,0.053168,0.035445,0.000000,2.374834,0.327869,3.792645,0.230394,0.008861,0.283562,0.567125,2.197607,0.053168,0.770935,1.949490,0.088613,0.079752,0.088613,0.008861,0.017723,0.000000,0.008861,0.974745,1.533008,0.203810,4.971201,7.425786,0.000000,0.000000,0.017723,0.026584,0.186088,0.230394,0.079752,0.017723,0.062029,0.265840,0.726628,0.026584,0.008861,0.079752,0.132920,0.044307,0.035445,0.000000,0.017723,0.017723,0.434205,0.017723,0.008861,0.088613,0.008861,0.115197,0.035445,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.097475,0.070891,0.000000,0.000000,0.008861,0.008861,0.000000,0.000000,0.008861,0.008861,0.017723,0.088613,0.000000,0.008861,0.000000,1.258307,0.008861,0.026584,1.781125,0.221533,0.620292,0.017723,0.008861,3.243243,0.000000,0.017723,0.000000,0.000000,0.124058,0.000000,0.008861,0.575986,0.035445,0.008861,0.008861,0.141781,0.044307,0.000000,1.214001,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.008861,0.000000,0.035445,0.283562,0.053168,0.035445,0.008861,0.000000,0.186088,0.345591,0.062029,0.008861,0.000000,0.000000,0.000000,0.000000,0.044307,0.026584,0.008861,0.017723,0.017723,0.062029,0.354453,0.097475,0.070891,0.008861,0.008861,0.079752,0.026584,0.150642,0.026584,0.567125,0.150642,0.079752,0.239256,0.035445,0.079752,0.558263,0.336730,0.000000,0.000000,0.079752,0.017723,1.665928,2.392556,0.008861,0.000000,0.132920,0.194949,0.079752,0.141781,0.008861,0.070891,0.088613,0.000000,3.260966,0.008861,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.026584,0.000000,0.017723,0.008861,0.000000,0.008861,0.008861,0.008861,0.017723,0.008861,0.000000,0.000000,0.000000,0.053168,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.124058,0.008861,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026584,0.053168,1.683651,0.000000,0.008861,0.000000,0.000000,0.000000,0.008861,0.008861,0.000000,0.000000,0.008861,0.000000,0.000000,0.327869,0.000000,0.000000,0.000000,0.000000,0.017723,0.000000,2.507754,0.008861,0.132920,0.044307,0.008861,0.000000,0.035445,0.062029,0.017723,0.008861,0.000000,0.053168,0.088613,0.106336,0.026584,0.150642,0.000000,0.017723,0.026584,0.070891,0.053168,0.274701,0.088613,0.256978,0.000000,0.017723,0.000000,0.026584,0.000000,0.017723,0.017723,0.008861,0.008861,0.000000,0.000000,0.017723,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.293753,0.097475,0.008861,0.008861,0.203810,0.682322,0.416482,0.177226,0.336730,0.398759,0.008861,0.274701,0.000000,0.017723,0.000000,0.044307,0.000000,0.008861,0.000000,0.345591,0.248117,0.000000,0.000000,0.044307,0.070891,0.000000,0.000000,0.079752,0.000000,0.000000,0.035445,0.017723,0.000000,0.000000,0.000000,0.115197,0.017723,0.000000,0.008861,0.017723,0.017723,0.017723,0.008861,0.000000,0.000000,0.000000,0.000000,0.017723,0.000000,0.000000,0.000000,0.017723,0.000000,0.000000,0.026584,0.000000,0.008861,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.026584,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.008861,0.008861,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.026584,0.000000,0.008861,0.000000,0.017723,0.000000,0.008861,0.017723,0.026584,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026584,0.017723,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.008861,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.177226,0.593708,0.363314,0.558263,0.008861,0.000000,0.000000,0.008861,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.070891,0.000000,0.000000,0.000000,0.008861,0.000000,0.000000,0.150642,0.035445,0.026584,0.000000,0.000000,0.000000,0.026584,0.150642,0.000000,0.186088,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.000000,0.008861,0.000000,0.008861,0.000000,0.035445,0.000000,0.008861,0.017723,0.008861,0.008861,0.000000,0.008861,0.000000,0.017723,0.000000,0.008861,0.035445,0.035445,0.000000,0.000000,0.000000,0.000000,0.000000,0.008861,0.026584,0.026584,0.000000,0.062029,0.000000,0.000000,0.106336,0.000000,0.008861,0.008861,0.000000,0.000000,0.256978,0.070891,0.017723,0.354453,0.000000,0.079752,0.000000,0.000000,0.062029,0.000000,0.000000,0.177226,0.000000,0.008861,0.062029,0.044307,0.026584,0.008861,0.000000,0.000000,0.000000,0.000000,0.194949,0.000000
>30,0.002823,0.008468,0.000000,0.211697,0.000000,0.002823,0.011291,0.000000,0.000000,0.129841,0.000000,0.000000,0.028226,0.000000,0.005645,0.000000,0.031049,0.022581,0.008468,0.104437,0.059275,0.031049,0.008468,0.047985,0.287908,0.000000,0.000000,0.002823,0.005645,0.000000,0.028226,0.000000,0.000000,0.002823,0.019758,0.019758,0.000000,0.002823,0.056453,0.011291,0.000000,0.000000,0.000000,0.191939,0.276617,0.237101,0.008468,0.019758,0.016936,0.175003,0.064920,0.132663,0.062098,0.000000,0.039517,0.000000,0.005645,0.002823,0.002823,0.022581,0.002823,0.002823,0.005645,0.002823,0.002823,0.000000,0.002823,0.005645,0.000000,0.014113,0.000000,0.000000,0.011291,0.104437,0.110082,0.002823,0.002823,4.739189,1.479056,2.133905,0.270972,0.008468,0.087501,0.081856,0.093147,0.005645,0.002823,0.053630,0.000000,0.002823,0.000000,0.000000,0.008468,0.222987,0.256859,0.138309,0.047985,0.062098,0.062098,0.053630,0.031049,0.987919,0.149599,0.248391,0.121373,0.208874,0.050807,0.002823,0.002823,0.191939,0.028226,0.011291,0.014113,0.045162,0.062098,0.002823,0.002823,0.000000,0.005645,0.014113,0.011291,0.124196,0.014113,0.000000,0.000000,0.002823,0.002823,0.000000,0.307666,0.008468,0.022581,0.031049,6.748899,0.093147,0.222987,0.011291,0.643559,0.014113,0.059275,0.019758,0.175003,1.419781,0.132663,0.302021,0.081856,0.050807,0.025404,0.064920,0.093147,0.059275,0.104437,0.383877,0.107260,0.005645,0.008468,0.002823,0.155244,0.084679,0.000000,0.318957,0.206052,0.637914,0.002823,0.002823,0.002823,0.053630,0.002823,0.002823,0.073388,0.019758,0.008468,0.000000,0.016936,0.005645,0.016936,0.002823,0.005645,0.002823,0.011291,0.000000,0.047985,0.081856,0.053630,0.016936,0.005645,0.000000,0.033872,0.008468,0.014113,0.127018,0.002823,0.141131,0.005645,0.070566,0.039517,0.033872,0.000000,0.059275,0.016936,0.000000,0.000000,0.002823,0.002823,0.000000,0.014113,0.005645,0.014113,0.073388,0.025404,0.005645,0.002823,0.033872,0.000000,0.011291,0.005645,0.028226,0.014113,0.005645,0.002823,0.000000,0.002823,0.002823,0.011291,0.000000,0.451620,0.011291,0.002823,0.014113,0.002823,0.016936,0.002823,0.002823,0.019758,0.002823,0.231455,0.087501,0.025404,0.022581,2.921418,0.335893,3.627075,0.251214,0.002823,0.383877,0.508073,2.605284,0.070566,1.066953,2.537541,0.098792,0.112905,0.076211,0.019758,0.019758,0.000000,0.019758,1.083888,1.673817,0.279440,5.162583,7.547702,0.028226,0.008468,0.005645,0.011291,0.132663,0.146777,0.090324,0.011291,0.047985,0.265327,0.372587,0.042339,0.014113,0.087501,0.121373,0.019758,0.022581,0.008468,0.036694,0.002823,0.273795,0.005645,0.036694,0.064920,0.008468,0.127018,0.079034,0.000000,0.000000,0.005645,0.011291,0.000000,0.002823,0.045162,0.127018,0.002823,0.000000,0.042339,0.000000,0.002823,0.002823,0.031049,0.008468,0.036694,0.093147,0.005645,0.002823,0.005645,1.357683,0.016936,0.084679,1.964548,0.191939,0.948402,0.011291,0.005645,3.771029,0.002823,0.005645,0.008468,0.002823,0.129841,0.005645,0.008468,0.462911,0.036694,0.011291,0.005645,0.163712,0.014113,0.016936,1.137518,0.047985,0.002823,0.000000,0.000000,0.000000,0.000000,0.000000,0.008468,0.008468,0.000000,0.028226,0.228633,0.031049,0.016936,0.011291,0.000000,0.239923,0.251214,0.022581,0.002823,0.011291,0.000000,0.002823,0.016936,0.039517,0.070566,0.016936,0.011291,0.031049,0.121373,0.296376,0.124196,0.093147,0.014113,0.014113,0.107260,0.056453,0.166535,0.014113,0.513718,0.050807,0.039517,0.251214,0.064920,0.081856,0.409281,0.316134,0.011291,0.000000,0.115728,0.025404,1.583493,2.311731,0.011291,0.002823,0.104437,0.194761,0.070566,0.129841,0.000000,0.081856,0.045162,0.002823,3.274246,0.050807,0.022581,0.002823,0.000000,0.002823,0.000000,0.011291,0.008468,0.002823,0.025404,0.019758,0.000000,0.011291,0.011291,0.011291,0.005645,0.011291,0.000000,0.002823,0.002823,0.014113,0.014113,0.011291,0.002823,0.000000,0.019758,0.002823,0.000000,0.000000,0.000000,0.098792,0.000000,0.005645,0.000000,0.000000,0.000000,0.000000,0.002823,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.022581,0.045162,1.625833,0.000000,0.011291,0.011291,0.002823,0.002823,0.002823,0.014113,0.014113,0.005645,0.016936,0.002823,0.002823,0.245568,0.002823,0.000000,0.000000,0.000000,0.011291,0.016936,2.306086,0.008468,0.175003,0.050807,0.005645,0.005645,0.033872,0.112905,0.002823,0.005645,0.002823,0.115728,0.050807,0.098792,0.039517,0.087501,0.002823,0.022581,0.022581,0.129841,0.093147,0.287908,0.098792,0.191939,0.000000,0.016936,0.005645,0.019758,0.011291,0.000000,0.011291,0.011291,0.002823,0.000000,0.002823,0.002823,0.002823,0.000000,0.011291,0.000000,0.000000,0.002823,0.011291,0.000000,0.005645,1.484701,0.118550,0.062098,0.019758,0.158067,0.420571,0.609687,0.172180,0.333070,0.313312,0.019758,0.265327,0.002823,0.019758,0.000000,0.039517,0.000000,0.005645,0.002823,0.282263,0.228633,0.000000,0.000000,0.011291,0.081856,0.000000,0.025404,0.028226,0.000000,0.002823,0.033872,0.000000,0.002823,0.002823,0.005645,0.028226,0.008468,0.002823,0.011291,0.005645,0.008468,0.005645,0.000000,0.000000,0.000000,0.005645,0.000000,0.014113,0.000000,0.000000,0.002823,0.005645,0.002823,0.002823,0.011291,0.005645,0.005645,0.000000,0.008468,0.002823,0.008468,0.000000,0.002823,0.000000,0.000000,0.008468,0.002823,0.000000,0.000000,0.000000,0.000000,0.019758,0.002823,0.000000,0.000000,0.005645,0.005645,0.008468,0.002823,0.002823,0.005645,0.002823,0.000000,0.002823,0.011291,0.000000,0.000000,0.002823,0.005645,0.002823,0.002823,0.002823,0.000000,0.000000,0.002823,0.002823,0.002823,0.002823,0.016936,0.008468,0.002823,0.011291,0.019758,0.000000,0.002823,0.000000,0.042339,0.000000,0.000000,0.005645,0.000000,0.000000,0.000000,0.000000,0.000000,0.011291,0.016936,0.000000,0.000000,0.002823,0.005645,0.002823,0.002823,0.005645,0.002823,0.002823,0.000000,0.002823,0.000000,0.002823,0.000000,0.000000,0.000000,0.005645,0.002823,0.002823,0.087501,0.471379,0.287908,0.445975,0.022581,0.005645,0.002823,0.000000,0.002823,0.002823,0.002823,0.002823,0.000000,0.000000,0.002823,0.056453,0.000000,0.005645,0.002823,0.000000,0.000000,0.002823,0.110082,0.016936,0.002823,0.005645,0.000000,0.000000,0.014113,0.062098,0.005645,0.090324,0.000000,0.002823,0.000000,0.000000,0.002823,0.000000,0.002823,0.000000,0.000000,0.000000,0.005645,0.022581,0.002823,0.005645,0.002823,0.033872,0.008468,0.016936,0.031049,0.014113,0.002823,0.000000,0.014113,0.005645,0.045162,0.014113,0.000000,0.036694,0.005645,0.000000,0.000000,0.000000,0.005645,0.000000,0.005645,0.008468,0.087501,0.000000,0.059275,0.000000,0.000000,0.129841,0.000000,0.008468,0.000000,0.000000,0.000000,0.265327,0.132663,0.016936,0.389522,0.019758,0.056453,0.000000,0.002823,0.079034,0.002823,0.016936,0.177825,0.000000,0.000000,0.042339,0.011291,0.011291,0.011291,0.002823,0.000000,0.008468,0.002823,0.101615,0.002823

diag_3,11,110,111,112,115,117,122,123,131,132,135,136,138,139,14,141,146,148,150,151,152,153,154,155,156,157,158,161,162,163,164,17,170,171,172,173,174,175,179,180,182,183,185,186,188,189,191,192,193,195,196,197,198,199,200,201,202,203,204,205,208,211,214,215,216,217,218,220,223,225,226,227,228,230,233,235,236,238,239,240,241,242,243,244,245,246,250,250.01,250.02,250.03,250.1,250.11,250.12,250.13,250.2,250.21,250.22,250.23,250.3,250.31,250.4,250.41,250.42,250.43,250.5,250.51,250.52,250.53,250.6,250.7,250.8,250.81,250.82,250.83,250.9,250.91,250.92,250.93,251,252,253,255,256,258,259,260,261,262,263,265,266,268,27,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,3,300,301,303,304,305,306,307,308,309,310,311,312,313,314,315,317,318,319,323,327,331,332,333,334,335,336,337,338,34,340,341,342,343,344,345,346,347,348,349,35,350,351,353,354,355,356,357,358,359,360,361,362,365,365.44,366,368,369,370,372,373,374,376,377,378,379,38,380,381,382,383,384,385,386,387,388,389,391,394,395,396,397,398,401,402,403,404,405,41,410,411,412,413,414,415,416,417,42,420,421,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,440,441,442,443,444,445,446,447,448,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,47,470,472,473,475,477,478,480,481,482,483,484,486,487,49,490,491,492,493,494,495,496,5,500,501,506,507,508,510,511,512,514,515,516,517,518,519,521,522,523,524,525,527,528,529,53,530,531,532,533,534,535,536,537,538,54,540,542,543,550,552,553,555,556,557,558,560,562,564,565,566,567,568,569,57,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,588,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,607,608,610,611,614,616,617,618,619,620,621,622,623,624,625,626,627,641,642,643,644,646,647,648,649,652,653,654,655,656,657,658,659,66,660,661,663,664,665,669,670,671,674,680,681,682,684,685,686,690,692,693,694,695,696,697,698,7,70,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,741,742,744,745,746,747,75,750,751,752,753,754,755,756,757,758,759,78,780,781,782,783,784,785,786,787,788,789,79,790,791,792,793,794,795,796,797,799,8,800,801,802,805,807,808,810,811,812,813,814,815,816,820,821,822,823,824,825,826,831,834,836,837,838,840,841,842,844,845,847,848,850,851,852,853,854,860,861,862,863,864,865,866,867,868,870,871,872,873,875,876,877,879,88,880,881,882,883,884,890,891,892,893,9,905,906,907,908,909,910,911,912,913,915,916,917,918,919,920,921,922,923,924,928,930,933,934,935,94,943,944,945,948,951,952,953,955,956,958,959,962,965,966,967,969,970,971,972,980,987,989,991,992,995,996,997,998,999,E812,E813,E815,E816,E817,E818,E819,E822,E825,E826,E828,E849,E850,E852,E853,E854,E855,E858,E861,E864,E865,E870,E876,E878,E879,E880,E881,E882,E883,E884,E885,E886,E887,E888,E892,E894,E900,E901,E904,E905,E906,E912,E915,E916,E917,E919,E920,E922,E924,E927,E928,E929,E930,E931,E932,E933,E934,E935,E936,E937,E938,E939,E941,E942,E943,E944,E945,E946,E947,E949,E950,E956,E965,E966,E980,E987,V01,V02,V03,V06,V07,V08,V09,V10,V11,V12,V13,V14,V15,V16,V17,V18,V22,V23,V25,V27,V42,V43,V44,V45,V46,V49,V53,V54,V55,V57,V58,V60,V61,V62,V63,V64,V65,V66,V70,V72,V85,V86
readmitted,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<30,0.00891,0.017821,0.00891,0.196026,0.00000,0.026731,0.00000,0.00000,0.008910,0.000000,0.044551,0.000000,0.053462,0.000000,0.00000,0.008910,0.000000,0.000000,0.026731,0.000000,0.00891,0.062372,0.017821,0.026731,0.026731,0.053462,0.00891,0.000000,0.258398,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.080192,0.00000,0.008910,0.000000,0.000000,0.017821,0.044551,0.000000,0.017821,0.026731,0.000000,0.00891,0.00000,0.000000,0.151475,0.596988,0.231667,0.062372,0.017821,0.008910,0.133654,0.044551,0.062372,0.008910,0.008910,0.106923,0.000000,0.00891,0.000000,0.00000,0.035641,0.000000,0.00891,0.008910,0.000000,0.000000,0.000000,0.000000,0.008910,0.000000,0.00891,0.071282,0.000000,0.000000,0.008910,0.062372,0.000000,0.400962,0.000000,0.000000,8.767709,0.997951,1.603849,0.151475,0.008910,0.026731,0.053462,0.008910,0.000000,0.000000,0.008910,0.000000,0.000000,0.00000,0.570258,0.285129,0.276218,0.089103,0.115834,0.196026,0.080192,0.071282,1.710773,0.231667,0.400962,0.089103,0.151475,0.035641,0.008910,0.017821,0.169295,0.017821,0.008910,0.035641,0.026731,0.142564,0.008910,0.000000,0.000000,0.000000,0.035641,0.008910,0.338590,0.00000,0.017821,0.000000,0.00000,0.000000,0.00000,1.193977,0.035641,0.035641,0.071282,5.355074,0.035641,0.454424,0.017821,0.454424,0.035641,0.044551,0.026731,0.231667,1.122694,0.169295,0.347501,0.080192,0.026731,0.044551,0.044551,0.080192,0.071282,0.365321,0.329680,0.240577,0.008910,0.053462,0.000000,0.000000,0.267308,0.106923,0.213847,0.258398,0.712822,0.008910,0.000000,0.000000,0.062372,0.026731,0.187116,0.044551,0.008910,0.008910,0.00000,0.000000,0.008910,0.026731,0.000000,0.035641,0.249488,0.106923,0.017821,0.008910,0.000000,0.008910,0.106923,0.035641,0.000000,0.062372,0.008910,0.294039,0.026731,0.026731,0.044551,0.044551,0.008910,0.044551,0.017821,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008910,0.525706,0.000000,0.000000,0.000000,0.00000,0.053462,0.026731,0.00891,0.000000,0.017821,0.008910,0.00000,0.008910,0.000000,0.000000,0.000000,0.000000,0.008910,0.008910,0.160385,0.008910,0.00000,0.017821,0.008910,0.000000,0.00000,0.000000,0.00000,0.000000,0.008910,0.00891,0.026731,0.00000,0.294039,0.106923,0.035641,6.130268,0.240577,3.421545,0.160385,0.008910,0.516796,0.169295,0.347501,0.302949,0.196026,3.011672,0.035641,0.169295,0.000000,0.071282,0.017821,0.000000,0.017821,0.971220,1.158336,0.222757,4.080905,4.963022,0.053462,0.00000,0.000000,0.008910,0.151475,0.062372,0.053462,0.008910,0.071282,0.383142,0.302949,0.053462,0.017821,0.213847,0.071282,0.000000,0.026731,0.071282,0.000000,0.008910,0.017821,0.329680,0.000000,0.053462,0.035641,0.026731,0.222757,0.115834,0.000000,0.017821,0.008910,0.00000,0.000000,0.044551,0.080192,0.00000,0.000000,0.000000,0.017821,0.000000,0.017821,0.008910,0.000000,0.000000,0.062372,0.000000,0.000000,0.650450,0.017821,0.00891,0.017821,0.588078,0.133654,0.659360,0.017821,0.000000,3.091865,0.000000,0.000000,0.008910,0.017821,0.089103,0.000000,0.000000,0.561347,0.044551,0.008910,0.142564,0.000000,0.035641,0.944489,0.026731,0.026731,0.026731,0.008910,0.00891,0.000000,0.000000,0.008910,0.000000,0.035641,0.490065,0.044551,0.035641,0.017821,0.008910,0.258398,0.588078,0.000000,0.00000,0.000000,0.00000,0.00000,0.000000,0.008910,0.017821,0.080192,0.017821,0.000000,0.035641,0.115834,0.338590,0.169295,0.115834,0.000000,0.000000,0.017821,0.035641,0.124744,0.00000,0.017821,0.365321,0.062372,0.071282,0.124744,0.035641,0.053462,0.249488,0.311860,0.000000,0.017821,0.267308,0.017821,0.089103,1.131605,2.984942,0.008910,0.017821,0.035641,0.142564,0.062372,0.311860,0.000000,0.062372,0.124744,0.008910,0.017821,2.111735,0.044551,0.008910,0.00891,0.000000,0.008910,0.008910,0.017821,0.017821,0.000000,0.000000,0.035641,0.008910,0.017821,0.008910,0.017821,0.000000,0.000000,0.000000,0.000000,0.000000,0.017821,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008910,0.000000,0.080192,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.008910,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.00000,0.008910,0.089103,1.006861,0.000000,0.000000,0.017821,0.000000,0.008910,0.017821,0.000000,0.026731,0.017821,0.00000,0.008910,0.000000,0.356411,0.000000,0.000000,0.000000,0.000000,0.008910,0.000000,1.782055,0.008910,0.008910,0.106923,0.044551,0.008910,0.017821,0.062372,0.178205,0.071282,0.000000,0.000000,0.133654,0.000000,0.044551,0.098013,0.053462,0.115834,0.008910,0.017821,0.044551,0.098013,0.160385,0.196026,0.089103,0.00000,0.258398,0.000000,0.000000,0.000000,0.008910,0.000000,0.008910,0.000000,0.00891,0.008910,0.000000,0.000000,0.000000,0.00891,0.008910,0.000000,0.008910,0.00000,0.00891,0.017821,0.00000,0.000000,0.000000,0.000000,1.309810,0.169295,0.115834,0.062372,0.320770,0.641540,0.534616,0.276218,0.347501,0.427693,0.044551,0.240577,0.017821,0.008910,0.000000,0.106923,0.000000,0.000000,0.000000,0.329680,0.285129,0.00000,0.008910,0.017821,0.044551,0.071282,0.017821,0.000000,0.000000,0.026731,0.017821,0.000000,0.000000,0.008910,0.035641,0.000000,0.000000,0.008910,0.017821,0.000000,0.000000,0.000000,0.00000,0.000000,0.00891,0.00891,0.008910,0.00000,0.000000,0.008910,0.000000,0.000000,0.000000,0.000000,0.000000,0.00891,0.00000,0.008910,0.000000,0.008910,0.000000,0.000000,0.000000,0.000000,0.000000,0.017821,0.000000,0.000000,0.00000,0.00000,0.017821,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00891,0.008910,0.017821,0.000000,0.000000,0.000000,0.000000,0.000000,0.008910,0.026731,0.000000,0.000000,0.000000,0.017821,0.000000,0.000000,0.008910,0.000000,0.000000,0.035641,0.008910,0.008910,0.000000,0.026731,0.000000,0.00000,0.000000,0.008910,0.00000,0.008910,0.000000,0.00000,0.008910,0.000000,0.00000,0.00000,0.000000,0.00000,0.000000,0.008910,0.008910,0.000000,0.008910,0.000000,0.00891,0.017821,0.00000,0.00000,0.00000,0.00891,0.00000,0.00891,0.008910,0.00000,0.294039,0.427693,0.267308,0.347501,0.017821,0.008910,0.000000,0.00000,0.017821,0.008910,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.204936,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00891,0.133654,0.062372,0.035641,0.000000,0.00000,0.00000,0.026731,0.098013,0.00000,0.008910,0.133654,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00891,0.00000,0.000000,0.008910,0.000000,0.000000,0.00891,0.000000,0.017821,0.008910,0.008910,0.008910,0.008910,0.071282,0.017821,0.017821,0.035641,0.008910,0.008910,0.000000,0.035641,0.000000,0.071282,0.000000,0.044551,0.000000,0.00891,0.035641,0.00000,0.035641,0.008910,0.000000,0.00000,0.000000,0.00000,0.000000,0.008910,0.000000,0.000000,0.000000,0.017821,0.062372,0.133654,0.000000,0.285129,0.000000,0.008910,0.320770,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.276218,0.169295,0.017821,1.176156,0.080192,0.098013,0.000000,0.035641,0.017821,0.000000,0.427693,0.017821,0.000000,0.017821,0.008910,0.071282,0.026731,0.000000,0.000000,0.008910,0.080192,0.000000
>30,0.00000,0.017063,0.00000,0.207599,0.00000,0.005688,0.00000,0.00000,0.000000,0.005688,0.068252,0.000000,0.008531,0.002844,0.00000,0.005688,0.002844,0.002844,0.000000,0.005688,0.00000,0.048345,0.011375,0.002844,0.002844,0.025594,0.00000,0.002844,0.142191,0.005688,0.002844,0.00000,0.000000,0.002844,0.005688,0.000000,0.045501,0.00000,0.008531,0.008531,0.005688,0.014219,0.042657,0.002844,0.011375,0.011375,0.000000,0.00000,0.00000,0.002844,0.091002,0.258787,0.139347,0.031282,0.008531,0.019907,0.108065,0.088158,0.068252,0.014219,0.008531,0.082471,0.002844,0.00000,0.005688,0.00000,0.025594,0.005688,0.00000,0.008531,0.002844,0.008531,0.002844,0.002844,0.002844,0.002844,0.00000,0.028438,0.000000,0.002844,0.002844,0.076783,0.002844,0.486293,0.000000,0.000000,10.129678,1.006711,1.473097,0.162098,0.017063,0.025594,0.036970,0.014219,0.005688,0.008531,0.022751,0.005688,0.000000,0.00000,0.551701,0.275850,0.139347,0.056876,0.133659,0.136503,0.045501,0.048345,1.302468,0.153566,0.375384,0.059720,0.147879,0.017063,0.005688,0.005688,0.167785,0.011375,0.000000,0.025594,0.048345,0.054033,0.000000,0.005688,0.000000,0.017063,0.002844,0.008531,0.221818,0.00000,0.022751,0.002844,0.00000,0.008531,0.00000,1.598225,0.014219,0.048345,0.085315,5.081902,0.031282,0.597202,0.014219,0.460698,0.028438,0.048345,0.011375,0.164941,1.177340,0.116597,0.378228,0.102377,0.042657,0.071095,0.036970,0.054033,0.065408,0.284382,0.338414,0.224662,0.011375,0.034126,0.002844,0.005688,0.267319,0.102377,0.238881,0.176317,0.821863,0.002844,0.022751,0.002844,0.028438,0.008531,0.236037,0.014219,0.005688,0.000000,0.00000,0.008531,0.005688,0.017063,0.005688,0.085315,0.139347,0.085315,0.028438,0.005688,0.000000,0.002844,0.127972,0.025594,0.002844,0.062564,0.002844,0.091002,0.014219,0.039813,0.036970,0.019907,0.000000,0.051189,0.011375,0.008531,0.002844,0.011375,0.000000,0.014219,0.014219,0.048345,0.381072,0.014219,0.017063,0.002844,0.00000,0.059720,0.017063,0.00000,0.014219,0.025594,0.028438,0.00000,0.011375,0.000000,0.000000,0.000000,0.002844,0.017063,0.005688,0.156410,0.014219,0.00000,0.019907,0.005688,0.000000,0.00000,0.014219,0.00000,0.005688,0.014219,0.00000,0.019907,0.00000,0.255944,0.190536,0.025594,7.064043,0.383915,2.801160,0.110909,0.011375,0.725173,0.153566,0.423729,0.324195,0.366852,3.841997,0.014219,0.201911,0.002844,0.011375,0.002844,0.008531,0.028438,1.251280,1.345126,0.287226,4.274258,5.309407,0.073939,0.00000,0.005688,0.008531,0.159254,0.045501,0.059720,0.002844,0.056876,0.312820,0.236037,0.045501,0.025594,0.253100,0.062564,0.008531,0.025594,0.031282,0.002844,0.011375,0.002844,0.196223,0.025594,0.088158,0.054033,0.031282,0.278694,0.122284,0.002844,0.011375,0.014219,0.00000,0.002844,0.076783,0.182004,0.00000,0.002844,0.005688,0.059720,0.002844,0.011375,0.019907,0.002844,0.014219,0.065408,0.002844,0.002844,0.560232,0.014219,0.00000,0.073939,0.688204,0.150722,0.764987,0.014219,0.005688,2.840974,0.002844,0.005688,0.019907,0.002844,0.042657,0.005688,0.005688,0.338414,0.031282,0.025594,0.187692,0.019907,0.054033,0.782050,0.045501,0.014219,0.014219,0.000000,0.00000,0.002844,0.005688,0.002844,0.000000,0.019907,0.656922,0.056876,0.019907,0.019907,0.000000,0.338414,0.369696,0.042657,0.00000,0.014219,0.00000,0.00000,0.000000,0.002844,0.005688,0.139347,0.039813,0.022751,0.005688,0.116597,0.241724,0.193380,0.125128,0.008531,0.000000,0.022751,0.036970,0.085315,0.00000,0.002844,0.332727,0.042657,0.048345,0.119440,0.036970,0.036970,0.142191,0.278694,0.014219,0.014219,0.099534,0.011375,0.122284,0.992492,2.420089,0.011375,0.025594,0.051189,0.147879,0.056876,0.352633,0.008531,0.056876,0.076783,0.002844,0.011375,1.973609,0.065408,0.014219,0.00000,0.002844,0.005688,0.002844,0.002844,0.019907,0.005688,0.011375,0.019907,0.011375,0.011375,0.011375,0.005688,0.025594,0.005688,0.002844,0.002844,0.000000,0.022751,0.022751,0.017063,0.000000,0.017063,0.005688,0.002844,0.022751,0.008531,0.068252,0.002844,0.000000,0.002844,0.002844,0.000000,0.002844,0.00000,0.000000,0.011375,0.002844,0.000000,0.002844,0.002844,0.005688,0.000000,0.00000,0.000000,0.00000,0.00000,0.014219,0.091002,1.103401,0.002844,0.000000,0.008531,0.000000,0.017063,0.022751,0.014219,0.005688,0.034126,0.00000,0.008531,0.005688,0.324195,0.002844,0.002844,0.002844,0.005688,0.002844,0.000000,1.504379,0.002844,0.028438,0.108065,0.031282,0.011375,0.019907,0.079627,0.182004,0.045501,0.008531,0.008531,0.093846,0.000000,0.054033,0.099534,0.025594,0.133659,0.019907,0.031282,0.019907,0.102377,0.153566,0.221818,0.153566,0.00000,0.164941,0.002844,0.002844,0.017063,0.017063,0.028438,0.008531,0.005688,0.00000,0.017063,0.002844,0.008531,0.002844,0.00000,0.005688,0.000000,0.025594,0.00000,0.00000,0.000000,0.00000,0.005688,0.000000,0.005688,1.322375,0.147879,0.108065,0.042657,0.190536,0.304288,0.597202,0.386759,0.366852,0.278694,0.048345,0.187692,0.008531,0.022751,0.014219,0.076783,0.000000,0.017063,0.000000,0.341258,0.159254,0.00000,0.002844,0.014219,0.019907,0.019907,0.022751,0.005688,0.002844,0.036970,0.005688,0.000000,0.002844,0.000000,0.019907,0.000000,0.002844,0.008531,0.008531,0.002844,0.008531,0.002844,0.00000,0.008531,0.00000,0.00000,0.017063,0.00000,0.000000,0.002844,0.002844,0.002844,0.002844,0.000000,0.000000,0.00000,0.00000,0.002844,0.000000,0.000000,0.000000,0.002844,0.000000,0.000000,0.000000,0.008531,0.002844,0.002844,0.00000,0.00000,0.017063,0.00000,0.00000,0.00000,0.002844,0.002844,0.00000,0.002844,0.000000,0.014219,0.002844,0.00000,0.005688,0.002844,0.002844,0.002844,0.017063,0.002844,0.005688,0.000000,0.002844,0.000000,0.002844,0.005688,0.005688,0.011375,0.000000,0.008531,0.000000,0.005688,0.011375,0.000000,0.022751,0.008531,0.039813,0.000000,0.00000,0.000000,0.005688,0.00000,0.019907,0.002844,0.00000,0.011375,0.000000,0.00000,0.00000,0.000000,0.00000,0.000000,0.008531,0.022751,0.005688,0.002844,0.000000,0.00000,0.002844,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.005688,0.00000,0.287226,0.287226,0.233193,0.278694,0.028438,0.005688,0.000000,0.00000,0.002844,0.002844,0.002844,0.000000,0.00000,0.00000,0.00000,0.00000,0.153566,0.005688,0.002844,0.00000,0.002844,0.005688,0.002844,0.00000,0.002844,0.002844,0.011375,0.00000,0.187692,0.079627,0.005688,0.011375,0.00000,0.00000,0.025594,0.108065,0.00000,0.008531,0.099534,0.00000,0.00000,0.00000,0.005688,0.002844,0.002844,0.005688,0.00000,0.00000,0.005688,0.005688,0.002844,0.005688,0.00000,0.002844,0.008531,0.014219,0.005688,0.017063,0.008531,0.076783,0.017063,0.028438,0.034126,0.002844,0.005688,0.005688,0.014219,0.005688,0.045501,0.002844,0.019907,0.002844,0.00000,0.036970,0.00000,0.005688,0.000000,0.002844,0.00000,0.005688,0.00000,0.002844,0.005688,0.008531,0.002844,0.002844,0.011375,0.085315,0.176317,0.000000,0.213286,0.008531,0.008531,0.295757,0.005688,0.022751,0.002844,0.00000,0.002844,0.000000,0.005688,0.301445,0.193380,0.031282,1.592538,0.082471,0.068252,0.005688,0.068252,0.008531,0.011375,0.509043,0.005688,0.002844,0.042657,0.008531,0.031282,0.017063,0.005688,0.000000,0.002844,0.062564,0.002844

--- number_diagnoses ---

              count      mean       std  min  25%  50%  75%   max
readmitted
<30         11314.0  7.691798  1.774833  1.0  6.0  9.0  9.0  16.0
>30         35502.0  7.645964  1.812102  1.0  6.0  9.0  9.0  16.0
NO          52527.0  7.174139  2.029145  1.0  5.0  8.0  9.0  16.0

max_glu_serum      >200      >300      Norm  not_measured
readmitted
<30            1.626304  1.582111  2.598550     94.193035
>30            1.492874  1.467523  2.492817     94.546786
NO             1.342167  0.929046  2.600567     95.128220

A1Cresult         >7        >8      Norm  Not measured
readmitted
<30         3.385186  7.150433  4.251370     85.213010
>30         3.661766  8.168554  4.495521     83.674159
NO          3.982714  8.429950  5.416262     82.171074

metformin       Down         No     Steady        Up
readmitted
<30         0.609864  82.870780  15.741559  0.777797
>30         0.535181  81.122190  17.365219  0.977410
NO          0.599692  78.670017  19.534715  1.195576

glimepiride      Down         No    Steady        Up
readmitted
<30          0.220965  95.315538  4.136468  0.327028
>30          0.188722  94.636922  4.887049  0.287308
NO           0.188474  94.882632  4.580501  0.348392

glipizide       Down         No     Steady        Up
readmitted
<30         0.751282  87.219374  11.154322  0.875022
>30         0.591516  86.682440  11.920455  0.805588
NO          0.481657  87.897653  10.899157  0.721534

glyburide       Down         No    Steady        Up
readmitted
<30         0.459608  90.030051  8.759060  0.751282
>30         0.628134  89.532984  9.067095  0.771788
NO          0.542578  89.188417  9.427533  0.841472

pioglitazone      Down         No    Steady        Up
readmitted
<30           0.159095  93.176595  6.407990  0.256320
>30           0.126753  92.237057  7.377049  0.259140
NO            0.102804  92.904601  6.785082  0.207512

rosiglitazone      Down         No    Steady        Up
readmitted
<30            0.044193  94.131165  5.656709  0.167934
>30            0.061968  93.217284  6.574278  0.146471
NO             0.110419  93.846974  5.852228  0.190378

insulin          Down         No     Steady         Up
readmitted
<30         14.963762  41.859643  30.228036  12.948559
>30         13.362627  44.887612  29.485663  12.264098
NO          10.415596  48.940545  30.805110   9.838750

change             Ch         No
readmitted
<30         49.010076  50.989924
>30         48.591629  51.408371
NO          44.407638  55.592362

diabetesMed         No        Yes
readmitted
<30          19.736610  80.263390
>30          20.334066  79.665934
NO           25.076627  74.923373

### Analiza kategorijskih atributa

Kategorijski atributi analizirani su kroz raspodelu njihovih vrednosti u odnosu na ciljnu promenljivu `readmitted`. Kod pojedinih atributa uoceni su izrazeniji obrasci izmedju grupa, dok su kod drugih raspodele bile veoma slicne.

Za detaljniju procenu povezanosti odabranih kategorijskih atributa sa `readmitted` primenjuju se hi-kvadrat test i Cramerov V koeficijent.

### Zakljucak analize kategorijskih atributa

Kod `medical_specialty` utvrdjena je statisticki znacajna, ali slaba povezanost sa `readmitted` (Cramerov V = 0.086), dok je kod `max_glu_serum` utvrdjena statisticki znacajna, ali veoma slaba povezanost (Cramerov V = 0.016). Na osnovu rezultata ove analize atributi nisu automatski eliminisani, vec su zadrzani za naredne faze obrade i modelovanja.

### Analiza numerickih atributa

Na osnovu deskriptivne analize izdvojeni su numericki atributi kod kojih su uocene izrazenije razlike izmedju grupa `readmitted`: `time_in_hospital`, `num_medications`, `number_outpatient`, `number_emergency` i `number_inpatient`.

Za ispitivanje statisticke znacajnosti razlika izmedju tri nezavisne grupe primenjuje se Kruskal-Wallis test.

In [94]:
numerical_columns = [
    'time_in_hospital',
    'num_medications',
    'number_outpatient',
    'number_emergency',
    'number_inpatient'
]

for col in numerical_columns:
    groups = [
        data.loc[data['readmitted'] == category, col].dropna()
        for category in ['<30', '>30', 'NO']
    ]
    
    stat, p = kruskal(*groups)
    
    print(f"{col}:")
    print(f"Kruskal-Wallis statistic = {stat:.4f}")
    print(f"p-value = {p:.4e}")
    print()

time_in_hospital:
Kruskal-Wallis statistic = 522.6134
p-value = 3.2804e-114

num_medications:
Kruskal-Wallis statistic = 627.8269
p-value = 4.6679e-137

number_outpatient:
Kruskal-Wallis statistic = 1276.2914
p-value = 7.1917e-278

number_emergency:
Kruskal-Wallis statistic = 1692.8219
p-value = 0.0000e+00

number_inpatient:
Kruskal-Wallis statistic = 5972.5782
p-value = 0.0000e+00

Kruskal-Wallis testom utvrdjeno je da za svih pet analiziranih numerickih atributa postoje statisticki znacajne razlike izmedju grupa ciljne promenljive readmitted (p < 0.001). Na osnovu toga, ovi atributi nisu eliminisani u ovoj fazi analize, vec su zadrzani za dalju obradu i modelovanje.

In [96]:
data[
    ['num_lab_procedures',
     'num_procedures',
     'num_medications',
     'time_in_hospital',
     'number_outpatient',
     'number_emergency',
     'number_inpatient',
    'number_diagnoses']
].corr(method='spearman')

,num_lab_procedures,num_procedures,num_medications,time_in_hospital,number_outpatient,number_emergency,number_inpatient,number_diagnoses
num_lab_procedures,1.000000,0.016508,0.248416,0.338932,-0.023744,0.008058,0.041246,0.165544
num_procedures,0.016508,1.000000,0.348619,0.186796,-0.023753,-0.046510,-0.064419,0.063339
num_medications,0.248416,0.348619,1.000000,0.463446,0.075430,0.045545,0.100765,0.293927
time_in_hospital,0.338932,0.186796,0.463446,1.000000,-0.013686,-0.000782,0.093031,0.237700
number_outpatient,-0.023744,-0.023753,0.075430,-0.013686,1.000000,0.179225,0.156665,0.113742
number_emergency,0.008058,-0.046510,0.045545,-0.000782,0.179225,1.000000,0.222692,0.093217
number_inpatient,0.041246,-0.064419,0.100765,0.093031,0.156665,0.222692,1.000000,0.136186
number_diagnoses,0.165544,0.063339,0.293927,0.237700,0.113742,0.093217,0.136186,1.000000

Analizom korelacija izmedju numerickih atributa nije utvrdjena jaka povezanost izmedju posmatranih promenljivih. Na osnovu toga nije uocena izrazenija redundantnost medju numerickim atributima, odnosno nema osnova za eliminaciju atributa zbog dupliranja informacija. Numericki atributi su stoga zadrzani za dalju analizu i modelovanje.

In [97]:
data[['diag_1', 'diag_2', 'diag_3']].nunique()

diag_1    715
diag_2    747
diag_3    786
dtype: int64